### ISSUE TITLE
ADAM filenames: Replace umlauts/spaces/special chars/uppercase

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#1033]
**example file: filename on PC:** 
dies ist ein test  doppelsabstand öäü ÖÄÜ!.docx

**example file: filename after upload with ADAM:** 
dies ist ein test  doppelsabstand öäü ÖÄÜ!.docx

(note that there is a double space in the filename before&after, which gets replaced by github.)

**url looks like this**
http://www.my-website.xy/Portals/0/adam/Content/oTCLEXlyk0WQwDBcFWNJHw/DocumentOrLink/dies%20ist%20ein%20test%20%20doppelsabstand%20%C3%B6%C3%A4%C3%BC%20%C3%96%C3%84%C3%9C!.docx

**critical characters**
- umlauts
- uppercase characters
- spaces
- special characters like brackets, questions marks, ...

**suggestions:**
- do all the replaces automatically, or
- offer configuration for ADAM-Filenames
-- replacement table (space => "-", ä => ae, "!" => 0)
-- force lowercase yes/no selection

**benefits:**
- no problems with different sytems, browsers,..
- beautiful and short urls, especially for google

**Comment by iJungleboy** [comment]
Here's my short analysis for this feature:

1. implementing a simple, forced version would be about 4-6h work in total (with documentation, testing, bug-fixing)
2. implementing a configurable version would be 8-16h (with documentation, testing, follow-up, etc.)
3. maintenance cost per year probably 2-4h
4. support cost per year because questions pop up and must be treated: 2-4h

Benefits
1. no problems with browsers - as far as I know, url encoding works anyhow, so I don't think this is an issue
2. shorter, nicer links - this is true, but we already have a fairly ugly GUID in the url, so it's not really nice and short, just nicer and shorter

Disadvantages
1. we're changing things the user uploads - this always leads to some support incidents, like in cases where a word with ä and another word with ae exists, and mean something different
1. if we change the name automatically, where will be the wish to modify it again manually - this feature would again cost extra work/time/support

So there's a cost which realistically is 10h first year, ca. 4h follow up years and the benefit seems small to me. @reto-f-999 What's your take on this? Is the benefit great enough that cover the cost?

**Comment by reto-f-999** [comment]
thanks for the analysis, the benefit does not really match with the estimated effort ;-) thought it would be much easier. 

The reason why I asked was a specific user problem, but the problem was in fact something else. Because there are widely known problems with url encoding - even google has some kind of problems though it's a standard - I thought this could be generally helpful.

**Comment by iJungleboy** [comment]
ok, then let's close this.
