### ISSUE TITLE
Page picker: switch between locales

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#1053]
The page picker only shows pages in the current locale. It would be optimal to switch between locales. Otherwise, it is sort of pointless to edit content in other cultures if you have to switch cultures in DNN. Does that make sense? In previous versions, i think before the control was loaded in a modal, you could switch. 

![image](https://cloud.githubusercontent.com/assets/3790873/21015467/b0f28a82-bd27-11e6-87f5-42c096c24ebf.png)

**Comment by iJungleboy** [comment]
We looked into this more deeply, and it's basically impossible to do this from JS, the DNN control just isn't modern enough. At the moment it takes the language of which the dialog was opened. 

Note also that in the background, when you link to a page "About Us" in EN and leave the link in DE, the DE visitor will automatically receive the "Über Uns" page as a link, since the link-resolution automatically links to the correct language. 

## Simple Workaround
If you ever really need this - like if a page is missing in one language - then you'll have to open the dialog from the page which has the "right" language. 

For now we'll close this, as we won't fix it on our side. Once DNN enhances these components, we'll include the improved components.
