### ISSUE TITLE
EAV_ChangeLog table cannot be purged

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#1075]
The ChangeLog table can grow up quickly but cannot be purged because the foreign keys like ChangeLogModified or ChangeLogCreated in related tables (entities, attributes) - are 'not null'.

Is there a good reason to keep these columns not null? Making them nullable would permit to keep the database slimmer by deleting the ChangeLog records periodically.

**Comment by iJungleboy** [comment]
Making it not-nullable would create future issues, because the change-log contains things which time-stamp a specific action (which would go missing, needing much additional code to handle those cases). So making it nullable right now is not an option. 

BUT: You can easily purge most of the items which are "not in use" - this would still remove 90-99% of everything. might need some sql-scripting to do it. If you create it, please post it in this issue for all to share. 

I quickly googled it - this will probably help. http://stackoverflow.com/questions/3312876/elegant-way-to-delete-rows-which-are-not-referenced-by-other-table

So please try it, and post your sql here for others to find :)

**Comment by BravoSierra** [comment]
Here it is (it removed 40% of the ChangeLog rows). 

delete ToSIC_EAV_ChangeLog where not exists
   (select * from ToSIC_EAV_entities e where e.ChangeLogCreated = ToSIC_EAV_changelog.ChangeID or e.ChangeLogDeleted = ToSIC_EAV_changelog.ChangeID or e.ChangeLogModified = ToSIC_EAV_changelog.ChangeID )  
and not exists
   (select * from ToSIC_EAV_attributes a where a.ChangeLogCreated = ToSIC_EAV_changelog.ChangeID or a.ChangeLogDeleted = ToSIC_EAV_changelog.ChangeID)
and not exists
  (select * from ToSIC_EAV_attributeSets s where s.ChangeLogCreated = ToSIC_EAV_changelog.ChangeID or s.ChangeLogDeleted = ToSIC_EAV_changelog.ChangeID)
 and not exists
   (select * from ToSIC_EAV_values v where v.ChangeLogCreated = ToSIC_EAV_changelog.ChangeID or v.ChangeLogDeleted = ToSIC_EAV_changelog.ChangeID or v.ChangeLogModified = ToSIC_EAV_changelog.ChangeID )

**Comment by iJungleboy** [comment]
Perfect, thanks!
