### ISSUE TITLE
V.8.11 Some issues in partial Import/Export

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#1130]
I've working with partial import/export last days were heavily. There are some issues:
1. I try to import an Contenttype which has added Values for an Dropdownfield to update an existing Contenttype. The new values are not imported.

2. Same happens with metadata for the contenttype. They are not imported.

3. I made an import for a Contenttype, that doesn't exist. Sometimes an WYSISWYG-Field is created as a string/default field, but that happens not always...

**Comment by iJungleboy** [comment]
Here's what's happening:

1. On a "normal" import, the rule is to add missing things, but to leave conflicts untouched. That's why it's not updating things which were already defined. This can be overruled with an attribute in the XML, but I would have to look it up for you - you can find some examples in the newer 2sxc install-xmls.
2. metadata: this is something we haven't implemented yet, our bad :(
3. This is because of old/new ways of describing the field. In 08.05 or something we created sub-types for a field, like `@String` has all things which every string-field has, while `@string-dropdown` has the fields which only dropdown-fields have. A normal field is described my multiple items, usually a combination of `@All` (containing is-hidden, title, description etc.), an item `@String` (which today doesn't have any fields at all), and an item `@string-[typename]` which contains infos special for that input-type. What you are experiencing is a history-problem: Your export probably still has the values in the `@String` item (which should be empty, but still works because old fields have data configured in it). But it's not imported any more. So the resolution is to fully configure the original fields again (that way ensuring that the config-settings are in the right fields), and then exporting/importing.
