### ISSUE TITLE
Error:  There are more presentation elements than content elements

### ISSUE THREAD

**Issue by TwoHeadsBrewing** [2sic/2sxc#1158]
I have several modules that utilize a list and when I re-order or try to add new items to the list, I receive the error shown in the title.  I have noticed that on one of my modules, the data set contains 4 items.  But in the  "re-order" tool, I see 6 items.  Two of the items do not have a title, just a "(0)".  

It seems like the database has not been updated or cleaned for some reason?  Please advise.

**Comment by iJungleboy** [comment]
This is correct behaviour. 

The (0) null entries are empty slots. The system automatically substitutes the demo-item there if your template has this. It's meant for rapid prototyping and similar scenarios.

**Comment by TwoHeadsBrewing** [comment]
How is this correct behavior?  I can no longer order, add, or remove entries from this collection.  In order to "fix" this, it's necessary to delete the entire module, re-add it, then re-create all of the content.

**Comment by iJungleboy** [comment]
Ok, I was a bit to fast in answering. 

Let's start over: in general each module-instance has two lists, one for items assigned and one for presentation items assigned - IF your template has presentation items configured. The presentation item-list is very commonly all nulls = "fallback to default" as that's the most needed behavior. I don't know why your two lists are not in sync, my best guess is that you already assigned items, demo-items etc. and then changed the template configuration, causing this error to appear. 

The error you're seeing is an error-check because if this happens, this could lead to unexpected situations. But you can fix it manually. Let me try to explain:

1. each module-instance internally has a content-item storing the configuration (what template ,what items, etc.). This item is of a type "2SexyContent-ContentGroup" in the hidden scope "2SexyContent-System"
2. you can find these by going to app-admin, data, then switching scopes as described in this blog post http://2sxc.org/en/Blog/post/advanced-dynamic-data-content-understanding-content-type-scopes
3. Note that each app keeps it's own set of ContentGroups, so you have to be on the correct app to find your "damaged" content-group.
4. You should now be able to find your item and fix it manually. It's a bit of a pain, but I think in all these years you're only the second person to run into this, so I assume it won't happen again. 

Hope this helps :)

**Comment by iJungleboy** [comment]
@TwoHeadsBrewing We just had a second case like yours, so it could be an issue. In our case this occured on a site which had 2sxc for a long time, and was just upgraded to 8.12. The template had no presentation settings at all. Does this match your setup?

**Comment by iJungleboy** [comment]
@TwoHeadsBrewing I believe the error occured in an older version of 2sxc - and is actually fixed in 8.12. But 8.12 detected it, so it complained. Could this be the same in your case?

**Comment by iJungleboy** [comment]
Someone else had the same issue, will reopen and try to close
