### ISSUE TITLE
Improve highlight of items in quick-dialog

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1204]
At the moment it looks like this if selected

![image](https://cloud.githubusercontent.com/assets/5321186/26753851/f61d6fe0-486f-11e7-83fb-658e88d62877.png)
...or like this...
![image](https://cloud.githubusercontent.com/assets/5321186/26753864/209fb9bc-4870-11e7-856c-4091cd39c6ca.png)

which is very strange, and the blue area changes depending on how flat/square the preview-image is. this is not good. Better to put a blue--50%-transparent-shade over everything, not just behind it.

**Comment by christophbuehler** [comment]
Because the preview images are not formatted in a consistent way (grayscale, dimensions), I would not try to change the appearance of the image itself.

This is my proposal:

![image](https://cloud.githubusercontent.com/assets/4547315/26823290/5f771920-4aad-11e7-8c71-100d559cca06.png)

**Comment by iJungleboy** [comment]
I believe your solution moves the thumbnail, which is against material design paradigms and forces us to plan more space around the images. I believe I would rather not do that, and instead use a blue shadow/glow for selection. Could you try that?

**Comment by christophbuehler** [comment]
Is this against MD paradigms? I am not sure about that. The height of the element did not increase, because there is enough spare room.
Colored shadows are invalid, though. Shadows can't have colors, they simply block off the light. In order to make the area of the shadow visually appear in a certain color, the background has to have that color. That's why this looks kind of odd:
![image](https://user-images.githubusercontent.com/4547315/26868839-957c7502-4b6a-11e7-9ee5-ecf9f967562c.png)

One alternative would be to make the shadow bigger (I still favor the y-translation):
![image](https://user-images.githubusercontent.com/4547315/26869046-4a036396-4b6b-11e7-9675-8e0991e903ad.png)

**Comment by iJungleboy** [comment]
For the moment we decided to go with blue, as it's very clear. Pls finish and post the code, closing this task.

**Comment by christophbuehler** [comment]
`box-shadow: 0 14px 28px rgba(0, 120, 220, 0.25), 0 10px 10px rgba(0, 120, 220, 0.22);`
