### ISSUE TITLE
User Profile and 2sxc question

### ISSUE THREAD

**Issue by andyduo** [2sic/2sxc#1239]
Is it possible to use 2sxc in the User Profile section of DNN to allow custom fields to be input and displayed on the user profile page? For example I'd like to provide a template where the logged in user can upload a few images to display on their profile.

Thanks!

**Comment by iJungleboy** [comment]
This could be done, but you would have to create a custom profile-page (instead of the automatically generated one by DNN). So the simplest version is to create a 2sxc-page showing the dnn-profile fields + the relevante 2sxc data. 

Alternately you could create a razor-page and just query 2sxc for the data you need.
