### ISSUE TITLE
JS / jQuery syntax highlight stops working between functions

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1276]
I'm submitting a bug report about edit experience / UI

Somewhere along this function syntax highlight gets broken and all code bellow is black.
https://pasteboard.co/GI3SmfB.jpg

2sxc version: 9.4.1
Browser: Firefox, edge, chrome
DNN: 9.1.1

**Comment by iJungleboy** [comment]
Thanks. What is the file ending of the file you're editing? .js, .cshtml, etc.? 
Does the error occur when opening the file, or does it happen after a few minutes of work?

just fyi: we're using the ACE open source editor for code editing.

**Comment by eXistenZe** [comment]
It js inside script tags in a .cshtml file.
The error occurs when opening the file.

**Comment by iJungleboy** [comment]
This is a limitation of the ACE editor - it cannot change context and basically provides intellisense for the primary expected type, which is guessed by the extension. So ATM there is no perfect solution for this - we use VS Code to do any extensive app development and simply use the integrated editor for quick changes. 

This is also because many advanced apps need a build process like gulp/grunt or Webpack, which requires a VS-Code setup anyhow.
