### ISSUE TITLE
SourceEditorSnippets.Content.Fields.Title only show for first file opened

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1277]
I'm submitting a bug report about edit experience / UI.

When I edit a view template from the toolbar or the settings DNN menu, the SourceEditorSnippets.Content.Fields.Title populate fine.

If I "quick-pick another file" (top left option in the editor) and open some other file from the same project/data (I only have two: list and details), the SourceEditorSnippets.Content.Fields.Title are empty.

2sxc version(s): 9.4.1
Browser: all
DNN: 9.1.1

**Comment by iJungleboy** [comment]
This is because the new template was opened "neutrally" without context. Think of it this way: each template file could be used in different scenarios (you can assign it multiple times) and there is no way the system could guess, for which scenario you are editing it. 

If you open it from a in-page toolbar, there is a context attached which the editor can build upon, but once you open other files, it's not clear in what context that happens. 

This is why the behaviour is ilke this. I admit there would be more perfect ways of doing it - incl. #905, but atm we didn't find the resources to do it.
