### ISSUE TITLE
[Feature request] Disable extension toolbar (to add app or content) on page (non-edit mode)

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1298]
**I'm submitting a ...**
[x] feature request

**...about** 
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
When we mouseover any available container on the page (not sure if this is the correct name, but I mean the place where you can insert modules on the skin/template), a toolbar appears with 3 icons (add content, app or select). This can be very intrusive when editing 2sxc app template and I clicked it by accident quite a few times.

**Expected behavior**
Show this toolbar only in DNN edit mode.

* **2sxc version(s):** 9.5.1 
* **Browser: [all]
* **DNN:** [9.1.1 ] 
* **Language:** [English]

**Comment by iJungleboy** [comment]
Our plan for this is a bit different - let me explain:

For us the "edit view" is terrible and we avoid it at all cost. It's slow, the page preview is bad, etc. So our goal is to create a solution, which works in "normal" view. 

In the future, we will show the "pick app" or "pick content-type" directly on click, and a user will be able to cancel it if he/she wants to. This will prevent any accidental addition. 

If you want to implement this feature as you want it, you can easily do this already. Basically you can control the behavior of the quickE toolbar using a special info is added to any html-node in your page, and anything inside this will adjust to you this. This is sometimes needed for VeryRichContent or InnerContent, because the toolbar would otherwise cause side-effects. 

So for your case, you can simply add / remove this special html attribute using a tiny bit of code based on the view. Here are the docs to it: https://github.com/2sic/2sxc/wiki/Html-Js-$quickE

As we won't implement it as discussed in this issue, and there is a viable workaround for anybody that wants it like this, I'll close this now.
