### ISSUE TITLE
Toolbars show incomplete items available in list view with App.Data["my_entity"]

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1313]
**I'm submitting a ...**
[x] bug report => search github for a similar issue before submitting 
[x] feature request
[x] not sure

**...about**
[x] edit experience / UI
[x] admin experience UI
[x] Razor templating

**Current behavior**

When I create a new view with a new template, I activate the list view and set the loop as:
```
@foreach(var Content in AsDynamic(Data["Default"]))
@Edit.Toolbar(Content)
```
This works fine as the toolbar will show add, replace, edit, etc, and I can start working on adding content.

However, if I do this:
```
@foreach(var Content in AsDynamic(App.Data["my_entity"]))
@Edit.Toolbar(Content)
```
This toolbar will not show any add, replace, etc stuff related to the entity content (just edit), even if I try to force it with:
`@Edit.Toolbar(actions: "new", contentType: "my_entity")`

**Expected behavior**
Using
```
@foreach(var Content in AsDynamic(App.Data["my_entity"]))
@Edit.Toolbar(Content)
```
Should display the full content toolbar.

**What is the motivation / use case for changing the behavior?**
This is particularly useful when pulling data from two entities to the same view in the same app.

* **2sxc version(s):** 9.6.0
* **Browser:** [all ]
* **DNN:** [9.1.1 ] 
* **Language:** [English]

**Anything you would like to add**
Thank you for your hard work.

**Comment by iJungleboy** [comment]
Hi @eXistenZe this is a common misconception. 

You are confused by data behaving differently, when it's assigned to this instance or when using it as data. Best read up on it on http://2sxc.org/en/blog/post/12-differences-when-templating-data-instead-of-content

**Comment by eXistenZe** [comment]
Thanks.

Can't quite figure why data cannot have the same add/delete buttons as content. It would have exactly the same behavior as creating or deleting an item from the app admin panel (it manages data, not content, right?).

I understand content allows multiple app/module implementations with separate content, but using data has some heavy possible implementations too... In my example, I was trying to create a single list view for a couple of different "details" (different) views in the same app. Content does not work since I can only assign one content to one view. Data would work fine, but I cannot manage it with the default toolbar.

Let's call it a feature request then.

**Comment by Accuraty** [comment]
Try this for a rephrase/rethink... With Content you are adding/deleting "slots" where Content can be assigned to (from your Data/records). Seriously, read that last sentence again. The "slots" are like content containers. You start with 1, but you can add many and they will repeat down the page using your repeater in the template. 
 
So imagine you have 5 People in your Content data (5 records). You add a Content module, set the token template to a basic repeat of the default data and nothing appears. This is because you have a slot with nothing assigned to that slot. (Or if you have a default item set, that 1 item shows up). So now the hover UI for the "slot" has 4 choices:
1. pencil/edit; means "edit the assigned record" (which is why, if nothing is assigned to the slot, you instead get to add (blank record form) [which can be more confusing if there is a demo/default item assigned because you still get a blank/add - which DOES make sense if you think about it; nothing is assigned to the slot, you are just seeing the select demo/default item]). 
2. plus/add; always lets you add a record (that self-assigns to this slot).  
3. glasses; change view/template
4. 3 dots “…” which rotate the UI on to the more advance choices...
  
This all makes more sense when you want to assign one of the existing records to a slot (see crossover arrows below, but please read them all carefully; it should start to make sense). You have to click the "..." so you can see the 8 (or 7 if you are on the first or last slot) blue-round UI options; which are:
"+" (add a new empty slot in the position after this one), 
“-“ (delete the current slot [does NOT delete the assigned record in the data]), 
the angle-up arrow (move this slot up/left [swap it with prev]), 
the angled-down arrow (move this slot forward 1 position [swap it with the next slot]), 
ordered list icon (pops up a UI to drag-drop rearrange all the slots), 
crossover arrows (assign an available data record to this slot)
clock (history), etc.
 
As you can see this “slot” (which is what your repeated is repeating for Content) concept for Content is very powerful … assigning data to the slot is completely different than the list/detail data you appear to be locked in to thinking about. If it hasn’t clicked yet, go experiment until it does. It will. Cheers! - Jeremy
 
PS, when it starts to click, go read Daniel's blog post again anyhow. Worth it!!

**Comment by eXistenZe** [comment]
First of all, thank you very much for the explanation.

2sxc content management seems indeed quite powerful (and very easy to manage to some degree). Let me give you some reasons why I have some difficulties learning how to properly understand data structure and querying:

We (most non-programmers) first learn to work with data from excel sheets. Then perhaps SPSS. Then maybe Access. Then move to mysql and sql server. Either step is one above the last and they all have one thing in common: you can see the global picture of the data (simple 2D table if needed, with more or less effort). Seeing the data makes you think on how to query it or select it or manage it (kinda like the baby concept of "I see you, you exist"). 2sxc is not one step above these, but quite a few leaps forward. The icache concept is way more advanced than anything I have used before. It's difficult to understand. Where is it? How does it work? Is it safe? If things go south how do I solve problems in it? You probably laughed at some of these questions, but they are real.

Not seeing the data (the full data, like a database - Select * FROM 2sxc) makes it hard to work with. You have entities that groups stuff like a table, but even then there is content (instance associated) and data (app associated). And they are definitely not the same, although linked through entities.

Some other questions that occurred to me recently that may not make sense at all to you:
- Can I assign a row (data - created through admin panel) to a content slot?
- What happens to deleted data? Is there any remnant info from deleted stuff? Recoverable?

Don't think for a second I don't like 2sxc, I quite love it. I already replaced some FnL apps and most of the Live Forms apps I had in one month cause the capabilities of 2sxc are just amazing. Things that took me one morning now takes 30 mins. And it's free. Can't ask for more.

I will read the post again and search for more basic info.

Thanks again.

**Comment by iJungleboy** [comment]
thx - I understand, it's just that we have such limited resources that it's hard to create the software, documentation, tutorials, blogs, videos ... - so this is atm what we can do. 

1. can you assign existing data - yes, absolutely. check out the replace-button (second set in toolbar, two arrows which intercross)
2. delete: there is remove, and delete. Remove is the round (-) button and happens without a confirmation, because you can always add it again with the feature just mentioned. delete is fairly permanent, meaning that it's gone, but that it could be undeleted because the pre-requisites are there, but there is no gui or something.

**Comment by iJungleboy** [comment]
...and thank @Accuraty for your contribution :)
