### ISSUE TITLE
Feature request: Easier way to edit a file (templates and controllers)

### ISSUE THREAD

**Issue by Eudoxe** [2sic/2sxc#1319]
**I'm submitting a**
* feature request

**about** 
* admin experience UI

**Current behavior**
Unless I'm wrong, the only way to edit a template is either:
- insert it into a page and go into the DNN menu "edit template"
- In the source editor, go to the "quick-pick another file" menu, display all the files and click on the desired file.

**Expected behavior**
1 / Would it be possible to add a button in the list of views in the action column to edit the model directly from this list?

2 / Would it be possible to add this same functionality for the list of .cs files in the api folder (WebApi tab)?

**What is the motivation / use case for changing the behavior?**
Easier way to fast edit templates and controller files

* **2sxc version(s):** 9.6.1

**Comment by iJungleboy** [comment]
Could you add screenshots with arrows to clarify what you mean?

**Comment by Accuraty** [comment]
Wait to see screenshots, but if I understand correctly, I do agree with this feature request. Many times I have been in one or other of the lists and been surprised I could not click edit from there. 
 
E.g. go to Admin, Administration popup, click on Views tab, for each, add a button that lets me jump in to the editor. Also, if I do click on an item in the list and go to the 2nd popup (detail/meta for the view), at the bottom, there should be an additional button next to Save that allows "Save and Edit" to save my changes and route me to the editor. 
 
Yes, this suggestions make us sound lazy. ;)

**Comment by Eudoxe** [comment]
Here it is... Of course, the blue pen is not really the best icon to use...
Comment of Mr Accuraty is much complete and goes in the way of my suggestion

Thank you very much!

FL

![screen shot suggestion edit template](https://user-images.githubusercontent.com/31480276/31188645-99271774-a903-11e7-9b10-446d8e94b5a6.png)
![screen shot suggestion etit webapi](https://user-images.githubusercontent.com/31480276/31188646-9930b446-a903-11e7-83df-8b0b3952e007.png)

**Comment by iJungleboy** [comment]
For the WebApi I find the wish to absolutely make sense. 

For the template I understand the idea, but I'm not a fan yet. The problem is that there are many places such helper-buttons could be added (we already added these to the in-page toolbar), and once we start adding even more, the UI will soon become crowded - as there won't be a good reason not to add another, and another. In this example, these buttons "could" be wished:

1. edit primary content-type
2. edit items of this content-type
3. edit template
4. edit list-content-type
5. edit demo content-item
6. ...

It also is hard to find even more buttons which clearly show what they do - we already have a few sub-optimal choices and the more buttons we add, the harder it gets. 

Note that there is another reason we don't offer template editing here: if it were here, the next need would be to also have a preview - because the editor won't see what the result is. ATM he's forced to start with creating a preview, and then start editing. But just adding this button will change the flow of work, causing new trouble. So I'm not in yet...

**Comment by Eudoxe** [comment]
So would you  consider editing the template by clicking on the file name of the template (showed on my printscreens - left arrow)? Right now, clicking on the title and clicking on the file name lead to the same screen (editing the attributes of the template}. It would be an alternative to keep the UI lean.

**Comment by iJungleboy** [comment]
@Eudoxe I'm not comfortable with providing edit-file in the template-management, because the admin will not be able to preview his changes - causing a lot of confusion regarding "how to I get a preview for this".

**Comment by Eudoxe** [comment]
I'm sorry to read this but I understand your point of view.

Would you consider having un simple button in the configuration tab opening the editor without any document open? May be this editor could be in its own tab , blank, with the same file selector?

This would be useful for editing other files like js, css, included files, etc.

**Comment by iJungleboy** [comment]
@Eudoxe for us it's important to always feel the user story, what is someone trying to achieve (full picture), and not what single action is he/she trying to perform. From that point of view, I don't see any benefit to accessing this dialog from the template list, as opposed to "from a page which shows the output, and can be refreshed once I make changes". Do you have a user story, which would explain why your suggestion would be very practical?

**Comment by Eudoxe** [comment]
Ok... You'll always tell me that to test, I'll have to open the the output anyway and I can go this way, for js or css included. From this point of view, the only benefit would have been to have less open windows in our browser...

I will not argue any more than that. Thank you very much, any way, for your help but especially to support your solution!
