### ISSUE TITLE
Error in Query-Designer with SQLDataSource prevent complete administration in 2sxc to work

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#1388]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] admin experience UI

**Current behavior**

**Minimal reproduction of the problem with instructions**

I've tested your new SQLDataSource in Visual Query Disgner 2.0 and a simple SQL-Select from an table. Everything works fine!
Then i extend the SQL-Select with an inner Join to another table. I forgot to full qualify a fieldname and got an error. That's correct!
But now i've the following problem: I cannot open in querydesigner the form to change the SQL-Select...i got an error. OK, i close the designer and try to open it again...

Now i got the next problem. I try to open the administration and i got another error :
<img width="776" alt="error2" src="https://user-images.githubusercontent.com/22051626/33174910-30a160dc-d05a-11e7-9cba-653be5214bab.PNG">
 
My Query isn't there and i cannot create a new one...

The same happens at the tab  "Daten": My Content-Types are not shown...
<img width="759" alt="error1" src="https://user-images.githubusercontent.com/22051626/33175048-a551a98c-d05a-11e7-90ed-2b0f528dce3d.PNG">

**Please tell us about your environment:**

* **2sxc version(s):** 9.9 
* **Browser:** [Firefox 57]
* **DNN:** [9.1.1 ] 
* **Language:** [German]

**Comment by iJungleboy** [comment]
this is bad, sorry. 

Could you tell us more what the dnn-event-log shows? it would help us corner the issue. you could also activate extensive logging (https://2sxc.org/en/blog/post/releasing-2sxc-9-6-with-extensive-logging) so we can discover more

**Comment by iJungleboy** [comment]
Just a tip: sometimes the api-calls run in the context of a module, and if that module has an error, some of the API calls fail, not because the API call has an issue, but because the module-context cannot be built. So a quick fix could be to switch the module to another view, and then the error may be gone, so that you can continue to work. 

Please tell me if this was the case, incl. the extensive log so I can fix whereever this happens.

**Comment by classmaxx** [comment]
Here is the event-log:
<img width="373" alt="error3" src="https://user-images.githubusercontent.com/22051626/33184435-dc06d6a6-d07c-11e7-83cf-e6b1f6790a56.PNG">

There is no change in event-log, if I activate extensive logging.

Switch the module to another view, doesn't make any difference...

**Comment by iJungleboy** [comment]
So just fyi: this really seems to be caused because the module-instance causes an error (because of the attached, faulty data-source), which has an unexpected side-effect on the API-call. I'll try to fix, but if you enter the admin-ui through another app (through manage-all-apps, then pick yours) it will probably allow you to fix it as the calls are then not relying on the defect instance

**Comment by classmaxx** [comment]
Thank you for the tip! Calling admin from another app makes it possible to change the query.

**Comment by iJungleboy** [comment]
note: I released 9.10 pre2 yesterday. This should also re-enable all API calls even when the view has a bad data supply
