### ISSUE TITLE
Long term support versions

### ISSUE THREAD

**Issue by Eudoxe** [2sic/2sxc#1406]
This is a suggestion. 

Could you consider having a version flagged as a Long Term Support version? 

Because of the pace of the releases and new releases can break the previous code, I suggest that a version could be LTS so only the bug fixes would be applied to. 

That could help us to test new versions being certain that our production code remains safe. 

For exemple, now that the visual query features are implemented, version 9.11 could be LTS so new versions could be developed leaving this version untouched excepted for the bug fixes, just like the 9.11.1.

Anyway, thank you for the great work the team is doing on this project. It's greatly appreciated!

**Comment by Accuraty** [comment]
I agree with this request. I really love and want the fast paced feature additions/enhancements, but it would be nice to have a Stable/supported release that gets ONLY bug fixes for a while (maybe 60 or 90 days). As a developer, I realize the complexity this can add. So please also know that saying no to this change will be understood and accepted (by me at least). :)

**Comment by iJungleboy** [comment]
I understand the request. At the moment, we can't commit to something like this, because it only works if we "guarantee" to fix things on older versions. Officially we can't and wouldn't do this, but for your info, internally we're kind of handling
* 8.12
* 9.6

As kind of LTS. I guess the question that arises is: which bugs do we fix - especially when future versions have a fix. Maybe we'll also provide this in the form of an SLA or something, where paying customers would only use these "long-term" versions....just thinking out loud....

**Comment by iJungleboy** [comment]
I'm planning on supporting this very soon ;)

Here's my plan
1. Create a special release which is specifically LTS
1. Create branches on all git repos with exactly that version
1. Fix only critical / really breaking bugs if necessary
1. Mark it as LTS and communicate it as such

**Comment by Accuraty** [comment]
Thank you!! Looking forward to. I hope it is easier to manage than I can imagine!!

**Comment by iJungleboy** [comment]
Releasing 9.14 as LTS :) - see blog post https://2sxc.org/en/blog/post/special-edition-2sxc-9-14-lts-long-term-support
