### ISSUE TITLE
Feature Request - Support EasyDNN News as a Datasource; Articles, Categories, Tags, Authors, etc.

### ISSUE THREAD

**Issue by Accuraty** [2sic/2sxc#1416]
**I'm submitting a ...
[x] feature request

**...about**   
[x] Razor templating
[x] Content Types or data management
[x] other / unknown

**Desired behavior**
It would be phenomenal if EasyDNN News could be treated as a data source for List/Content.
 
**What is the motivation / use case for changing the behavior?**
EasyDNN News is a great product, but somehow still only supports plain HTML templates with [TOKEN] replacement. This is too limiting for many use cases.

**2sxc version(s):** 9+
**DNN:** [9.X.X ] 
**Language:** any/all

EasyDNN Solutions, easydnnnews

**Comment by iJungleboy** [comment]
This is fairly easy to do, but we won't be doing it ourselves. Would you do it, if I created a tutorial how to create data sources?

**Comment by Accuraty** [comment]
I would consider it and currently rate it as LIKELY. So, yes please!

**Comment by iJungleboy** [comment]
Ok, just started :). Added some enhancements in 2sxc 9.13 to make it easier, and starting to roll out blog-series about it. Will close this task now ;)

**Comment by Tychodewaard** [comment]
@Accuraty are you willing to post your app when you are finished? Or @iJungleboy are you putting it on https://2sxc.org/en/Apps? 
Would be awesome. :-)

**Comment by iJungleboy** [comment]
Most certainly - it's almost done ;)

**Comment by Accuraty** [comment]
@Tychodewaard, I cannot think of a reason not to.

**Comment by Accuraty** [comment]
Is there a tutorial yet or code sample on how to build this yet? If so, please point me to it. Thanks !!

**Comment by iJungleboy** [comment]
working on it. There are 2-3 components which you may care about

1. https://2sxc.org/en/blog/post/tutorial-custom-datasources-for-eav-2sxc-9-13-part-1
1. an installable dnn module with data sources (still work in progress, will blog about it soon: https://github.com/2sic/2sxc-eav-tutorial-custom-datasource
1. the standalone Form and List data source - but careful, it is special because the original data is already a DataTable, so it uses a trick which is probably not applicable to you: https://github.com/2sic/dnn-datasource-form-and-list i'll also blog about this soon

**Comment by Accuraty** [comment]
Above you said, "working on it" and "blog about this soon" - is there anything new related to this? We've had this come up again for another client so I am leaning towards creating this custom datasource; and just hoping there were more examples or new info on this topic.

**Comment by iJungleboy** [comment]
@Accuraty: Here's an example of a standalone for form-and-list https://github.com/2sic/dnn-datasource-form-and-list

Best you start there, if you run into questions, just post them on StackOverflow.
