### ISSUE TITLE
[Feat request] Change field data type

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1419]
**I'm submitting a ...** 
[x] feature request

**...about**
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
After choosing a data type for a field (string, numeric, date), you stick with it until you delete the field.

**Expected behavior**
In some cases, changing data type should not be a problem, like changing a number or date to string. And even the opposite could be tested (try casting the data in the field) and alerted the user to the consequences.

**What is the motivation / use case for changing the behavior?**
Sometimes plans change or problems get fixed. 

* **2sxc version(s):** 9.11.1

**Comment by iJungleboy** [comment]
This is easily 2 weeks of work, because it would result in many unexpected side effects. A simple example: if a user had a field which was string (and contained a string), and in the history it had these strings. Now the user changes it so everything is a number - everything looks fine. Now he restores an item from history, and you have collisions. Of course we can handle all this, but it would lead to many small problems which take time to test, resolve and handle user complaints. So not really worth the effort. 

There is a very easy workaround: 
1. export existing data
2. delete the field and create new
3. import data

That solves the same need, without risking a lot. So for now, we will certainly stick to this.

**Comment by eXistenZe** [comment]
That could also be done by 2sxc. The ability to copy one field data into another one in the admin view :)

**Comment by iJungleboy** [comment]
It's technically possible - the main difference is that if a button does it, it must work flawlesly and make sure we handle every thinkable scenario - or add features to disable the button in other scenarios. In other words: quite a bit of work. 
If the user does it him/herself, the expectations are different, and the user "knows" what he/she did.
