### ISSUE TITLE
Title in module settings lost

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#1446]
**I'm submitting a ...
[x] bug report => search github for a similar issue before submitting 

[x] DNN parts

If I change the content of an App I created and save, the title of the module (coming from module settings) is reverted to 'File:129'. 

**Expected behavior**
To leave the module settings of the DNN module as it is.

**Minimal reproduction of the problem with instructions**
On my install, just edit the content of the app and press save.

**What is the motivation / use case for changing the behavior?**
It is an install that is new to me.

**Please tell us about your environment:**
Managed.com server, DNN 804, patched

* **2sxc version(s):** 9.13.0
* **Browser:** Chrome XX 
* **DNN:804 
* **Language:** Dutch

**Comment by iJungleboy** [comment]
This is a known side-effect, and you're not the first wanting to turn it off. We won't do anything on short notice, because it's a bit tricky to determine how to turn this off in the right place - so some apps may want this, others not. 

So i'll put it on low priority and we won't address this soon, just fyi. 

For a workaround, use a container not showing a title, like the https://github.com/2sic/dnn-container-invisible and put the title in separately.
