### ISSUE TITLE
.inpage-frame-wrapper class / or something else?

### ISSUE THREAD

**Issue by pircjernej** [2sic/2sxc#1464]
**I'm submitting a:**  
[x] bug report
[x] not sure

**...about**
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
Quick-Dialogs for selecting Template is overlapped with dnn persona bar,
so the first item is not fully visible.
<a href="https://ibb.co/jN3jim" target="_blank">image1</a>

**Expected behavior**
<a href="https://ibb.co/faAmw6" target="_blank">image2</a>
If I add this class
```
.inpage-frame-wrapper {
   padding-left: 80px;
}
```
I get what I want...
I try to find from where **inpage.min.css** came, or where is default **.inpage-frame-wrapper** class defined and if can be a change in sources for 2sxc?

Or what is the possible way to be this fixed in 2sxc that I don't need to add this every time...

* **2sxc version(s):** 9.14.0 
* **Browser:** [all]
* **DNN:** [ 9.1.1 ]

**Comment by iJungleboy** [comment]
Thx for reporting this. we'll look into it, but not high priority

**Comment by Accuraty** [comment]
I am using 2sxc 9.42.00 and I am still needing to have the following in my Skin.css:

// 2sxc UI is not yet respecting the PersonaBar...
.hasDnnPersonaBar .inpage-frame-wrapper {
   padding-left: 80px;
}
 
Anytime the browser viewport is below about 1250px, the annoyance factor is pretty high. Since the 'inpage'
![image](https://user-images.githubusercontent.com/653301/55687936-5f189d00-5938-11e9-9762-75d46588f525.png)

**Comment by Accuraty** [comment]
Still not fixed in 9.43  :/

**Comment by iJungleboy** [comment]
I really missed this. We'll include it in a patch-update probably next week.

**Comment by iJungleboy** [comment]
@raphael-m pls look at it - I think the code from @Accuraty is more appropriate because it probably only applies when the persona bar exists
