### ISSUE TITLE
razor CreateInstance problem

### ISSUE THREAD

**Issue by pircjernej** [2sic/2sxc#1528]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 
[x] not sure

**...about** 
[x] Razor templating
[x] other / unknown

**Current behavior**
If I use code like this:
`var lib = CreateInstance("_library.cshtml");`

Sometimes the _library.cshtml stop working and the only way
to fix problem is to rename _library.cshtml to _library1.cshtml
and 
`var lib = CreateInstance("_library1.cshtml");`

Then view is rendered OK and I can change _library1.cshtml back to _library.cshtml and
`var lib = CreateInstance("_library.cshtml");`

I am trying to find exactly when the problem is shown but don't find an exact reason...
I think that there is some kind of caching but don't know where and how to clear it...
Is there any **CreateInstance caching** and how to clear it?

**Minimal reproduction of the problem with instructions**
Usually, the problem is when making changes to _library.cshtml
and make some mistake and get the real problem... Then I fix it but the code doesn't work until I rename file...

I was checking in web.config at httpRuntime fcnMode but no luck... Also if I restart app the problem persists and the rename part is, for now, the only thing that helps me to get code work again...

**Please tell us about your environment:**
* **2sxc version(s):** 9.1.14  
* **DNN:** [ 9.1.1 ]

**Comment by iJungleboy** [comment]
So I've never seen this before, but yes, the .net framework caches every file it compiles into a DLL somewhere in windows/system32 or something. It then tries to detect changes on the file to recompile - similar to how it watches the web.config for changes to restart the server. 

Since I've never seen your case before in all these years (except for certain special cases while developing on my local system, but there the setup is so complex with visual studio etc, that it just sometimes needs a reboot) - my guess it that your system has trouble with change detection. 

Often a reboot will completely fix everything. But it could also be that the files are on another server (NAS hosting-setups sometimes cause trouble with change detection) or something else. So I don't have a clear answer, but I'll still close this for now as it's basically out of the scope of 2sxc.
