### ISSUE TITLE
Generate DNN Friend URLs on the client side

### ISSUE THREAD

**Issue by Accuraty** [2sic/2sxc#1552]
**I'm submitting a ...
[x] feature request

**...about**   
[x] JS development
[x] APIs like REST
[x] DNN parts

**Current behavior**
Not able to generate on-site, DNN/friendly URLs from client-side. Or... are we?

**Expected behavior**
Given a TabID and one (or a few) params (name/value pairs), construct a full DNN URL in to an existing page in JavaScript.

**What is the motivation / use case for changing the behavior?**
The need to do more and more stuff client-side instead of server side.

* **2sxc version(s):** 9.23+ 
* **Browser: all
* **DNN: 7.4.2 and up
* **Language: any/all

**Anything you would like to add**
After seeing the new $2sxc.cms.run(), this is my suggestion for additional functionality. Please consider exposing DNN's ability to generate URLs. I have had a few cases where I've wanted to do this client side and had easy access to the target TabID. Seems logical that we would want to generate properly formed URLs using DotNetNuke.Common.Globals.NavigateURL(tabid, pname, pvalue)...

Something like:
myHref = 2sxc.cms.DnnUrl(tabID, 'dept', deptID);

Could be used to create a DNN frield URL like:
https://mysiterocks.co/careers/dept/311

**Comment by iJungleboy** [comment]
There are many ways to do this - but we want to be careful to add new official APIs in 2sxc, because...

1. they have to be maintained forever
2. ...even as DNN changes
3. or even if one day it will also run on Orchard, Umbraco, Headless or NopCommerce 

Because of this, I don't think we'll add this in the near future. It's easy to do yourself though, simply by creating your own JS which gets the important IDs from Razor. 

So for now we won't implement this. If you need any tips, just ask questions in this issue.
