### ISSUE TITLE
Database corruption

### ISSUE THREAD

**Issue by wchaspuri** [2sic/2sxc#1600]
**I'm submitting a ...**  
[x] bug report 

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management
[x] other / unknown

**Current behavior**
All 2sxcContent modules display the following error message after adding a field to an existing Content Type.  

`Error: Sitemap is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: An item with the same key has already been added. ---> System.ArgumentException: An item with the same key has already been added. at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at ToSic.Eav.Data.Builder.EntityBuilder.GenerateAttributesOfContentType(IEntity newEntity, IContentType contentType) in C:\Projects\eav-server\ToSic.Eav.Core\Data\Builder\EntityBuilder.cs:line 81 at ToSic.Eav.Persistence.Efc.Efc11Loader.LoadEntities(AppDataPackage app, Int32[] entityIds) at ToSic.Eav.Persistence.Efc.Efc11Loader.<>c__DisplayClass5_0.<Update>b__0() at ToSic.Eav.App.AppDataPackage.Load(Log parentLog, Action loader) in C:\Projects\eav-server\ToSic.Eav.Core\App\AppDataPackage.cs:line 182 at ToSic.Eav.Persistence.Efc.Efc11Loader.Update(AppDataPackage app, AppPackageLoadingSteps startAt, Int32[] entityIds, Log parentLog) at ToSic.Eav.Persistence.Efc.Efc11Loader.AppPackage(Int32 appId, Int32[] entityIds, Log parentLog) at ToSic.Eav.DataSources.Caches.BaseCache.EnsureCache() in C:\Projects\eav-server\ToSic.Eav.DataSources\Caches\BaseCache.cs:line 91 at ToSic.Eav.Apps.App..ctor(Int32 zoneId, Int32 appId, Boolean allowSideEffects, Log parentLog, String logMsg) at ToSic.Eav.Apps.App..ctor(IEnvironment env, ITenant tenant, Int32 zoneId, Int32 appId, Boolean allowSideEffects, Log parentLog) at ToSic.SexyContent.ContentBlocks.ModuleContentBlock..ctor(IInstanceInfo instanceInfo, Log parentLog, ITenant tenant, IEnumerable`1 overrideParams) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\ContentBlocks\ModuleContentBlock.cs:line 64 at ToSic.SexyContent.View.get_SxcInstance() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 24 at ToSic.SexyContent.View.Page_PreRender(Object sender, EventArgs e) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 54 --- End of inner exception stack trace ---`

**Expected behavior**
New field is added to the content type and everything will still work.

**Minimal reproduction of the problem with instructions**
Unable to reproduce since the site is live.  We got back up after restoring the database however, so I suspect the something happened while writing to the database and caused 2sxc to throw the error for all Content.

**Please tell us about your environment:**
Evoq Engage 9.02,  Azure Webapps, Azure DB

* **2sxc version(s):** 9.32  
* **Browser:** all
* **DNN:** 9.02
* **Language:** any/all

**Comment by iJungleboy** [comment]
is this an upgrade of a previous version? because I believe previous versions had an issue that when a field was created with a name that had existed before, you ran into problems. could you check if that was the case? 

The easiest fix would then be to find the old "deleted" item in the DB (it just has a deleted date) and completely remove it (or give it a fake name), then restart dnn and you should be good to go. ok?

**Comment by wchaspuri** [comment]
Hi @iJungleboy 

Yes, I upgraded from 9.14 LTS.  Could you point us to which DB table should we check to delete the item?  And in order to fix this error from happening in the future, do we have to do a clean install of the 9.32 version? ie not upgrade

**Comment by iJungleboy** [comment]
I'm not sure what would be necessary to prevent this from ever happening again, as it's a rare issue. But for now, I wouldn't restart with a clean install, since I cannot guarantee that it will never happen again. I believe the issue is gone today, but I cannot guarantee it. 

The table you want to check is the `ToSIC_EAV_Attributes` which contains the field definitions. They are mapped to content types in the table `ToSIC_EAV_AttributeSets`.
