### ISSUE TITLE
nested ContentBlocks error

### ISSUE THREAD

**Issue by pircjernej** [2sic/2sxc#1605]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
If you use nested ContentBlocks, application picker don't work

**Minimal reproduction of the problem with instructions**
https://stackoverflow.com/questions/51647365/2sxc-nested-contentblocks-error

* **2sxc version(s):** 9.32.1  
* **Browser:** [all]
* **DNN:** [9.2.0] 
* **Language:** [any]

**Comment by iJungleboy** [comment]
ok, we'll look into this. probably an issue which came with toolbar optimizations...

**Comment by tvatavuk** [comment]
Confirming issue in 9.14LTS, 9.32LTS and current development branch.
Simpler cases with Inner Content Blocks works as before.
This is more complex case where:
1. App1 have Content Item with Inner Content Block (parent CB, first level)
2. in parent CB is placed App2 that also have Content Item with Inner Content Block (child CB, second level)
3. server side exception in thrown in case we try to place anything in child PB when App2 is not same type of application as App1

`
{"Message":"An error has occurred.","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":"   at ToSic.SexyContent.ContentBlocks.EntityContentBlock.ParseContentBlockDefinition(IEntity cbDefinition) in C:\\Projects\\2sxc-dnn742\\Website\\DesktopModules\\ToSIC_SexyContent\\ToSic.Sxc\\SexyContent\\ContentBlocks\\EntityContentBlock.cs:line 34\r\n   at ToSic.SexyContent.ContentBlocks.EntityContentBlock._constructor(IContentBlock parent, IEntity cbDefinition) in C:\\Projects\\2sxc-dnn742\\Website\\DesktopModules\\ToSIC_SexyContent\\ToSic.Sxc\\SexyContent\\ContentBlocks\\EntityContentBlock.cs:line 65\r\n   at ToSic.SexyContent.ContentBlocks.EntityContentBlock..ctor(IContentBlock parent, Int32 contentBlockId, Log parentLog) in C:\\Projects\\2sxc-dnn742\\Website\\DesktopModules\\ToSIC_SexyContent\\ToSic.Sxc\\SexyContent\\ContentBlocks\\EntityContentBlock.cs:line 55\r\n   at ToSic.SexyContent.WebApi.Helpers.GetSxcOfApiRequest(HttpRequestMessage request, Boolean allowNoContextFound, Log log) in C:\\Projects\\2sxc-dnn742\\Website\\DesktopModules\\ToSIC_SexyContent\\Sxc WebApi\\Helpers.cs:line 58\r\n   at ToSic.SexyContent.WebApi.SxcApiControllerBase.Initialize(HttpControllerContext controllerContext) in C:\\Projects\\2sxc-dnn742\\Website\\DesktopModules\\ToSIC_SexyContent\\Sxc WebApi\\SxcApiControllerBase.cs:line 28\r\n   at ToSic.SexyContent.WebApi.SxcApiController.Initialize(HttpControllerContext controllerContext) in C:\\Projects\\2sxc-dnn742\\Website\\DesktopModules\\ToSIC_SexyContent\\Sxc WebApi\\SxcApiController.cs:line 35\r\n   at ToSic.SexyContent.WebApi.View.ModuleController.Initialize(HttpControllerContext controllerContext) in C:\\Projects\\2sxc-dnn742\\Website\\DesktopModules\\ToSIC_SexyContent\\Sxc WebApi\\View\\ModuleController.cs:line 34\r\n   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)\r\n   at System.Web.Http.Tracing.Tracers.HttpControllerTracer.<>c__DisplayClass4.<System.Web.Http.Controllers.IHttpController.ExecuteAsync>b__0()\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.TraceBeginEndAsync[TResult](ITraceWriter traceWriter, HttpRequestMessage request, String category, TraceLevel level, String operatorName, String operationName, Action`1 beginTrace, Func`1 execute, Action`2 endTrace, Action`1 errorTrace)\r\n   at System.Web.Http.Tracing.Tracers.HttpControllerTracer.System.Web.Http.Controllers.IHttpController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsyncInternal(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)"}
`

Error is related to this line on server side:

https://github.com/2sic/2sxc/blob/64508cc51862737691a8917a76ef626684dc4db7/ToSic.Sxc/SexyContent/ContentBlocks/EntityContentBlock.cs#L58

**cbDef** is null, because requested **contentBlockId** is not in list. It happens when app with child CB have different **AppID** than app with parent CB.

I have to discuss next steps with @iJungleboy.

**Comment by iJungleboy** [comment]
I believe this was fixed a long time ago, so I'll close.
