### ISSUE TITLE
2sxc upgrade log files clean up

### ISSUE THREAD

**Issue by andyduo** [2sic/2sxc#1625]
**I'm submitting a ...**  

[x] not sure

**...about**   

[x] other / unknown

I have a question about the upgrade logs stored in Upgrade/log directory. I'm noticing in some of my sites there are tens of thousands of log files being generated. Most are just 1kb but it's a pain if you are copying the site files as it takes quite a while to FTP them all.

Here is a typical entry in the log file:
2017-11-25T04:13:22 08.11.00 - IsUgradeComplete checking - static check
2017-11-25T04:13:22 08.11.00 - IsUgradeComplete: True

Is there a way to prevent this behavior? I assume I can also manually delete these files?

Thanks

**Comment by iJungleboy** [comment]
This behavior is necessary, because in certain cases like farm-scenarios multiple threads may start checking if the upgrade is complete, and would then cause parallel running of updates. That would be bad. This is why the files are created and not auto-deleted. They are created every restart of DNN. 

You can delete all the old files, but in general I would recommend to only delete the tiny ones (the ones which simply detected that update isn't necessary. 

For now, we won't implement an auto-clean up as it's simply not on our priorities.
