### ISSUE TITLE
[Feature Request] Image search

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#1696]
**I'm submitting a ...**  
[x] feature request

**...about**   
[x] edit experience / UI

**What is the motivation / use case for changing the behavior?**
- I use RelayThat for creating social media posts. In this tool there is a tab 'images'. If you do a keyword search, it returns 3 columns with free to use photos. 1 column unsplash, 1 column Pexels, 1 column Pixabay. All 3 sites have API's for that.
https://unsplash.com/documentation
https://www.pexels.com/api/
https://pixabay.com/api/docs/

It would be great if a similar feature could be added into 2SXC.
I imagine the most logical place would be in the part that appears after clikcing the 3 dots button in thdialogue of the content app where you can now choose between adam and the DNN image manager. You could add 'ideas' or 'browse free photos' which offers a search box.
The easiest variant would be to have people download an image and upload using ADAM.
Mor ecomplex would be to utilize the API of photo website and have the photo trasferred directly to ADAM.

**Comment by iJungleboy** [comment]
I like the idea, but will need to think about this for a while. Either way we would wait till the Angular 7 UI comes out, as we're trying to minimize new features on the old API, which we would have to duplicate (twice the work).

**Comment by iJungleboy** [comment]
This hasn't had any activity in forever so I'll close this. 
We're aware that it is still very desirable, but it won't have anybody doing this soon, unless someone wishes to sponsor it. 

Implementation is quite complex, depending on the image source, because they often have special legal requirements like linking from their servers, which would create new challenges in terms of automatic resizing which would use different params etc.

So for anybody wishing to sponsor be aware that a first implementation will take ca. 5 days for the first source, and depending on complexity related to what's allowed or not it could be more.
