### ISSUE TITLE
Erratic behaviour with toolbar position

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1754]
**I'm submitting a ...** 
[x] bug report 

**...about** 
[x] Razor templating

**Current behavior**
Some setting do not seem to work, like:
`new { hover = "left", show = "always" })`
In only shows on mouseover, not always.

If I use hover = "right" it displaces the toolbar too much to the right, making it unclickable (since it's out of the theme container).

If I use a table and place the toobar for edit item in the first column, it actually shows on the second column, and I can't click it. Basically most bars shows 3 cm to the right of what they should.

* **2sxc version(s):** 9.3 - 9.4

**Comment by eXistenZe** [comment]
The inline toolbars work fine, it's just the hover ones that have issues.

**Comment by iJungleboy** [comment]
First: which version of 2sxc? 9.3 seems very old. 

Second: I believe something in the theme CSS is causing this - maybe some global floating rules. If you change the theme, does the problem still persist?

**Comment by eXistenZe** [comment]
Sorry. I woke a bit disoriented today.
I've been using 9.4x and updated today to v10.
Tested with Porto theme and xcillion. Happens in both.

**Comment by iJungleboy** [comment]
Not sure if this still is an issue - what's your status? otherwise we'll close.

**Comment by eXistenZe** [comment]
The positioning issue seems fixed.
But the show = "always" definitely does not work for me.

**Comment by iJungleboy** [comment]
ok, thanks for the feedback. Basically the show=always won't be necessary in future, when people use the `Edit.TagToolbar(...)` and don't use the `sc-element` any more.

**Comment by Accuraty** [comment]
I have been steadily converting our work to use Edit.TagToolbar(), but we keep coming up with too many cases where the blue circle(s) behave bizarrely or appear outside the "hover zone" - this means that you hover, they appear, then when you move the mouse towards them, they vanish again because the mouse moved outside the hover zone. Super frustrating and time wasting (to fix). I will try to get you a repeatable example. In a lot of cases I just use Bootstrap cheats to move them "in range" ; e.g. mt-5, mr-n5, etc.
```
    <p @Edit.TagToolbar(Content, settings: new { hover = "left", classes = "mr-n5" })>stuff</p>
```
In one example we were outputting rows that were full-width, edge to edge in the browser and a simple @Edit.TagToolbar(Content) resulted in the blue circles appear off screen to the right. So you scroll right to get to them and then since they are outside the hover zone, they vanish before you get there.

**Comment by iJungleboy** [comment]
@Accuraty First of all great job with the classes - I bet very few people know about that hidden gem. 

Could you create a new issue and post a template or maybe an app for us to be able to reproduce it? thx!
