### ISSUE TITLE
"NOT SAVE" should be "Don't Save"

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#1777]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] edit experience / UI

**Current behavior**
There's a minor spelling mistake in English for the edit dialog. When you try to leave the edit modal without saving, an alert appears telling you "You have unsaved changes. Are you sure you want to close this dialog?" "SAVE | NOT SAVE"

NOT SAVE is a bit confusing because it's both a grammatical mistake but it can make the user question what they're doing.

![Screen Shot 2019-06-17 at 2 06 51 PM](https://user-images.githubusercontent.com/8751936/59637240-2a7c4b00-910a-11e9-90c9-1d3cd7297e2f.png)

**Expected behavior**
The button "NOT SAVE" should probably be something like "DON'T SAVE"

Alternatively, this might be an opportunity to improve the UX. Something like this might be better:

"You have unsaved changes. SAVE AND CLOSE | DISCARD CHANGES"

There's a few ways that it could be done. The wording change might be the simplest but if you change the behaviour of the buttons it might make it more clear.

**Minimal reproduction of the problem with instructions**

1. Edit a item
2. Make some changes
3. Try to close the window without saving
4. The alert will notify you that you are leaving without saving

**What is the motivation / use case for changing the behavior?**

It's a relatively minor grammatical mistake in English but it can be a little confusing for the UX.

* **2sxc version(s):** All
* **Browser:** All
* **DNN:** All
* **Language:** English

---
Version currently agreed to as best:
"You have unsaved changes. To close this dialog, please decide what happens to the changes:"

DISCARD CHANGES | SAVE

**Comment by iJungleboy** [comment]
Thanks for this - it hasn't gotten the love it deserves yet ❤

There are a few goals to this dialog which I would like to ensure:
1. use simple enough English, so that not-native speakers will understand it (that's why I'm not sure about the word "discard" even though it's the best term)
1. It must explain that it's about to close the dialog - because it may appear when you accidentally click on the background (so not actively click the X). 
1. it should remain a toaster which goes away, so it's not interfering in case you never intended to close
1. it should adhere to material style guide. So the primary action should be to the right - in this case save I believe should be the "safest" button and put to the right. 

Based on This my suggestion would be:

1. Message: "You have unsaved changes. To close this dialog, please decide what happen to the changes:"
1. Change order of labels - the confirmation / preferred action "SAVE" should be to the right
1. Use buttons "DISCARD CHANGES" and "SAVE" - since save is so clear in it's meaning, I'm sure even non-natives will know that the discard will probably do the opposite

Your thoughts?

**Comment by eXistenZe** [comment]
Isn't the UI getting translated?

**Comment by ajplopez** [comment]
I like your suggestions so far. I would add that if you can make the Primary action (SAVE) use the primary button style, that would greatly help. So "SAVE" would be the container button on the right, and then "DISCARD CHANGES" would be a plain link on the left. With that, I think most people, even non-native English speakers, would understand that the primary action saves and the other button does cancels. Best yet, if you make the primary button the same style and colour as your edit dialog's SAVE button, then the user would know that they both do the same thing.

A minor spelling edit to your message:

"You have unsaved changes. To close this dialog, please decide what happens to the changes:"

DISCARD CHANGES | **SAVE**

**Comment by iJungleboy** [comment]
@eXistenZe it will be for all the languages we find volunteers for. But other languages will auto-revert to english, so we want to keep it simple

@ajplopez 

1. Thx for for the spelling thing. Note that I'll update your initial post to the currently agreed on version. 
2. The color change is not in line with material design https://material.io/design/components/dialogs.html, so I think we shouldn't do that.

**Comment by eXistenZe** [comment]
Don't they want to use a free extension? Giving back one hour in translation is nothing compared to the hundreds they can save with a proper app. I have at least.

**Comment by iJungleboy** [comment]
@eXistenZe I totally agree - but many don't even realize that they could do this. But that may be a thought to add some kind of message when opening in alternate languages... I'll think about this.
