### ISSUE TITLE
[Feature Request] Formula/Method Generated Title for Records

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#1780]
I'm submitting a 
[x] feature request

about
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
When viewing your data rows, the Title is often worthless due to wrong information or lots of duplication.

**Expected behavior**
It would be VERY useful to allow the Title to be a formula or calculation; preferably allowing the use of full C#/.Net to do so and at least access to all the rows of the columns of the current record.
 
This would be especially useful in records that are on the Many side of the 1:many relationship. A great example is in the Content App, just open the Presentation settings for Basic Content on a busy site. In this case it would be nice to have a Title formula that could instead show the Title of the Parent basic content item.

**What is the motivation / use case for changing the behavior?**
When users need to select a record from a dropdown and see many duplicates with no way of knowing which is the correct one, than will add more unnecessary records because they don't know which one is the correct one by the Title.

Example assumes the current row is available AsDynamic()? 
= (me.Field1.IsNullOrEmpty ? me.Field2 : me.Field1) + " (for "+ me.Parent.EntityTitle + ")";
 
As you can see, seeing that in a dropdown would be extremely helpful to the users!
 
Whereas now they get a drop with a lot of 'no title'...

![image](https://user-images.githubusercontent.com/653301/59855683-09e70780-933b-11e9-921c-bd483c1929f8.png)

**Please tell us about your environment:**
n/a

2sxc version(s): 9.x, 10,x
DNN 8.X.X | 9.X.X 
Language: any/all

I realize this won't be a high priority, but maybe IF you are already planning to provide (enhanced) **Calculated Fields for Content Types** in the near future, this could get added there since the functionality seems both 'similar and nearby.'

**Comment by eXistenZe** [comment]
https://github.com/2sic/2sxc/issues/1639

Just gonna link these here.
I think these should be two very distinct matters.
Naming a field as Title only works in some sort of primary key field. And it's still more useful with the actual field name.

Calculated fields are a major asset, but not exactly related to the field name. You should be able to name it whatever you want, not just Title.

**Comment by iJungleboy** [comment]
Note that as an alternative to the calculated title field, it would also be an option to enhance the picker dialog to show other or all columns.

**Comment by Accuraty** [comment]
For anyone else reading this, the issue here compounded and became significant for us on a large project. We came up with a partial solution for a use case that I thought was worth sharing.
 
We now allow the content managers to put more complex info in the field designated as the Title (that shows in the dropdown picker:

![image](https://user-images.githubusercontent.com/653301/66326554-cd8de600-e8ee-11e9-93d2-347cf177a923.png)

Notice above, we have lots of Party theme types. Each has a "Character Visit" add-on. But after you've entered a few of the various visit add-ons, in the dropdown, there is no way to tell which "Character Visit" to use for Pirate vs. others. So we added the "#" as a special character meaning comment; everything to the right doesn't output. Only the stuff to the left ends up on the page:

![image](https://user-images.githubusercontent.com/653301/66326153-201ad280-e8ee-11e9-9463-057948602112.png)
 
And to do that we simple add a little code to the View, we wrap the output the of Title in a simple StripComment() function:

```
// other stuff

      <div class="card-header">
        <p class="card-title" @Edit.TagToolbar(item, settings: new { hover = "left", classes = "mt-3" })>
          <strong>@StripComment(item.AddonName)</strong> &mdash;
          <span class="card-subtitle mb-2 text-muted">@item.AddonPrice</span>
        </p>
      </div> <!-- end card-header -->

// other stuff

@functions {
  public string StripComment(string inTitle, string sep = "#") {
    if(inTitle.Contains(sep)) {
      return inTitle.Substring(0, inTitle.IndexOf(sep) - 1).Trim();
    } else {
      return inTitle.Trim();
    }
  }
}
```

This isn't great though. Extra coding. Extra time in training. Extra time in the UI explaining the work-around. Confusions after they learn, like it, and then want to know why the same feature isn't available in other places on the site with similar needs.

**Comment by iJungleboy** [comment]
Thanks for this. 

I think we'll try to prioritize this, but in the first version it might still have some glitches.

**Comment by jeremy-farrance** [comment]
Bump? This continues to be a minor pain point for our projects. Maybe some of the recent changes thru v11 have made this easier to get to?

**Comment by iJungleboy** [comment]
This is actually a very complex issue - because we must solve it in a generic way that matches other things in the pipeline. Basically it will require a formula or similar + a formula engine, which we'll also need for conditional-show-hide and other features. 

That's why it's so complex and hasn't been prioritized. 

We have some very awesome stuff coming for 11.01 and 11.02, but I hope to get this in somewhere during the next ca. 3 months.

**Comment by iJungleboy** [comment]
We're just finish the formula engine for 2sxc which will be able to handle these scenarios.

Would you help us test this today or tomorrow? I would give you a pre-release.
