### ISSUE TITLE
Installing 10.02 Pre downgraded RazorBlade from 2.x to 1.x

### ISSUE THREAD

**Issue by Accuraty** [2sic/2sxc#1791]
[x] bug report 

[x] admin experience UI
[x] Razor templating

**Expected behavior**
Installing should not break things or downgrade  DLLs?

**Minimal reproduction of the problem with instructions**
Install with v2.x of /bin/ Connect.Razor.dll and Connect.Razor.Dnn.dll already installed. After install, .cshtml files using v2 features of Blade all... explode in the usual ugly way.

DNN: 9.3.2 
2sxc 10.01 upgrading to 10.02-pre

**Comment by iJungleboy** [comment]
This sucks - sorry. ATM we don't have a solution, because it's how DNN requires us to bundle things. 2sxc 10.05 or so will include razor blade 2.x, but until then, you are forced to do this workaround:

1. Go to extensions and find the razor-blade
1. Set the version to a lower number (just fake it, it's just that the 2sxc installer doesn't complain)
1. upgrade 2sxc
1. re-install latest razor blade

**Comment by Accuraty** [comment]
I greatly appreciate the workaround, thank you!

**Comment by Accuraty** [comment]
Note: this problem still exists in 2sxc 10.04

**Comment by iJungleboy** [comment]
10.05 to be released today or tomorrow has razor blade 2.0 included
