### ISSUE TITLE
TinyMCE doesn't work after 2SXC patch

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#1804]
**I'm submitting a ...** 
[x] bug report 

**...about**  
[x] edit experience / UI

**Current behavior**
TinyMCE editor doesn't appear. Only a small textbox shows.

**Expected behavior**
Editor should appear, not a tiny texbox.

**Minimal reproduction of the problem with instructions**
1. Log in as admin
2. Go to edit a content type
3. Find a String field that is set as wysiwyg-tinymce and click it
4. Small textarea appears instead of tinymce editor

**What is the motivation / use case for changing the behavior?**
Bug report

**Please tell us about your environment:**
DNN 9.3.2 on Azure
Originally had 2SXC 10.02 and upgraded to 2SXC 10.03

* **2sxc version(s):** 10.03 
* **Browser:** [all]
* **DNN:** [9.3.2 ] 
* **Language:** [all]

**Anything you would like to add**
I have a relatively new DNN 9.3.2 installation. I initially installed 2SXC 10.02 and created content types and templates. Today I patched the module with 2SXC 10.03. The installation went fine but now when I click on any "Text" field in the editor UI, the box simply shows a small textarea instead of the tinymce wysiwyg editor. When I inspect the devtools console, I see JS errors about tinymce. See screenshots. I tried doing a repair install but that made no difference. I also tried clearing cache and restarting the application domain but that didn't work either.

![Screen Shot 2019-09-06 at 3 14 05 PM](https://user-images.githubusercontent.com/8751936/64463474-0dc43380-d0b9-11e9-85cc-684609878c3e.png)
![Screen Shot 2019-09-06 at 3 14 11 PM](https://user-images.githubusercontent.com/8751936/64463475-0dc43380-d0b9-11e9-8ef6-66672a6b60cb.png)
![Screen Shot 2019-09-06 at 3 14 27 PM](https://user-images.githubusercontent.com/8751936/64463476-0dc43380-d0b9-11e9-9084-ff495ce882ec.png)

**Comment by ajplopez** [comment]
Testing more, changing it to other WYSIWYG types doesn't work either. It has the same problem.

**Comment by iJungleboy** [comment]
@ajplopez this is unexpected - it's working on our systems.

1. Can you check the network tab to see if the browser is refusing to load certain files - TinyMCE is loaded from a CDN. 
1. What browser are you using?

I'll also release 10.04 in a few minutes because it fixes a view-js-sources problem and some minor issues, but in regards to this nothing should have changed

**Comment by ajplopez** [comment]
MacOS Chrome and Firefox. I’ll have to check the network tabs later when I’m at a computer.

**Comment by iJungleboy** [comment]
@ajplopez I just heard from @PagnoDunadan that it could be a caching issue which we'll try to fix. But if it is that, it should only happen on browsers which had already cached some old code - so maybe try with F12 and "disable cache" and/or clearing the browser cache. Does that fix it?

**Comment by ajplopez** [comment]
My bad - clearing the browser cache seems to have fixed it. I thought I cleared cache enough with the inspector tool open but it looks like it needed a complete clear. Thanks a ton, guys. TinyMCE is looking amazing! Great work as always.

**Comment by iJungleboy** [comment]
thx! 
We'll still try to ensure, that the caching is auto-resolved @PagnoDunadan  :)

**Comment by PagnoDunadan** [comment]
Fixed in next version.

**Comment by Accuraty** [comment]
This just happened to me also upgrading from 10.02-pre to 10.04. The fix was easy and only required (in Chrome):
- make sure you are on the site you just upgraded
- open Developer Tools (F12 or Ctrl-Shift-I)
- switch back to the browser tab
- right-click the Reload button
- select "Empty Cache and Hard Reload" from the drop down

After that, for me, the WYSYWIG editor appeared again and works.
