### ISSUE TITLE
2SCX File Manager Not Syncing with cloud

### ISSUE THREAD

**Issue by AdamMcIntosh** [2sic/2sxc#1851]
**I'm submitting a ...**  
[x] bug report 

**...about**  
[x] other / unknown

**Current behavior**
We have our site assets configured to be in the azure blog storage using Mandeep's Cloud Storage Provider. We have confirmed, using the DNN site assets the files are being read from Azure. However, the 2SXC file manager is using the traditional filesystem to read files instead. 

**Expected behavior**
The 2sxc file manager picks up files in the cloud storage

**Minimal reproduction of the problem with instructions**
Switch site asset folder settings to cloud storage, verify that the files exists in the storage. Navigate to 2sxc file manager and there will be missing files

**What is the motivation / use case for changing the behavior?**
Allows users to upload files using 2SXC. 

**Please tell us about your environment:**

* **2sxc version(s):** 9.43.1
* **Browser:** [all 
* **DNN:** 9.03.02
* **Language:** English 

**Anything you would like to add**

Is there a setting or fix for this?

**Comment by iJungleboy** [comment]
Hi @AdamMcIntosh - thanks for this. Are you talking about 2sxc app-files (in the 2sic folder), about ADAM files (in adam) or portal root files? Or are some working, and others not?

**Comment by AdamMcIntosh** [comment]
Hi @iJungleboy, I am talking about ADAM files and portal root files. Some are working and some are not. There appears to be a disconnect where 2SXC can recognize some of the cloud files but not all of them.

**Comment by iJungleboy** [comment]
Could you try to re-sync the DNN file DB (in the file manager)? Because I don't know for sure how it works now, but if some files show and some don't, it seems that it's very selective. So there must be a pattern we must check - the most common one would be if DNN doesn't itself list all the files in the system.

**Comment by AdamMcIntosh** [comment]
Hi @iJungleboy Syncing the DNN file DB won't work. We aren't seeing any of the cloud files. It's only reading the local/portals directory. ADAM isn't going to the azure blob at all.

**Comment by KurtTrowbridge** [comment]
Hi, @iJungleboy – I'm working with @AdamMcIntosh on this issue. This afternoon, I tried switching away from the ADAM editor and using the older File Manager instead. However, that also lists files from and uploads files to the local Portals directory, rather than Azure blob storage. Is there a way to point either file manager to Azure blob storage instead of the default local folders?

**Comment by iJungleboy** [comment]
There is no specific switch for this. ADAM doesn't actively prefer local files, I presume that either this is an oversight in the current solution, and/or the file listing/access is somehow different and not covered yet by the way ADAM retrieves the files. 

Basically to even give a qualified answer we would need a few hours to reproduce and dig through the API - and to fix it reliably would also take another few hours - my guess is totally ca. 2 days to fix reliably. We (2sic) don't have a real need for this so we would not prioritize this any time soon. If it's important to you, you would either need to contribute the fix or sponsor it (https://2sxc.org/en/contact).

**Comment by KurtTrowbridge** [comment]
@iJungleboy To confirm what you're saying: 2sxc is not able to communicate with Azure blob storage (regardless of whether we're using ADAM or the older File Manager as our file management solution – we've taken ADAM out of the equation at this point), and since it's not a priority to change it, sites running as Azure web apps with scaling are unable to properly use file management within the 2sxc module. Is my understanding correct?

**Comment by iJungleboy** [comment]
@KurtTrowbridge I don't know. We host most of our own sites ourselves, so this use case hasn't been proven or disproved by us. AFAIK 2sxc uses standard DNN functionality but there may be issues that we're using an older API or missed something. AFAIK folder provider are being used by 2sxc-customers, but I cannot say so for certain, because I wouldn't hear of those where it worked the way they want it. 
For example, I believe we've had users use secure files (where people placed data in the secure folders - which are also a folder provide), and AFAIK this works. So we simply don't know.

**Comment by iJungleboy** [comment]
BTW: in 10.10 we've fixed something related to protected folders - which are actually referenced using a LinkClick.aspx. I don't know how folder providers work, but I'm guessing they do the same thing. It may be fixed automatically.

**Comment by iJungleboy** [comment]
Closed because of inactivity
