### ISSUE TITLE
The type or namespace name 'DynamicEntity' could not be found

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1944]
**I'm submitting a ...** 
[x] bug report 

**...about**   
[x] Razor templating
**Current behavior**
The FAQ App is broken in 2sxc 10.24 LTS
**Expected behavior**
No breaking change
**Minimal reproduction of the problem with instructions**
It breaks [here](https://github.com/2sic/app-faq-with-categories-archived/blob/2bf38265740b36a0e237a2ba148aa62a8e989bc0/_Simple%20list%20of%20questions.cshtml#L7)

> 2sxc\FAQ with Categories\_Simple list of questions.cshtml(15): error CS0246: The type or namespace name 'DynamicEntity' could not be found (are you missing a using directive or an assembly reference?) bei System.Web.Compilation.AssemblyBuilder.Compile() bei

* **2sxc version(s):** 10.24 LTS

**Comment by iJungleboy** [comment]
Let me check - the FAQ app was always an issue because the code was so old, let me check.

**Comment by iJungleboy** [comment]
Can reproduce...

**Comment by iJungleboy** [comment]
This is caused by a very old style of code, which shouldn't be used anymore. The FAQ app was made ca. 2013. We'll release a newer one in a few days. 

Until then, I've documented how to fix it https://r.2sxc.org/ErrDynamicEntity and the next bugfix release will automatically include this link in the error message.

**Comment by SCullman** [comment]
@iJungleboy thank you very much.
Documentation is so much better than just a bugfix!
