### ISSUE TITLE
Entitiy disappear when makerd as "Hide"

### ISSUE THREAD

**Issue by RaulZu** [2sic/2sxc#1965]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] Content Types or data management

**Current behavior**
Changing the status of an item to "hide Everything"  in a list of entities, inside Content Types an Data, in administration panel. It makes the item to disappear from the list, instead of being shown with the icon "visibility_off"

Setting to "Draft" work as expected.

In 10.20.2 works ok.

**Expected behavior**
It should remain in the list.

**Minimal reproduction of the problem with instructions**
1- Edit an item/entity mark as "Hide Everything"
2- Look in the list of entities of that type
3- Th item is no longer in the list

**Please tell us about your environment:**

* **2sxc version(s):** 10.23-10.25  
* **Browser:** all
* **DNN:** 9.4.1 ] 
* **Language:** all

**Anything you would like to add**

**Comment by iJungleboy** [comment]
This is probably a mistake in your code, not a 2sxc bug. 

Here's how it works: Before a Razor-template shows data, it will ask for the data to be provided. Where this comes from depends on configuration - it can be a Visual-Query, it can be "items manually added to this module" or it could be code that gets the data. 

The default behaviors in 2sxc contain the rule to provide visible data to all, visible+draft to editors only. 

In your case it seems that the invisible items are filtered out. So I assume you either have code that does this, or a visual-query which does this (probably by accident). 

If you still think it's a bug in 2sxc, pls provide information where the data is coming from for this template, and maybe include code or screenshots. Otherwise I'll just close this for now, assuming it's something in yours olution.

**Comment by RaulZu** [comment]
Sorry, I think i have not explained well, is not in my templates is here:

![2sxcListadoDatos](https://user-images.githubusercontent.com/19955983/72617545-75c53900-3939-11ea-9c11-5306fbbbd039.jpg)

**Comment by iJungleboy** [comment]
thanks! I can reproduce it and it may even be connected to #1959
