### ISSUE TITLE
Public forms gives 401 on ajax reload with new UI

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2039]
**I'm submitting a ...** 
[x] bug report 

**...about** 
[x] edit experience / UI
[x] Razor templating
[x] JS development
[x] Content Types or data management

**Current behavior**
I still get 401 with public forms and the new UI.
The form opens, shows data, but when exiting it gives 401 and does not save.

**Expected behavior**
Public forms works.

**Minimal reproduction of the problem with instructions**
I double checked:
- User is in role
- Features are enabled (public forms, and permissions by role)
- Code works (in admin and old UI)
- Permissions are set for data types

* **2sxc version(s):** 10.28

**Comment by eXistenZe** [comment]
Small update: turn out the changes are saved. But I still get 401.

**Comment by eXistenZe** [comment]
Turns out this is the same as https://github.com/2sic/2sxc/issues/1769

**Comment by iJungleboy** [comment]
thx, not good. will look into it

**Comment by iJungleboy** [comment]
any tip how I can quickly reproduce it - were you using one of the tutorial apps or something?

**Comment by eXistenZe** [comment]
Just use any app with public forms, ajax reload enabled and try to add
something with non admin access.

**Comment by iJungleboy** [comment]
Ok, I checked and public forms are working. 
I assume you wanted the view to AJAX reload, but that's for editors only - the security checks will stop that from happening. Otherwise an attacker could try to ajax-load views that shouldn't be in his control. 

I recommend you don't use ajax-reload - as public forms usually won't show what was input directly anyhow - requiring an editor to "release" the new data from draft. 

If you want to have some kind of public list with ajax loading, you'll need to do this yourself using JavaScript and ajax. 

You'll notice on https://github.com/2sic/app-tutorial-public-forms/blob/master/_List.cshtml#L50 that here we're just showing an alert - you can also do a `location.reload()` or if your output is already JS based, trigger a data-refresh.
