### ISSUE TITLE
Unable to save when editing content that contains entities

### ISSUE THREAD

**Issue by 10PoundGorilla-ChrisBehling** [2sic/2sxc#2042]
**I'm submitting a ...** 

[x] bug report

**...about**   
[x] Content Types or data management

**Current behavior**

When you editing a modules data that has entities in it, you are unable to complete the final save. You will receive the grey box "saving..." at the bottom and it will not complete. Attempting to close out of the dialog will result in a dialog asking if you want to proceed without saving changes. Saving with this dialog will not successfully save the data. No error messages are returned, consoled, or logged.

**Expected behavior**

Clicking save should save the data.

**Minimal reproduction of the problem with instructions**

[Video Link](https://www.dropbox.com/s/224p99gr5qsqzvr/unable-to-save.mov?dl=0)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Tested on multiple DNN installs, using both Evoq and Platform. DNN versions range from 9.2.0 - 9.4.0

* **2sxc version(s):** 10.28.X - Confirmed  
* **2sxc version(s):** 10.26.X - Possibly  
* **Browser:** [all]
* **DNN:** [all] 
* **Language:** [any/all]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Hi Chris
Thanks for the video - makes it much easier/faster to help. 

This is almost certainly the same issue as #2024 - basically the UI has a bug that if there is no string/text field it refuses to save. 

This has already been fixed and will be in the next release, but that will take ca. 2 weeks because we made so many other changes that we have to release all that together. 

As a temp workaround just add a random optional text-field to the item. Maybe you can even hide it - haven't tested that.
