### ISSUE TITLE
RazorComponent causing issues with instant bootstrap

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2043]
**I'm submitting a ...** 
[x] bug report 

**...about**
[x] edit experience / UI
[x] admin experience UI
[x] Razor templating
[x] JS development
[x] Content Types or data management

**Current behavior**
When loading a page with a 2sxc app, I get this:
```
Uncaught TypeError: Cannot read property 'getVar' of undefined
    at dnn.cookieconsent.js?cdv=599:4
    at dispatch (jquery.js?cdv=599:2)
    at v.handle (jquery.js?cdv=599:2)
```

When trying to open any 2sxc menu:
```
Uncaught (in promise) TypeError: $.ServicesFramework is not a function
    at new <anonymous> (ng-dialog-params.ts:59)
    at e.getLink (command-link-generator.ts:83)
    at Function.e.openDialog (cms-engine.ts:154)
    at m (cms-engine.ts:96)
    at cms-engine.ts:108
```

**Minimal reproduction of the problem with instructions**
I just can't pinpoint to a specif change in 2sxc or DNN. Today the app just stopped working.
I manged to trace the error to razor component. When I remove the line 
`@inherits ToSic.Sxc.Dnn.RazorComponent`
and adjust the code to the old AsDynamic, everythig works again.
Also, this only happens with instant bootstrap theme (Porto works fine)
Also, only happens with normal users. Admin has no issue.

Note: am I supposed to have "2sic RazorBlade" and "DnnConnect Razor Blade" installed?

* **2sxc version(s):** 10.28
* **Browser:** [all]
* **DNN:** [9.5]

**Comment by iJungleboy** [comment]
Hi Joao

So first of all, you don't have to install RazorBlade - it's included in 2sxc. 

To 99% you're running into an optimization factor we introduced with RazorComponents. previously 2sxc auto-included both jQuery and the $2sxc JS on every 2sxc module, no matter if it was used or not! This was not good for page speed, but we couldn't just fix it because just like in your case, some templates were using it without explictly asking for jquery. 

When you switch to RazorComponent, this auto-include is not there any more. There is a checklist for migrating: https://r.2sxc.org/RazorComponent

**Comment by eXistenZe** [comment]
Nope. That's not it. Jquery was already loaded.
I tried the code nevertheless and the issue remains.

My question with razorblade modules is that 2sxc installs two of them ("2sic RazorBlade" and "DnnConnect Razor Blade").

**Comment by iJungleboy** [comment]
RazorBlade: Both are actually installed :). DNNConnect was the old version, and for compatibility we're still including it. 

I'm still very convinced that it has to do with automatically included JS files - for example, porto might include them by default, but "Boostrap instant" shouldn't. It may also be jQuery UI that's missing or something. Or that the load-order is different, and the old behavior may have had a side-effect to correct this. 

To really make sure you're not chasing a ghost, please disable CDV for a moment as well - client dependency in DNN - because sometimes you may be getting cached JS files with other versions or something.

**Comment by eXistenZe** [comment]
I've already disabled minification, composite files and increased the CDV version (don't know how to disable it). This happens in multiple PCs.

Here's the list of the network tab from Instant Bootstrap (issue):
![jsissueIB](https://user-images.githubusercontent.com/26518879/79318338-c0d1f680-7efe-11ea-885b-a7b1316ec82b.jpg)
And from Porto (no issue):
![jsissuePorto](https://user-images.githubusercontent.com/26518879/79318430-e101b580-7efe-11ea-93d7-629af6127bad.jpg)

**Comment by iJungleboy** [comment]
I'd love to look at it more but I don't have time to setup a system to try reproduce it - if you could give me access to your system - mail me the access info.

**Comment by eXistenZe** [comment]
Sent with facebook messenger.

**Comment by eXistenZe** [comment]
Ok. This is clearly an intermitent issue. Now I have no errors. I'll report back if it happens again.
