### ISSUE TITLE
Missing translation js (pt.js for example) now popups a 404 on item edit

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2064]
**I'm submitting a ...** 
[x] bug report 

**...about**  
[x] Content Types or data management

**Current behavior**
With v11 I now get a 404 popup every time I try to edit an item (normal toolbar or public forms).

```
Request URL:https://site.pt/desktopmodules/tosic_sexycontent/dist/ng-edit/i18n/pt.js?11.0.0.29965
Request Method:GET
Remote Address:*
Status Code:
404 Not Found
```

* **2sxc version(s):** 11
* **Browser:** [ Firefox ]
* **DNN:** [ 9.5 ] 
* **Language:** [ English | Portuguese ]

**Comment by PagnoDunadan** [comment]
Version 11 clears installation directories. You probably have to place pt.js in i18n folder again to get it working.

Clearing installation directories allowed us to split 2sxc into modules so now 2sxc frontend has 50ish files instead of standard 5 when entire application is bundled together.

You will probably have to copy your own translations after every installation.

**Comment by eXistenZe** [comment]
There is no translation...

**Comment by PagnoDunadan** [comment]
I thought you made a custom translation. The problem is that error is shown to you instead of just gracefully falling back to English

**Comment by eXistenZe** [comment]
In v10 the error was logged, but not shown. Now it's a popup.

**Comment by PagnoDunadan** [comment]
Next update will contain the fix. Thank you for reporting this :)
