### ISSUE TITLE
RFC: App Upgrading (Discussion)

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2071]
I'm submitting a [x] feature request and [x] not sure, about [x] admin [x] other / unknown.
2sxc version(s): 11+, Browser: all/any, DNN: 8.x, 9x, Language: any/all
 
Do you foresee any or all apps being able to upgrade in the future? Similar to DNN modules. For example, someday when this Podcast app goes from v1 to v2.x, will there be a simple way to upgrade? This has been especially painful for us on the Content app,

Some thoughts...

I think one of the main hurdles at this point could be resolved and avoided. I am guessing that in most cases people install an app and then directly customize the Views and sometimes also the data and queries. This alone makes it hard or impossible to upgrade.

What if apps evolved slightly and you added a few features to 2sxc/apps?

1. Add an App setting that flags it as upgrade-able; this would "lock-down" the assets (queries, views, assets, etc) so they don't get modified. Essentially make them read-only.

**Note:** that this idea/pattern seems to be very similar to the recent changes for [Polymorphism](https://docs.2sxc.org/specs/cms/polymorph.html). In addition to the examples of Live, Staging, and Next, why NOT have a locked, as-is app version set that only changes via upgrade?

Now you just need to add one or a few features to make the app easy to customize.

2. Make it simple for us to clone an Asset and give it a new name (in one step). It is frustrating how many steps it actually takes to copy a view and get all the settings right.
Now you can upgrade and replace all the assets; core views and other things (queries, etc) and also upgrade the data accounting for field name changes and data migrating like DNN modules do.

I realize there is a lot more to this, but 1 and 2 above would really start to get things aligned so that it would be become possible in the future.

**Comment by iJungleboy** [comment]
I agree that this is something we should work on. Let me give some background as to the concepts I see and parts of the solution that would probably be needed:

## Apps are Templates

In general, most apps or content-templates will be installed, and it's expected that in most cases changes will be made. This is a crucial idea and limits what can be auto-updated. 

## App-Updates can be Incompatible to the Previous App

When a new App-Version (or Content-App-Version) is released, it can easily be that the new App is so different to the previous one, that it breaks stuff. Some examples:

1. If the main CSS-Framework changes, that would "break" the previous app. This would be something most people wouldn't want and probably wouldn't expect. 
1. Often the logic changes, as 2sxc introduces new features. For example, the Blog 2.0 had a rather temporary solution for Inner-Content, and then 2sxc was improved so that Blog 4.0 uses the nicer, in-wysiwyg inner-content, but the old inner content was removed from the template. Such an upgrade could easily render the upgraded blog useless, even though the clunky features would still work. 
1. Another example of ongoing enhancements is the News app. Previously VisualQuery wasn't able to provide different items to the admin vs. the user, so the template had additional logic to compensate for this. Since 2sxc ca. 10.25 this is now possible in visual query, so both the query and the view were changed - fairly complex changes to slide into an automatic upgrade. 
1. Sometimes we have to rename stuff - again the Blog app used to have a field "Blog" which caused trouble import/exporting and editing in excel. So Blog 4 renamed the field to "Content". This would be very difficult to slide into an upgrade, as the field-name is used in many templates, queries etc. 
1. Often a feature will require both content-type changes, data-changes (possibly app-settings or default-values on existing data) and code. 

## Some Goals of an Improved Update Scenario

1. Users (designers/developers) must still be able to change their Apps as they need
1. Improvements to the App-Template should become easy to merge with an existing (usually modified) app
1. After merging in the enhanced features, the user should be able to quickly benefit from the enhanced features provided in the new template. 

## Some Requirements to this Scenario

1. It's important that the Apps can continue to evolve and be implemented using latest best practices - otherwise the Apps get very complicated with time as the get more features, which 2sxc would solve. So we must allow new apps to become incompatible. 
1. It's my opinion that a fully automated process is neither possible nor necessary, and as it would be extremely hard to implement (even for partial scenarios), I also don't see it as a requirement. 

## Parts of the Solution

Since I don't anticipate a fully automatic upgrade as being possible or reasonable (see list above), I think the best way would be semi-automatic features as well as compare-features to better see what changed and then easily merge the desired changes. I would segment it into partial topics like

1. **Content-Types (Schema)** - which would also include default-values etc.  
It includes: new Types, Type changes and (low priority) removed Types
1. **Data** - When schemas change certain data will also change - a boolean field may be replaced with a drop-down, or a new field may be introduced expecting an always-there value (which would be missing in the existing data).   
It includes: New fields (which may expect default data), changed Defaults (which may already have data, but not the ideal value for the new setup), or (low priority) removed fields
1. **Settings, Configuration, Resources** - this is similar to data changes
1. **Views/Templates** - both the view configuration and code
1. **APIs** - mainly the code
1. **Code** - other code, like shared code
1. **App Assets** - mainly images / js / css etc. in the app folder
1. **ADAM and Portal Assets** - files in the portal system which may be included in the new app
1. **Extensions** - something secret 🤫 we're working on ATM

I think that covers most bases. What does everybody else think? Priorities?

**Comment by iJungleboy** [comment]
Note that views and data are now much easier to import/export since 2sxc 11.10.

This discussion will now be closed because of inactivity.

**Comment by skarpik** [comment]
@iJungleboy - do you have any thoughts on you might release an LTS for version 13.x. I'm at the prototyping stage in a project that involves your app / content templates and some apps that I have written. Ideally I'd like to start with a 2sxc release that that is the most advanced, stable version. If would not be an issue if not for the fact that from my perspective, each 2sxc release represents a significant step forward and I want to include the latest and greatest. I can't think of a release where I've been blasé about fixes or new features in it. So would I love to see some way to update 2sxc content and apps in deployed website but at the same time, I recognize the complexity of providing such a facility.
