### ISSUE TITLE
Conditional Display of Input Controls for Add/Edit

### ISSUE THREAD

**Issue by 10PoundGorilla-ChrisBehling** [2sic/2sxc#2081]
**I'm submitting a ...** 
[x] feature request

**...about**
[x] edit experience / UI

**Current behavior**
We’d love to see the ability to conditionally show/hide input controls based on the values in other input controls.

# Example 1

Card option controls:
* Title
* Title Size
* Subtitle
* Subtitle Size
* Content
* Links

In almost every instance, in our template files we wrap every input control in a check to ensure it exists before displaying the field. This keeps empty html elements out of the site without always requiring every field on add/edit. This is often very helpful because our designs will often include instances where a Subtitle is used, and other times when a subtitle is not used.

With conditional control display, we’d be able to set Subtitle Size to only display if Subtitle has any content in it. 

This helps simplify the add/edit UX for the end user and helps clear up clutter. 

# Example 2

Card option controls:
* Title
* Subtitle
* Background Color
* Desktop Image
* Mobile Image

In some instances we allow for multiple controls that have similar impact to the component look and feel. Using razor we currently have to create a defined priority for which element would display over the other.

In the above example, the lowest priority value is Background Color. If the user selects a background color, but then fills out a Desktop Image and Mobile Image, we ignore the Background Color value and output the Desktop and Mobile Image values.

We’d instead like to see the ability to add a conditional control to help clarify this editing process:

* Title
* Subtitle
* Background Style
** Background Color
*** Primary Color
*** Secondary Color
** Image
*** Desktop Image
*** Mobile Image  

Based on the Background Style selected we would then display either the Background Color control or set of Image controls.

Potential conditional parameters
* [x control] == null
* [x control] != null
* [x control] = true/false
* [x control] == “exact value match”
* [x control == “% partial value match %”

**What is the motivation / use case for changing the behavior?**
Without the ability to have conditional display of input controls you are left with 2 options:
Without the ability to have conditional display of input controls you are left with 2 options:
* Create nearly identical content types, which makes the admin process more difficult for end-users with many content types to choose from.
* Display too many input controls in the editing UI which becomes confusing for the end-user to easily understand the editing process and what fields they should be filling out.

**Please tell us about your environment:**

* **2sxc version(s):** 11.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

Edit: Updating list markdown formatting.

**Comment by iJungleboy** [comment]
Just for some context: this has been on our mind for a long time - and we did have to wait for the new UI to address this option. 

There are additional parts involved here that I would like to mention:

1. There is also a need for calculated fields - for example #1757 and #1780 
1. No matter what we do, it must be fairly future proof - so the syntax must be very well thought through
1. the calculation system must be fairly generic, to ensure that most cases are covered, even cases that we didn't think of as of now
1. We should not invent a wheel here, but base our formula-engine on something solid/proven and open-source
1. Optionally there may be a need for an intermediate step - because in some cases the same calculation will be needed for many fields, and repeating the formulas could be fairly cumbersome

We have created various online tools which are based on Excel, and generate a JSON from that spreadsheet, to then run live calculations based on the real, underlying excel formulas. This has been a great success. The underlying engine is https://github.com/handsontable/formula.js/ and we're currently considering implementing that - giving the formulas an Excel-Standardized formula language. 

What do you all think? Leave your comments.

**Comment by iJungleboy** [comment]
This is done & ready in 12.01 which will be released on Towel Day. We would appreciate testing and feedback.
