### ISSUE TITLE
Allow admins to make illegal changes to items

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2100]
**I'm submitting a ...** 
[x] feature request

**...about** 
[x] Content Types or data management

**Current behavior**
When a fields is marked as mandatory, no one can submit the form without a value in that field.

**Expected behavior**
Admins should be able to make any change, bypassing these checks.

**Comment by iJungleboy** [comment]
This seems like a very arbitrary wish. 

If admins could just bypass checks, that would usually result in many new mistakes being made, because often the admin will accidentally bypass the checks, and not on purpose. 

if this is just a once-in-a-while thing, please just make the field unrequired, make the change, then set to required again. 

I'll just close this for now. If you have a really good story why this should be a standard feature, please post and we'll reconsider.
