### ISSUE TITLE
Remove HTML markup from preview text in editing UI

### ISSUE THREAD

**Issue by 10PoundGorilla-ChrisBehling** [2sic/2sxc#2104]
**I'm submitting a ...** 

[x] feature request

**...about**   
[x] edit experience / UI

**Current behavior**
Nested 2sxc entities are set to display the “starred” control in the editing UI. In an instance where you have an entity with a WYSIWYG editor it will output the HTML markup. This also happens if you have a text control with inline html markup.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

[screen-shot of entity displayed as a label with HTML markup.](https://www.dropbox.com/s/3giwo2p8uh66kt6/entity-list.png?dl=0)

[screen-shot of entity content editor.](https://www.dropbox.com/s/yaaku0mlz6994d3/entity-editor.png?dl=0)

If it were possible to parse through and remove any html markup and instead output the display text, I feel this would be more intuitive for the end user. 

```
Before: <h1>Lorem ipsum</h1><p>Hello world</p>
After: Lorem ipsum hello world.
```

There definitely could be some considerations with how the parse would string together elements, but it would still likely be more intuitive for the end user. Perhaps the display text could be limited for the first element with returned data.

Example 1:
```
Before: <h1>Lorem ipsum</h1><p>Hello world</p>
After: Lorem ipsum.
```

Example 2:
```
Before: <p><img src=”[your-image.jpg]”>Let’s remove the image as well?</p>
After: Let’s remove the image as well?
```

**What is the motivation / use case for changing the behavior?**
HTML markup strung together inline is not intuitive for general content editors or even a code editor.

**Comment by iJungleboy** [comment]
The * is the **Title** field and will be used for many things incl. `@Content.EntityTitle`. As such, various field types are not well suited, like the custom-empty or entity-dropdown. I would lay that string-wysiwyg is also not ideal for this.

We are working on a different feature to enable calculated fields, in which case you could then create a calculated read-only-field producing a simpler text and then use that as the Title. Because this will resolve your issue, we won't also implement some kind of automatic-modifications on title fields, as that would have way too many unexpected side effects.
