### ISSUE TITLE
Existing text not in edit field

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#2108]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 
[x] not sure

[x] edit experience / UI

I have a very simple token app. When I try to edit existing text, the existing text won't appear in the edit box

**Expected behavior**
To have the existing text present

**Minimal reproduction of the problem with instructions**
I have recorded the issue (< 1minute) https://www.youtube.com/watch?v=y_FYudj8AzU

* **2sxc version(s):** 11.0.0 
tested in Chrome only as 2SXC won't work in Edge

* **DNN:** 9.6.1
I don't have the same issue on other sites, same DNN, same server, also token apps.

**Comment by iJungleboy** [comment]
Hi @Tychodewaard 
I'm not sure what you're describing. 
Are Tokens the problem, is it the edit-dialog? Could you also test on 11.02?

**Comment by iJungleboy** [comment]
OK, just watched the video - thanks for that.

So it's certainly not related to tokens - the Edit-UI doesn't know anything about the templates at all. 

Basically it has to do with the transition from wysiwyg preview to dialog. I'm not sure what the reason is, but we're changing a few things there in 11.03, so it's probably fixed already.
