### ISSUE TITLE
Confused about file location while editing templates 

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#2124]
**I'm submitting a ...** 
[x] feature request

**...about**   

[x] admin experience UI

**Current behavior**
Templates can be stored per portal or by system/host.
However, the script editor has no indicator of the location of the scripts. 

**Expected behavior**
Please add a button host templates.
The existing template button should only show portal templates for that app.

**screenshot**
![image](https://user-images.githubusercontent.com/5693190/86784460-d53b1080-c061-11ea-9052-928aaa0a5510.png)

**Remarks**
I run a few portals which share all the same custom app. I usually have one script for all in portal/_default, and a few customizations inside the portal folder.

**Comment by SCullman** [comment]
Today I edited a template, and again I had to wonder about the (empty) list of templates
![image](https://user-images.githubusercontent.com/5693190/92443429-ca137680-f1b1-11ea-9576-6038d8c2cff5.png)

**Comment by iJungleboy** [comment]
I just ensure that it works again as expected. 

Since shared templates are a fairly advanced feature which normal users will have trouble with, the normal editor won't show it. But if you have a template which is in a shared location, the editor will open it there now from the admin-ui and show all other files from the shared location
