### ISSUE TITLE
Add existing module > make a copy does not work

### ISSUE THREAD

**Issue by kieran23101** [2sic/2sxc#2175]
**I'm submitting a ...** 
[x] bug report
[x] feature request
[x] not sure

**...about**   
[x] DNN parts

**Current behavior**

I am unsure if this is by design by I am currently trying to have my website able to be edited by others and they like to utilize that dnn feature, however 2sxc doesn't seem to work when wanting to make a copy, they are always shared modules.
**Expected behavior**

If this is a bug, I'd expect the "Make a copy" function to actually create a copy of the module that you are trying to duplicate.

**Minimal reproduction of the problem with instructions**
Using the dnn version listed below, simply add a 2sxc app on a page and then navigate to another page and use the "Add existing module" dnn feature. (Ensure that "make a copy" is selected).

After getting the module on your new page, try and edit a data entry using the regular blue edit pencil. The edits made to the duplicated version will also reflect onto the original module

**Please tell us about your environment:**

* **2sxc version(s):** 11.06.01  
* **Browser:** [all]
* **DNN:** 9.6.2
* **Language:** [English]

**Comment by iJungleboy** [comment]
This is by design, but does cause unexpected results with DNNs use of Modules. Basically our module is not notified of what DNN does, but to really do it right, we would have to ask some questions. Here examples of what the user may expect:

1. Copy a text/image block - a full copy is probably expected
1. Copy a module which shows a picture from a gallery - well...
    1. a copy might be expected, but maybe not
    1. if a copy is expected - are the tags supposed to be copied too, or not?
1. Copy a module which shows the picture which has tags -

**Comment by iJungleboy** [comment]
closed to quickly by accident, had to finish my comments above.
