### ISSUE TITLE
Git Workflow within a team

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#2223]
**I'm submitting a ...** 

[ ] bug report => search github for a similar issue before submitting 
[ ] feature request
[x] not sure

**...about**   
[x] ** templating
[x] ** development

**Current behavior**

2sxc allows GitHub versioning, as described in this blog:
https://2sxc.org/en/blog/post/github-versioning-an-app-with-the-database-for-dnn-dotnetnuke  
It works as expected if there is only a single developer.

I would expect for a term based flow that a team can work together and that it is simple to merge the changes of the schema in the XML manifest and to import this manifest again via _Import Content and Templates into this App_ 
However, this results in an error box: "Had an error talking to the server (status 500).

Workaround:

- Copy App folder
- Delete App within 2sxc
- Create App again
- Import manifest

**Expected behavior**
I can simply import the manifest. 2sxc just wipes out the current state of the app and starts with the new manifest.

**What is the motivation/use case for changing the behavior?**
Simplified teamwork

**Comment by iJungleboy** [comment]
I understand the idea and think it's great. 

As of now, the xml only helps to track changes to the app. It is identical to the importable xml, that process currently only works for new (empty) apps. I guess for this to work it would need two distinct things

1. A complete "flush-the-app" functionality which empties the app completely - incl. app definition (name, etc.)
2. import the xml (in the same go - because otherwise the app-definition entity is auto-generated again)

ATM we're focused on a bunch of UI enhancements + getting 2sxc to also run on Oqtane, so this certainly won't be a priority. But contributions would be welcomed ;)

**Comment by iJungleboy** [comment]
Started work on this.

**Comment by iJungleboy** [comment]
It's implemented and tested - I believe it works. 

The next release 11.8 will have a lot of internal changes, because we modified a lot of code to ensure it will work in Oqtane. So 11.8 will be more of a beta-release, so even once it's out, wait a bit :).

**Comment by iJungleboy** [comment]
First implementation will be released in a few minutes in 11.10 - pls test :)

**Comment by iJungleboy** [comment]
This is what it looks like

![image](https://user-images.githubusercontent.com/5321186/99383320-f8a67f80-28cd-11eb-9e99-63bf3646711b.png)
