### ISSUE TITLE
Can't access app-settings/app-resources via the content admin panel.

### ISSUE THREAD

**Issue by MS-BSI** [2sic/2sxc#2260]
**I'm submitting a ...** 
[x] bug report

**...about**  
[x] admin experience UI

**Current behavior**
A click on Content Admin > App > App Settings > Edit App Settings shows that error message in the console : "Found too many settings for the type App-Settings". Same for the App Resources. So it's impossible to choose languages (or others settings).

**Expected behavior**
Settings/Ressources displayed.

* **2sxc version(s):** 11.10.01
* **Browser:** [all]
* **DNN:** [8.4.0 ] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment]
This is a rare bug and usually caused by something in versions long ago. Basically it results in a entity which should only exist once, to exist 2x. 

To fix it
1. go to the `Data` Tab 
1. In the bottom left corner you can switch scopes - basically showing hidden content-types which the user should normally not work on. I think the scope is called "App System" or something 
1. there you'll find App-Settings, App-Resources etc. - all of which should only exist once, but you'll have one that exists 2x. 
1. Find out which one to keep, then delete the other one and it should work
