### ISSUE TITLE
C# Razor template "breaks" / loses paths after editing content when using module snippets in the template

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2315]
**I'm submitting a ...** 

[x] bug report

**...about**   
[x] edit experience / UI
[x] Razor templating

**Current behavior**
When you have a content module and a c# razor template and you use the code like @Dnn.Tab.SkinPath, it works great until you edit an item. Then it seems to disappear and you have to refresh the page before you can edit again. For example, the following code works as expected when the page loads:

`<img src="@Dnn.Tab.SkinPath/images/chatmodaldesign.svg" alt="red and yellow circle design">`

But then when I edit the content of the module and save, the template loses the path to the image. I have to refresh the page before I see this load again. It seems to happen not only with SkinPath but with JS that runs on the page as well.

**Expected behavior**
If a template renders a path or JS via the snippets, it shouldn't break after editing content.

**Minimal reproduction of the problem with instructions**

1. Create a content type and C# template
2. Use @Dnn.Tab.SkinPath to link to an image in the skin via the template
3. Edit a content item and save
4. Once the save happens, the URL to the image will break and the image will disappear

**What is the motivation / use case for changing the behavior?**
It can confuse the editor and causes everyone to refresh the page after making changes. I like using those snippets because I know it's more reliable than hard-coding the path to a skin. 

**Please tell us about your environment:**
Shared hosting

* **2sxc version(s):** all
* **Browser:** [all]
* **DNN:** [9.7.0 ] 
* **Language:** [any/all ]

**Anything you would like to add**
I've seen this issue since I first started working in 2sxc.

**Comment by iJungleboy** [comment]
I assume this is the AJAX reloading, which doesn't have the full context of the module. We'll look into this, thanks for reporting it.

**Comment by iJungleboy** [comment]
I can reproduce the issue. Basically it seems to be a DNN bug - see https://dnntracker.atlassian.net/browse/DNN-3434

Basically the object is not reliably populated by DNN, and all the workarounds I've checked don't help. 

From my understanding DNN initializes certain objects like the SkinSrc in fairly special ways, so that sometimes it's there, sometimes not. When it's not there, I should be able to get it using the `TabController.GetTab`, but this too doesn't give me a fully populated object - some properties are just missing. 

I tried all kinds of ways to retrieve it - here some code - all of it still returned an empty `SkinSrc`

```
        public TabInfo Tab
        {
            get
            {
                //return Portal?.ActiveTab;
                // Experimental, trying to fix https://github.com/2sic/2sxc/issues/2315
                // wasn't successful - the SkinPath was always empty with all variations of the code...
                if (_tab != null) return _tab;
                _tab = Portal?.ActiveTab;
                if (Portal == null || _tab == null) return null;
                
                // check if tab info is fully populated
                if (string.IsNullOrEmpty(_tab.SkinPath))
                {
                    var tabController = new TabController();
                    _tab = tabController.GetTab(_tab.TabID, Portal.PortalId);
                }
                return _tab;
            }
        }

```

As of now I must simply assume we can't fix it in 2sxc - unless someone can give me a snippet how to get this data fully populated. Because of this I'll close the task as of now. 

As a workaround you can disable AJAX on your app (if it's an app, doesn't work in Content templates) to work around this.
