### ISSUE TITLE
Module gets renamed when entering data

### ISSUE THREAD

**Issue by BobGroenewoud** [2sic/2sxc#2317]
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] DNN parts

**Current behavior**

When I add the content module to a page I give it a name like "Links". Then I enter the data.
<Links>
- Facebook
- Instagram
- Etc.
The name of the module in the DNN page then automatically changes to the first data entry for example "Facebook".
This is visible after reloading the page (see movie below)

**Expected behavior**

The name should not change automatically.

**Minimal reproduction of the problem with instructions**

https://user-images.githubusercontent.com/10153127/102968249-d2d75080-44f3-11eb-9380-d5bb70e675af.mp4

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 11.11.3  
* **Browser:** all
* **DNN:**  9.6.1 and  9.2.2
* **Language:** any

**Anything you would like to add**
My compliments for your great work!

**Comment by ajplopez** [comment]
This is typical and expected and I think it makes a lot of sense. Seeing how you have "Enable List" enabled, you should define a Header for your list in the template settings (you would have a Title field inside your header). Then, when you edit the title of the header, the module title will become the title of the list. The reason why this makes sense is because presumably your content editors won't be editing the module settings title, they will edit the header title of the list module and it will automatically update the module settings title. The idea is that editors use the 2sxc controls and not the DNN controls and it keeps things sensible.

**Comment by BobGroenewoud** [comment]
@ajplopez , thank you for your answer.  
I see that I can set a "Header Item ContentType". I create a data definition with only a "Title", but I don't understand how I can use that in a razor template.
Do you know where I can find a working example of a razor template with a separate data definition for the "Header Item"?

**Comment by ajplopez** [comment]
@BobGroenewoud Yeah, it's as simple as:

@Header.Title

**Comment by BobGroenewoud** [comment]
@ajplopez , Thank you. 
I added @Edit.TagToolbar(Header) as well, so the user now can change the heading. 

<h1 @Edit.TagToolbar(Header)>@Header.title</h1>
