### ISSUE TITLE
Wish: Edit toolbar to edit specific fields

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2322]
**I'm submitting a ...** 
[x] wish

**...about**   
[x] edit experience / UI

**Current behavior**
I wish there was a way to configure the edit tag toolbar so that I can target a specific field only. For example, I have a content module that lists out products. Each product has a modal that appears when a person clicks on a product. Right now, my content editors can "edit" the whole product and it shows all the fields in that content type. But most of the time when they're editing, they open the modal of the product and see the content, then want to edit a specific bit of content inside the content type. It would be useful if I could configure edit toolbars for each field in the design.

In a way, they already have this if there are sub-entities within the product but that edit ability only applies to these sub-entities.

**Expected behavior**
Make an edit tag toolbar that can be figured to target specific fields in a content type.

**Minimal reproduction of the problem with instructions**
User goes to edit some content. Instead of seeing 1 blue edit pencil for the entire content type, they see edit icons for each bit of text they hover over. For example, if there's a heading, a block of text, and an image, when they hover over each they see an edit pencil. Then when the click on the edit pencil, it pops a modal to edit only that 1 field.

**What is the motivation / use case for changing the behavior?**
Improve the edit experience for content editors by allowing them to edit specific fields that they click on.

**Please tell us about your environment:**

* **2sxc version(s):** 11.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
This is a good suggestion, but I'm not sure if this is how it should be implemented. 

Especially if it's just a specific field, then maybe some kind of inline editing would be more appropriate (but more work to develop). We'll think about it - won't happen quickly, but we'll ponder it.

**Comment by eXistenZe** [comment]
You could disable all other fields for that dialog only.
There is also the custom fields through public forms. Create a new button, a simple modal where you load the field to, and a save button linked to the cms run or even a custom API.

**Comment by jeremy-farrance** [comment]
This is related in many ways to issue #1638.
https://github.com/2sic/2sxc/issues/1638

**Comment by iJungleboy** [comment]
V12.01 to be released on Towel Day would allow you to do it - not so easy yet, but possible. 

Basically 12.01 has 3 important new features which will help

1. You can create fields which are treated as variables only - so they will not save the data - check the [docs for ephemeral fields](https://docs.2sxc.org/basics/data/fields/ephemeral.html). You would probably hide this field or make it disabled while working on the solution. 
2. This you could then prefill using normal prefill features - so each button would give it another value. Since it won't be saved, it will always be empty when the form loads again, accepting the new prefill
3. Using this variable you can then create formulas to control the visibility of other fields. In your case I guess field-groups would be more appropriate. The docs are not quite done, but you'll find them on https://r.2sxc.org/formulas
