### ISSUE TITLE
Is there a way to present a real backend for Editors, where they can manage all the content 

### ISSUE THREAD

**Issue by rockgobo** [2sic/2sxc#2344]
Is there a way to present a real backend for Editors, where they can manage all the content? Like a way to get the Content Admin on a Page a restricted area? Or even cooler directly in the Persona Bar.

**I'm submitting a ...** 
[x] feature request

**...about**   
[x] edit experience / UI

**Current behavior**
I guess the editor has to go to a page where a 2sxc Content module is placed then switch to the admin mode. There a Popup opens with the Tab "Data". Finally he sees all the Content of Website and can add, edit or remove stuff (like Persons, Adresses, ...)

**Expected behavior**
It would be so much more fun to get rid of the in Page additing for the basic data of the webside, that is than presented on different pages in different views anyways, thanks to awesome 2sxc System!

**What is the motivation / use case for changing the behavior?**
I would like to have a central place for every content on the website, which is easily accesible for an editor of the content. Strict cut between content and the view (and the pages) where it is presented

* **2sxc version(s):** 11.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [9.6 ] 
* **Language:** [English | German ]

**Anything you would like to add**
I love 2sxc

**Comment by iJungleboy** [comment]
So there is now "All data in 2sxc" tree-admin or something, also not in the Persona Bar. 

As of now, we're also not planning on implementing this, because there are other ways to achieve the main purpose, which is usually easier for normal editors. 

The way we usually do this is to add buttons to the toolbar which directly open the table. You can find examples of this in the Mobius App, where the toolbar has a button opening the submitted forms for this module (it even passes a filter-param to the data, so only the items of this form are shown). 

I suggest you pursue that way :)
