### ISSUE TITLE
[Feature request]Tokens as default value for a string field

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2370]
**I'm submitting a ...**  
[x] feature request

**...about**   
[x] Content Types or data management

**Expected behavior** 

I'll keep this as simple as possible.
I'm building another project in 2sxc (maybe the 100th one) where I would greatly need some info to be prefilled in a form (default value), based on simple tokens such as user info, date, whatever. Yes, the editor can fill this, but it's extra work and I need most of these fields locked (disabled).

As a goodie, you could also add the option to replace the previous value when editing.

**Comment by iJungleboy** [comment]
This will not happen soon, as the data would need to be provided from the server which is quite difficult to do in the Edit UI.

BUT: It's easy to do yourself, just by ensuring it's in the prefilllin the edit toolbar. 

Since 2sxc won't address this anytime soon, I'll close thie issue.

**Comment by iJungleboy** [comment]
If you have further questions, feel free to add to this issue, I'll still get notified if something gets added.

**Comment by eXistenZe** [comment]
When you set a field to entity, and allow new items to be added, the new
form will be opened through the ui, and not the toolbars.

**Comment by iJungleboy** [comment]
So your concern is sub-items, correct?

Like 

1. A primary Item like `BlogPost`
2. has `Tags`

You are correct, in the Edit-UI there is no way to prefill these, and even if there were, the Edit-UI wouldn't be able to find the values since again they are on the server. 

There is a way to add items from the page. So that you could edit the `Tags` list on the blog, and also do adding from the page directly. Would this be a solution? We added this functionality fairly recently, I believe ca. v11.7 or so. 

The solution basically makes list-editing work the same as content-editing, that you have + buttons on a `Tag` in a `BlogPost` which would add it the tags list. You also get up/down etc. features in the page. 

If you're interested I'll give you some guidance.

**Comment by eXistenZe** [comment]
Partially yes. But toolbars will never be a solution, since I only use the
admin panel for superuser access, and public forms for my researchers (that
are not editors).

But the use case is what you described.

**Comment by iJungleboy** [comment]
The main difference in UI would be this:

The editor would have the normal edit button for the primary data `BlogPost` and would not edit the `Tags` in the form at all (maybe the tags would be invisible, or wouldn't have an add-button)

Then after saving they would see the `BlogPost` and somewhere in there would see the list of `Tags`. They would then be able to add more tags from there. 

So it's a slightly different edit-flow, but not massively different.
