### ISSUE TITLE
New Versions of 2SXC and Plant An App cause sites to crash when installed together

### ISSUE THREAD

**Issue by rezagarrow** [2sic/2sxc#2437]
**I'm submitting a ...**   
[x] bug report 
[x] not sure

**...about**   
[x] DNN parts
[x] other / unknown

**Current behavior**   
Hello,  my name is Reza Garrow and I'm the Head of Product for Plant an App (a.k.a DNNSharp).  Let me start by saying I'm a big fan of 2SXC.  I've seen some really amazing things our mutual users have built with our 2 products combined and have seen we have a sizable population that overlaps.  Therefore we always try to make sure our products play well when installed together.  

With the newer version(s) of 2SXC, we've had several users reporting issues when installing  2SXC  alongside Plant an App AppBuilder (our product) their DNN instance will crash with an error message: 
Exception Details: System.Exception: The DI container initialization was triggered before DNN was able to run its IDnnStartup logic.  

Our devs investigated and found that some of the dlls that both us and 2sxc are using are not copied because 2SXC is registering them in DNN with the incorrect version (image1). The version of 2SXC is used instead of the version of the dependency (dll version). As an example with Microsoft.EntityFrameworkCore.dll, 2SXC is using 1.1.1 (see (image4) attached), while PlantAnApp is using 2.2.1 (image5), but DNN thinks that ours is older because it thinks that 2SCX's is 11.22.1 instead of 1.1.1, and it skips copying it.

2sxc dependencies are getting inserted with the wrong version because it is not specifying the dependency version in the DNN manifest (image2).
You can see in (image3) that we are using the proper versions.

**Expected behavior**   

Would you consider updating the assembly registrations in dbo.Assemblies?  

**Instructions to Reproduce the Problem**
If this is taken up, I'm happy to do assist with testing/validation on our end or make a version of the product available.

**Why change the behavior?**  
We'd be happy to do something on our end but so far as we can see, short of a very ugly hack - which will increase our maintenance cost, there is nothing that we can do, and people will have to manually copy the missing DLLs out to the file system and manually update entries in their web.config

**Your environment**  
Plant an App App Builder latest versions when installing after 2SXC

* **2sxc version(s):** 11.11.22  
* **Browser:** [all]
* **DNN:** [ 9.9.0 ]  and probably others as well.
* **Language:** [any/all]

**Anything you would like to add**
Happy to hop on a call to discuss/demo/troubleshoot together anytime if that would help
![image1](https://user-images.githubusercontent.com/18374037/120564437-8ceeb480-c3d0-11eb-97e2-8ad03f2bcdc4.png)
![image5](https://user-images.githubusercontent.com/18374037/120564439-8d874b00-c3d0-11eb-9a3c-deadbdf4c664.png)
![image4](https://user-images.githubusercontent.com/18374037/120564441-8d874b00-c3d0-11eb-95bd-af98abb15a40.png)
![image3](https://user-images.githubusercontent.com/18374037/120564442-8d874b00-c3d0-11eb-933f-13fe5341683e.png)
![image2](https://user-images.githubusercontent.com/18374037/120564443-8e1fe180-c3d0-11eb-9096-b56b229e64bd.png)

**Comment by iJungleboy** [comment]
@rezagarrow Thanks for the well documented issue. We would love to help, but I'm not sure how easy this will be, and I would be grateful if you could assist in researching as we try to fix this together. 

My understanding is that we'll have a diverse set of scenarios which may or may not cause different problems. 

1. Existing installations of DNN 7/8 which already have the entry with the wrong versions - these would have to be corrected in the DB which will probably require change scripts, as I believe the installer has no such mechanisms
2. DNN 9 versions which could have up to 3 different versions of EntityFramework
     1. The DNN included ones which are ca. V2 and are in the `bin` folder
     2. The 2sxc included ones which are .net standard 1.6 so EF Core 1.1 and lie in the `bin\2sxc` folder
     3. The version included in PlantAnApp which seem to be in the `bin\PlantAnApp_Core` folder

So my understanding is that we'll run into multiple problems to solve

1. Both 2sxc and PlantAnApp should be able to install / upgrade if the other had been installed. Based on your description above this will not work, because even though the DLLs are in different folders and must *both* be installed, your description indicates that DNN will skip either one if it believes that there is already one with a higher version, no matter where it is. If this were the case, we would have to get DNN to treat these version checks differently.  
  👉 Can you confirm that this is a problem?
2. It also appears that DNN isn't keeping track of their pre-installed EF - otherwise that too would cause problems. In future that may actually end up being tracked, in which case this would need to be addressed at DNN level  
  👉 Can you confirm that this is a problem?
3. Do you know if the `<version>` in the Dnn Manifest already existed in Dnn 7? this is important, because 2sxc can still run on 7.4.2
4. Do you know of a way we could down-bump the version number on a future upgrade? AFAIK DNN would not do that, since it would assume it's older and not install it. 

A viable solution I could think of is to give both yours and our DLLs other names - like `Microsoft.Extensions.DependencyInjection.2sxc.dll` so that DNN would see it as a separate DLL and not mess it up. But this would lead to a load of new issues like cleaning up an existing install - where deleting a DLL is possible, but if you include a delete-DLL in your manifest, it breaks new-installs which don't have this DLL. Or do you know of a way to achieve that?

**Comment by rezagarrow** [comment]
1. Yes that is correct. If the version issue gets fixed, then 2sxc cannot be installed after PlantAnApp because it comes with older versions of dependencies :-(
2. Not sure if DNN using EntityFramework. We just checked the 9.9.1 install package and it does not have it.
3. It looks like it's there at least from the [initial commit on GitHub](https://github.com/dnnsoftware/Dnn.Platform/blame/4e6fa4c5bb5d8bc408db37ac4905990384b2f098/DNN%20Platform/Library/Services/Installer/Installers/FileInstaller.cs#L300)
4. Apart from a SQL script or maybe unregistering the dlls through the manifest and then re-register them (not sure what order of execution is used by DNN when running the manifest / installing the extension), no we do not know of any other.

**Comment by iJungleboy** [comment]
I believe this cannot really be solved unless DNN makes changes. I created an issue for this https://github.com/dnnsoftware/Dnn.Platform/issues/4704

Please also chime in there to help push it's priority.

**Comment by iJungleboy** [comment]
Based on the DNN feedback you and I are doing it wrong, we shouldn't use `Assembly` in the web.config but secretly include the bins using a ZIP.

**Comment by rezagarrow** [comment]
@iJungleboy Discussed it with the team today and we're going to implement the change on our end over the next week or two.  Where did you land on it?

**Comment by iJungleboy** [comment]
My goal is that we'll implement the fix, but probably not until summer because anything affecting the installation can be messy to test in all scenarios, so it will need some time and we cannot prioritize this. But if you already implement it on your side, you're safe and our modules can peacefully co-exist 👍

**Comment by iJungleboy** [comment]
@rezagarrow any progress on your side?

**Comment by rezagarrow** [comment]
Hey there.  Apologies for the delay.  I went to reply the other day and forgot to click the Comment button.
I think we have this fixed.  There may be an edge case or two (still testing various configurations/DNN versions).
With that said, we're pushing it out in our 1.15 release today!

**Comment by iJungleboy** [comment]
Sounds great. What will you change?

**Comment by rezagarrow** [comment]
I believe it essentially came down to us adding.NetCore assemblies as files instead of assemblies and adjusting the pointed assembly bindings to 2.2.0 version within our own bin folder.  
I'm out of my depth here, so hoping @dimarobert can chime in.

**Comment by iJungleboy** [comment]
I assume @rezagarrow fixed this a while ago on PlantAnApp, so I'll close for now.
