### ISSUE TITLE
Feature/Enhancement Request - Add the Options to Export Content Type(s) with View Export

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2464]
I'm submitting a [x] feature request about [x] admin experience and [x] Content Types or data management.

**Current behavior**  
You can export a View for import elsewhere. But it is only the View, its settings, and the code of the token or razor file. 

**Enhanced behavior**  
Upon initiating the export, add a dialog that by default does the same thing as it does now, but show some options, mainly:
 
  [ ] Include Content-Type(s)
  [ ] Include the data in the CTs
 
So this would then additionally export the following Content-Types if they are specified, not null:

- Content-Item
- Content-Item Presentation
- List; Header-Item
- List; Header-Item Presentation
- Settings
- Resources

**Why change the behavior?**

This would effectively allow a useful View with all its needed data to be exported in to a simple package that could be added to another 2sxc app in another project. In normal apps, the use case would only be occasional. But in the Content App, this would have a huge ROI. 

We have used the Content App quite a few times in projects and often we add new content types + views to handle specific things that don't merit a full solo 2sxc app. Examples are Grids, Accordions, Cards, and then variations of the existing content types that we usually name ContentPlus, PersonPlus, etc. Moving these (reusable) efforts to new projects is error prone and time consuming. Even with a detailed how to and step by step, most intermediate users cannot successful take an existing View and get it working on another Dnn/2sxc site.
 
**Alternative Approach with the same goal?** 

Leave the View Export as is, and instead enhance the Admin/App tab's **Export or Import parts of this App** section titled, "(Views) Templates Without Content Types" so that each selected view would allow you to  optionally add each View's needed Content-Types (as I outlined above).

**Anything you would like to add**

You might ask, "Why not just make each one of these things an App? Problem solved?" Because that is not a good user experience. These are specifically quick page content build out things. 

Further, imagine installing the Content App and then finding out you can import more Views+CTs via a simple download of a Zip? I am sure we could share a few useful ones right away. Especially if the 2sxc site added an "App Parts" or "App Addons" category or section to the app catalog.
 
This could allow a website-builder style library of working "parts" to be quickly added to a site. Very exciting idea if you ask me. It could dramatically speed a Dnn website build out in the future.

Content Manager: "Hey, how come I don't have that cool Grids thing to use on that site?"
Me: "Here is a link, import it and you'll have it there and ready to use in less than a minute."
Content Manager: "Wow, that is cool."

**Comment by iJungleboy** [comment]
Hi @jeremy-farrance 

I understand your needs, but believe we need a more comprehensive approach. For me this ties in together with the question of upgrading apps etc. 

My long-term goal is to create something where you can pick up a source-app and a target-app, browse through differences and transfer / sync the parts you want - down to field-definitions etc. 

I believe this is where we should go, because there are so many more complexities involved and every partial solution forces us to maintain more code, and still never satisfy people. 

For example: the current view-export/import fails, when the languages are different on source/target. It's a partial solution but because it's not done, it causes issues, support and almost forces us to prioritize enhancing it - instead of investing resources into a more comprehensive solution. 

I will be off to Tanzania for 7 weeks and will be back mid of August. My guess is that we'll implement a comprehensive sync-solution till the end of the year. 

Your thoughts?

**Comment by iJungleboy** [comment]
Cleaning up old issues.

We have something planned within the next quarter which should address this, but not as described here, so I'll close this.
