### ISSUE TITLE
No editing possible

### ISSUE THREAD

**Issue by AndreasDecke** [2sic/2sxc#2480]
**Problem**
I did everything according to the instructions! (Install Oqtane 2 on IIS 10 (Workstation or Server)) There is also no feedback whether something went wrong.

Unfortunately the icons for editing the content are missing. An JS
![28-07-2021 18-08-09](https://user-images.githubusercontent.com/45657628/127359829-e02d12e8-04cb-49ed-9d38-7a7e80ee8f77.jpg)
 error is displayed in the console (Chrome, show Image).

**Your environment**  

* **Oqtane version(s):** 2.2.0
* **2sxc version(s):** 12.02.01
* **Browser:** [all | Chrome 92.0 | Firefox 90.0.2 | Edge 92.0
* **Language:** [English | German | other ]

**Comment by iJungleboy** [comment]
We'll check asap. I believe it's because Oqtane 2.2 has some breaking changes in regards to Bootstrap or JS.

**Comment by tvatavuk** [comment]
I see the issue. It is because jQuery is missing (the current 2sxc depends on it).

2sxc 12.02.01 depends on jQuery from Bootstrap 4 included in Oqtane 2.1.
In Oqtane 2.2 bootstrap is updated to Bootstrap 5 (and that removes jQuery dependency).

A quick fix could be to include again jQuery (that was used in Bootstrap 4 ... "//code.jquery.com/jquery-3.5.1.slim.min.js") as 2sxc Oqt Resource, or similar...

Another option is to evaluate removing jQuery as a dependency from 2sxc.

**Comment by iJungleboy** [comment]
We'll try to fix this asap, so that 2sxc will automatically add jquery in Oqtane. 

We'll also review how we can improve the inline editing to not need any jquery.

**Comment by iJungleboy** [comment]
See also #2492

**Comment by iJungleboy** [comment]
fixed in 12.04
