### ISSUE TITLE
Bug: Exporting and then Importing my custom app fails due to illegal characters in path

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2485]
**I'm submitting a ...**  
[x] bug report 
[x] not sure

**...about**  
[x] admin experience UI

**Current behavior**   

I created a custom app on a staging site. I then exported the app and went to import it into a live site that uses the same 2sxc version (12.2.1). When I go to import, after about 30 seconds I get an error message: "Could no import the app / package: Illegal characters in path."

![Screen Shot 2021-08-07 at 12 34 52 PM](https://user-images.githubusercontent.com/8751936/128612038-5f288dbb-beda-41ab-b135-c197f3499258.png)

I tried both exports, the plain one and the one with the content included and I get the same error.

**Expected behavior**   

**Instructions to Reproduce the Problem**

Create an app on a staging website. Export the app. Then go to import the app into a different site.

**Why change the behavior?**  

I think it's a bug

**Your environment**

Nothing special.

* **2sxc version(s):** 122.1  
* **Browser:** [all  ]
* **DNN:** [9.9.1 ] 
* **Language:** [any/all | English ]

**Anything you would like to add**

**Comment by ajplopez** [comment]
Turns out the the import fails because some of the files the content editors uploaded has Chinese characters in the file names. 

To fix the import, I had to rename the files and then delete them from ADAM before doing an export.

It would be better if there was at least some kind of warning. Of course, it'd be ideal if it doesn't get caught up on illegal characters or Chinese characters in file names.

**Comment by iJungleboy** [comment]
@ajplopez  Could you drop us a file with such Chinese characters for better reproduction?

**Comment by ajplopez** [comment]
I don't have an example anymore. But it looks looks like when you upload a file (called 波巴茶.jpg) via ADAM, it uploads it as "???.jpg" where it replaces the characters with question marks. Then the whole import is invalid for importing.

**Comment by iJungleboy** [comment]
Update: I tested uploading such a file and that worked. So the adam-upload preserves the name as expected:

![image](https://user-images.githubusercontent.com/5321186/129672992-6fa70dda-6954-4483-8b7a-d6be6d3fadda.png)

**Comment by iJungleboy** [comment]
It seems to be an issue with the ICSharp ZIP library. The version included in DNN 7.4.2 doesn't really support Unicode (support was added later in V1, DNN has 0.86 - see https://github.com/icsharpcode/SharpZipLib/wiki/Release-History#changes-for-v10)

Since 2sxc is meant to still work with DNN 7.4.2 we cannot just fix this. I even attempted to set the Zip-entry flags manually, but it doesn't seem to work. 

```
            var entry = new ZipEntry(fileRelativePath)
            {
                DateTime = DateTime.Now,
                // 2021-08-17 Future: use IsUnicodeText, but because DNN 7.4.2 still has an old ICSharp v0.86.0.518, we cannot use this property yet
                // entry.IsUnicodeText = true;
                // ...instead we must set the flag
                // but it doesn't work - unsure why, but according to the history, Unicode wasn't added till v1.0 (https://github.com/icsharpcode/SharpZipLib/wiki/Release-History)
                // Flags = 0x0800 // 2048; // this should have the same effect as IsUnicodeText
            };
```

So for now I think there is no good solution which doesn't risk other problems, so we cannot continue on this ATM, sorry.

**Comment by iJungleboy** [comment]
Will close for now, as we cannot fix in the near future.

**Comment by ajplopez** [comment]
Ok, thanks. Just so I understand - you do see the issue but there's nothing that can be done at this time. So I will just have to make sure to watch out for illegal characters being uploaded via ADAM before export-import.

**Comment by tvatavuk** [comment]
In my simple test, during 2sxc app export, ICSharp ZIP library (part of DNN, used by 2sxc module) created zip that contains adam file `波巴茶.jpg` with the wrong filename `???.jpg`, and this zip file can not be imported later due to illegal characters in path error.

It is expected that export app zip contains adam files with the right filenames like `波巴茶.jpg` so it can be imported without issues. 

So to quickly test this import part, using total commander I manually replaced adam files in exported app zip (so in zip I got adam file with the right filename `波巴茶.jpg`). After that, 2sxc app import from manually fixed zip worked without issues. In dnn I got imported adam files with the right filename `波巴茶.jpg` and the imported 2sxc app is working as expected.
 
In my test (DNN 9.10.0, 2sxc v12.03.00-pre2) ICSharp ZIP library issue with unicode filenames was limited to zipping files (for export zip) and unzipping unicode filenames worked as expected (in app import).
