### ISSUE TITLE
Updating Apps when Upgrading?

### ISSUE THREAD

**Issue by BGillham** [2sic/2sxc#2566]
**I'm submitting a ...**   
[x] feature request
[x] DNN parts
[x] other / unknown

**Current behavior**   
Upgrading to the latest version was painless but... 
I have an issue when Updating the Apps to the latest version.
eg: Installing Blogs4 when Blogs3 exists results in two Blog Apps!

**Expected behavior**   
eg: Installing Blog4 when Blog3 exists should result in 1 x Blogs App with the latest version.

**Instructions to Reproduce the Problem**
Install Blogs4 when Blogs3 exists

**Why change the behavior?**  
Without being obvious, there should only be ONE version of each App

**Your environment**  
DNN9.10.02
* **2sxc version(s):** 12.6.0  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [9.10.02 ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**
I apologise if I am asking inane questions but I am fairly new to your amazing CMS Tool.

**Comment by BGillham** [comment]
Will v12.08 address the issue? Or is there a Procedure to follow in order to Upgrade Live Sites?
I have looked for a "Best Practices" but cannot seem to find it so perhaps you can advise me there... 
Thank you once again for a great product...

**Comment by iJungleboy** [comment]
No, 12.08 will not address this issue - it's an edge case where a template app of ours wasn't quite ideal, but we believe it's only installed ca. 5-10 times, and it's better to fix these than to bloat 2sxc. 

What doesn't make sense is - if you changed it to `Convert.ToInt(...)` the error should at least change - because the error originally said `Convert.ToInt32`. What is the new error you get? it has to be different, otherwise you were changing the wrong file.

**Comment by iJungleboy** [comment]
BTW: We also upgraded a site having the temporary swiper app, and there was also a `ToSingle()` which had to be replaced with `ToFloat(...)`. Then it worked.

**Comment by BGillham** [comment]
Did you make that change in the "_swiper.cshtml"?

**Comment by iJungleboy** [comment]
yes. 
BTW: The next release of 2sxc will have a hidden ToInt32 and a hidden ToSingle so that the old code will continue to work.
