### ISSUE TITLE
Permissions Content module

### ISSUE THREAD

**Issue by ArankaBond** [2sic/2sxc#2577]
**I'm submitting a bug report

**...about**  
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management
[x] DNN parts

**Current behavior**  
We need to ass permissions on the Content module, so that a security role can only edit the content, not delete or other things.
He does not have page permissions.

**Expected behavior** 
To be able to add permissions based on role or even userid, we activated the features.

**Instructions to Reproduce the Problem**
The permission buttons are not enabled, we can not use them, not in the app permissions or data/view permissions

**Why change the behavior?**  
This is a basic feature we use a lot

**Your environment**  
Windows, Chrome, Logged in as Admin

* **2sxc version(s):** 12.2.1
* **Browser:** [all ]
* **DNN:** [9.10.01] 
* **Language:** [any/all]

**Anything you would like to add**
In the screenshots below, you see that all permission buttons are disabled.

![image](https://user-images.githubusercontent.com/28566983/139839924-2327577a-4961-44fe-80b2-40c188d9ab4a.png)
![image](https://user-images.githubusercontent.com/28566983/139839955-0587907b-2374-4ea7-b38b-5b613356e3de.png)

**Comment by iJungleboy** [comment]
Just for clarification: 

1. App Permissions relate to data and content-types on the app, not to module-instances in a page. So these settings on the app should not have any relevant effect on modules - it's more commonly used for API scenarios and more advanced use cases with data-lists (which isn't normal on the primary Content App)
1. IMHO App-Permissions have never been available on the Content-App, since it's meant for data-centric operations which are not recommended (and most APIs for that are disabled on the Content App)

So just that I understand what you're saying, because you say you use this a lot - has this been possible in a previous version of 2sxc - or is this just that you would _like to do this a lot_?

**Comment by ArankaBond** [comment]
I was confused by another selfmade App which was our way for the content app.

But is there another way of adding permissions for editting the Content, without having to use the DNN page or module permissions?
We want to make sure he can edit the text, but can not delete or add modules.

**Comment by iJungleboy** [comment]
Off the top of my head: I'm not sure. 

It's possible that it can be done with various things like content-type permissions and some special steps in Razor, but it would probably not be official and difficult to figure out the first time. 

We could investigate this for you (ca. 2h of paid work - see https://2sxc.org/en/contact) and we might then have a recommendation, or it may need some more changes to make it fly.
