### ISSUE TITLE
Feature Request: Ability to add external plugins to TinyMCE

### ISSUE THREAD

**Issue by ufoloko** [2sic/2sxc#2613]
Actually 2sxc allows to add custom TinyMCE configuration extending options, but is not allowed to add new plugins. I have tried to add a new non standard plugin (example codemirror or visualblocks) but editor crash.

I tryed to add plugins placing files on plugins folder but errors appears and editor don´t load

It should be great to have this functionality to add more options for this editor.

**Comment by iJungleboy** [comment]
As of now you can do this, but you'll need to create a custom Input Component. 

We have some examples in the Razor Tutorial and I believe most of it is explained in the docs as well. 

I don't think we'll add the feature to do this with configuration only any time soon, simply because we don't have the resources / priority for this. 

If someone else wants to contribute - great!

**Comment by ufoloko** [comment]
Thanks. I just worked in a solution to get the dnn ckeditor back, based on tutorial located in [https://2sxc.org/dnn-tutorials/en/razor/ui221/page](https://2sxc.org/dnn-tutorials/en/razor/ui221/page) Maybe can be helpful for somebody else. im attaching result file with some comments for better understanding.

[index.js.zip](https://github.com/2sic/2sxc/files/7678729/index.js.zip)

**Comment by iJungleboy** [comment]
That's very cool :)! 
Thanks for sharing
