### ISSUE TITLE
Entity data type: if the table/data type changes name, every field that targets this entity will need reset

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2760]
**I'm submitting a ...**
[x] feature request

**...about**  
[x] Content Types or data management

**Current behavior** 
Let's say you have two data types: e_dogs and e_breeds.
e_dogs has a field named f_breed, with points to the entity e_breeds.
If you change the name of e_breeds to e_dog_breeds, the field f_breed will still look for the old name and find no entries.

**Expected behavior**
The field should look for the entity by some ID (EntityId or Guid) and not the name, since it can change.

**Comment by iJungleboy** [comment]
Just to be sure we understand the issue

1. You have one type - maybe `dogs` which had a field `breed` - there you had an entity-picker showing all items of type `breed`
2. After renaming breed to something else, the dropdown didn't show further options, because the name had changed

Assuming this matches your issue then I agreed it's not convenient (I had run into this a few times myself). 

Changing this would be very difficult and take probably a days work, because historical data would still have to work. Because of this, I don't think we'll address this anytime soon, so I'll close this.
