### ISSUE TITLE
2sxc module disappears from page until reloaded after modal window closed.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [2sic/2sxc#2822]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**   
After editing entity in modal window and closing it in any way (saving changes or canceling) - 2sxc module just desappears from page and manual page reload is needed to make it appear on page again.

**Expected behavior**   
2sxc module object should be still on page.

**Instructions to Reproduce the Problem**

1. Click edit button on any 2sxc module tagToolbar
2. Close window
3. See that view of that module is not displayed on page any more
4. Reload page manually
5. See that module is displayed again

**Why change the behavior?**  
Cause it's very inconvenient and takes some time to manually reload page during development process to check some minor changes in process.

**Your environment**  
Windows 10
Visual Studio 2019 & 2022

* **2sxc version(s):** 14.7.3  
* **Browser:** [Chrome Version 103.0.5060.114 (Official Build) (64-bit)]
* **DNN:** [9.10.2] 
* **Language:** [English]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
This seems to be something unusual. Normal editing doesn't cause this. I've just verified it to be sure. 

Minor detail: maybe you need to update to 14.7.4?

So internally each app can specify if it supports AJAX reloading - which allows fast module-only update after editing. This is a setting at the App level. By default, the Content-App had this active all the time, and most apps we release today have it enabled too. 

If you have another app this could be on or not - but it would impact this. For example, if it requires JS to run on-page-load, this would probably update and then now show anything, because the JS isn't running. 

It's also possible that it's using some variable from the URL which may be missing on the AJAX call (since it's not the real page being loaded). 

Either way I'll have to assume it's fixed with an update, and/or your razor view isn't working either server-side or the JS being loaded isn't run after the reload. 

To fix: investigate the app setting, then see what the ajax-api call returns which is replaced, and check any JS being loaded if it's not running on ajax. Maybe just disable AJAX for this app.

**Comment by Constantine-Ketskalo** [comment]
> Minor detail: maybe you need to update to 14.7.4?

Looks like that was it. I've been updating 2sxc some time ago. Not sure about versions though, cause I don't remember it and I didn't check git history. But looks like it was fixed by some update cause I can't reproduce it any more. Thanks for the reply and suggestions anyway.
