### ISSUE TITLE
Feat: Improve Formulas

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2831]
**I'm submitting a ...** 
[x] feature request

**...about** 
[x] admin experience UI
[x] JS development
[x] Content Types or data management
[x] other / unknown

**Current behavior**
Formulas have come a long way since implementation, and they are very useful to my research apps.
I can create random IDs, generate hashes, etc, which is actually a crucial aspect of research anonymization.

**Expected behavior**
A couple things could be improved:
1. Access app.resources and app.settings, so that we can store keys and other elements needed for formulas.
2. Access entity type data. If a field has the type Entity, and is linked to another data type with a couple fields, the formula could have the ability to lookup these fields in the data.

**Comment by iJungleboy** [comment]
I understand the need for these features. 

## Regarding 1. App.Resources & App.Settings

I don't think we would implement this any time soon. The reason is that there are security implications which developers wouldn't notice. Like if all the settings would be included, there could be passwords or something that were not intended to be published. Resources have a similar problem: A large app can have hundreds of resources, and loading them all by default to enable this use case could slow down all forms even though almost nobody needs them. 

For now, I suggest you create an endpoint to just get the values you need. 

## Regarding 2. Entity Data of Sub-Entities

Quite clear why you would like to have this. There are some difficult challenges here - like if we would pre-fetch the data (slowing down the form) or using promises - which is much harder to code with. Both cases have a lot of issues and need a lot of time developing them. So I don't think it will happen soon. 

For now, I suggest you create an endpoint to just get the values you need.

**Comment by eXistenZe** [comment]
Can you give me a couple examples of how and where I can store some values that can be accessed in the formula?

**Comment by iJungleboy** [comment]
We'll publish some example formulas in a few days on our tutorials. I'll post them here when they are published.

**Comment by iJungleboy** [comment]
Here's some new tutorials showing how to access webapis from formulas

https://2sxc.org/dnn-tutorials/en/razor/f200/page
