### ISSUE TITLE
Persistent error "Thread was being aborted."

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2839]
**I'm submitting a ...**
[x] bug report 
[x] not sure

**...about**
[x] other / unknown

**Current behavior**
My dnn log is flooded with these errors:
```
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
PortalId:-1
UserId:-1
TabId:-1
Message:Thread was being aborted.
StackTrace:
   at ToSic.Sxc.Blocks.BlockBuilder.RenderInternal() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Blocks\BlockBuilder_Render.cs:line 134
Source:ToSic.Sxc
```

Cannot pinpoint it to a particular app or user.

**Your environment**  

* **2sxc version(s):** 14.3
* **DNN:** [ 9.10.02 ] 
* **Language:** [ English ]

**Comment by iJungleboy** [comment]
Since it says portal=-1 etc. I assume it's something that happens during DNN Full-Text indexing. Possibly you have a razor template or something that isn't configured correctly and/or has code that doesn't work when there is no http-request attached. 

To verify this, try to either disable the DNN site indexing and/or compare time stamps with indexing scheduler. Then please report your findings. 

BTW: This looks more like support than a 2sxc bug. Because of this, I ask you to continue on StackOverflow unless it's found to be a 2sxc issue and you know more about the exact cause etc.
