### ISSUE TITLE
Formula: context.user.isSiteAdmin does not work

### ISSUE THREAD

**Issue by 10poundgorilla** [2sic/2sxc#2843]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Razor templating
[x] JS development
[x] Content Types or data management

**Current behavior**   
It will not identify any DNN administrator, even the primary administrator in the Adminstrator role as true to isSiteAdmin. Only host level users will return as true and host users return for true as well for isSystemAdmin. 

**Expected behavior**   
isSiteAdmin should only mark as true if DNN administrator security role is given.
isSystemAdmin should NOT mark as true for DNN super users (unless this was intended to include all lower level access as true)

**Instructions to Reproduce the Problem**

Create any formula using context.user.isSiteAdmin on a field type.
Login is an administrator and test, check to see if the console is reporting that user as true as it should but it will not. 

**Why change the behavior?**  

**Your environment**  
Any environment, any browser.

* **2sxc version(s):** 14.07.4  
* **Browser:** [all ]
* **DNN:** [ 9.10.2 ] 
* **Language:** [any/all ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Just to be sure - is in not correct in Razor (ICmsUser) or in the Formula (JS stack)?

**Comment by 10poundgorilla** [comment]
I have not tested in Razor. 

Does not seem to be working in Formula (JS Stack).

**Comment by iJungleboy** [comment]
Ok, we'll look into it. thx.

**Comment by iJungleboy** [comment]
I just reviewed it and can verify it's not working in formulas. Both `isSiteAdmin` and `isSystemAdmin` seem to be true/false only based on super-user permissions (at least it 14.08).

1. `context.user.isSiteAdmin` must be true for admins and for super users (because both can admin the site)
2. `context.user.isSystemAdmin` must only be true for super users

this is what F12 shows when debugging formulas (14.08) on host user:

![image](https://user-images.githubusercontent.com/5321186/195392080-89ae8cb2-27c1-4417-9d7f-360f75b64efd.png)

but for admin, both are false. we'll research this some more...

**Comment by iJungleboy** [comment]
Solved will be in 14.09

Note that we have `isSiteAdmin` and `isContentAdmin`.

Difference is that if is admin, `isContentAdmin` will always be true. 

But if the `isSiteAdmin` is different, because you can add more roles to DNN to disable many advanced admin features:

1. If there is no helper role like "2sxc Designers" or "2sxcAdministrators" then isSiteAdmin would be true
2. If these roles exist and the user is assigned to one of them, it is also true
3. if these roles exist and the user is not assigned to them, `isSiteadmin` will be false
