### ISSUE TITLE
Toolbar: Improve filter feature to support giving entities as filters

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2845]
**I'm submitting a ...**   
[x] feature request

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Razor templating

**Current behavior**   

When using the Toolbar-Builder to get a `data` list of items it's common to include a filter, but this can be finicky. 
Goal is to make an automatic handler of parameters on the `filter:` property, so that various combinations of this should work:

```
filter: new { Author = entity}
filter: new { Author = [entity1, entity2] }
filter: new { Author = someListOfEntities }
filter: new { Author = new string[] { key1, key2 } }
```

**Your environment**  

* **2sxc version(s):** 14.07.05

**Comment by tpperlman** [comment]
Hi Daniel. Based on this improvement, shouldn't this link click filter be working?

`$2sxc(this).manage.run({ action: 'contentitems', contentType: 'Reviews', filter: new { Approved = false } });`

Because it is returning the error below:

`Uncaught SyntaxError: missing : after property id`

It works fine without the filter as so:

`$2sxc(this).manage.run({ action: 'contentitems', contentType: 'Reviews' });`

We also tried these, which similarly didn't work:

`$2sxc(this).manage.run({ action: 'contentitems', contentType: 'Reviews', filter: 'Approved=false' });`

`$2sxc(this).manage.run({ action: 'contentitems', contentType: 'Reviews', filter: 'Approved=false' });`

We're running 2SXC v14.12.3 and would consider upgrading if that is the issue, but we'd have to verify all the other 2sxc modules used throughout the site.
