### ISSUE TITLE
Library of files still accessible in view after deleting the field

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2848]
**I'm submitting a ...**
[x] not sure

**...about**
[x] Content Types or data management
[x] other / unknown

**Current behavior** 
I had a field set to library of files, for image uploading with adam.
Added a few examples for testing.
Created a code with:
```
var images = AsAdam(c, "UserConsent").Files as Dynlist;
foreach (var i in images)
    {
        <img class="img-fluid" 
          src='@Tags.SafeUrl(i.Url + "?w=25&h=50&mode=crop&scale=both&quality=80")' 
          alt="abc" />
    }
```
After deleting the field, the view keeps working, so the information in adam is still tied to a data type that no longer exists. And the files too.

**Expected behavior** 
When deleting a data type linked to uploads, ask if the files and metadata should be deleted too.

**Comment by iJungleboy** [comment]
The adam library is not really stored anywhere, it's just a convention as to where files of a field are stored. 

Since assets are not deleted, it can still find them based on the convention and doesn't realize the field doesn't exist. 

In a future API (the fairly new `Field("...")` it would probably not happen any more, but otherwise this is by design and not planned to be changed any time soon.
