### ISSUE TITLE
Show fields side by side in form

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2874]
**I'm submitting a ...** 
[x] feature request

**...about** 
[x] Content Types or data management

**Current behavior**  
All fields in a form show inline.

**Expected behavior** 
When fields are grouped in a header, the header could be configured to show side by side, using columns in bootstrap.

**Comment by iJungleboy** [comment]
Thanks for the suggestion. 

I believe this will challenging because it would need some kind of configuration + ways to stop it (so some fields side-by-side, followed by not-side-by-side etc.) and more. So to do this right, probably ca. 2 days of work. 

Because of this I don't think it will be on our priorities any time soon, which is why I'll mark it as requiring sponsor and close it for now.
