### ISSUE TITLE
ContentGroup not being created

### ISSUE THREAD

**Issue by vandersonpessoa** [2sic/2sxc#2983]
### I'm submitting a ...
[x] not sure

### ...about
[x] Content Types or data management

### Current Behavior / Expected Behavior

A customized Content Type (Series) was created to feature all the necessary data for our pages. The information should be divided into sections, so we've been using ContentGroup entities with Templates for that. However, editing a field whose template and Series don't have a ContentGroup entity associated, doesn't trigger the creation of a new record. Is there any scenario that editing a customized Content Type (that is associated to a Template) triggers the creation of a ContentGroup? Also, is there any documentation that can help us with this issue?

### Instructions to Reproduce the Problem
Editing a field from the customized Content Type that was previously empty.

### Your environment
DNN EVOQ 9.10.06

* **2sxc version(s):** 14.11
* **Browser:** all
* **DNN:** all 
* **Hosting platform:** IIS
* **Language:** any

**Comment by iJungleboy** [comment]
@vandersonpessoa Your issue is very confusing. Could you make a video or something to make it clear what you're trying to do and what doesn't work?

**Comment by vandersonpessoa** [comment]
We've created a new content type (Series) with all the information for our pages that have integration with the 2sxc component.

![series](https://user-images.githubusercontent.com/51916596/214905643-1a2d08f0-8e43-40bb-ae97-f950e8e4491b.PNG)

The Series content type has multiple fields and to show them in the different sections of the page, we've used templates/views. Basically, the Content Group entities were imported and they reference 2 things:
1. The Template/View
2. The Series Content

![content-group](https://user-images.githubusercontent.com/51916596/214905745-2a7c867e-5a61-4b28-a2f1-b90d64b4df04.PNG)

The Content Groups are used by the DNN modules. The modules reference the Content Group GUID in their property ToSIC_SexyContent_ContentGroupGuid.

![guid](https://user-images.githubusercontent.com/51916596/214905846-86f34c97-d5d1-4103-8597-22fe717556a2.png)

![module-db](https://user-images.githubusercontent.com/51916596/214905868-43c93cbf-8da0-494a-b1c8-6d49749ce314.PNG)

That’s how they look on the page.

![apc-template1](https://user-images.githubusercontent.com/51916596/214905990-197e0d06-5a39-432e-8a79-7eec19617a36.PNG)

![apc-template2](https://user-images.githubusercontent.com/51916596/214905952-23cdac76-9f24-4ee9-bb84-1d00ffc07d61.PNG)

The Content Groups were not created for all the combinations of Series/Templates, since some of the fields were empty. So we'd like to know if it's possible to trigger the creation of new Content Groups by editing the previously empty Series fields.

Is there any documentation that can help us with this issue?

**Comment by iJungleboy** [comment]
So to start - thanks for an AMAZINGLY CLEAR DESCRIPTION! 🥳💃🏻

So my guess is you're doing something unconventional (which is probably fine) but it causes us to interpret slightly different meanings to the words. I'm still missing a detail, but I'm sure we can figure this out. 

1. You mentioned an import, so I'm not sure what you mean by that, can you elaborate?
2. How were the original groups created? You describe something of "because xyz was empty" but that isn't clear to me.
3. I have a feeling that you have say 200+ pages or something and that each item is on an own DNN page or something. Is this correct? On the other hand, why not use list/details where the url-parameter determines what should be loaded?

**Comment by vandersonpessoa** [comment]
1 and 2. We’ve generated xml files with all the content that we would like to be in the Adam components from the site database and imported them using the Content Admin.

![content admin](https://user-images.githubusercontent.com/51916596/215787703-e4c3344d-2caf-43d7-8d16-c22f6f2d5ddd.PNG)

The files look like this:

![xml](https://user-images.githubusercontent.com/51916596/215787797-2e58156f-eaaa-444f-967c-0afb00802fff.PNG)

3. We have hundreds of series pages, some of them share the same content though (SEO purposes). Not sure we’ve used list/details before, can you please elaborate or reference a documentation for this?

**Comment by vandersonpessoa** [comment]
Thank you for the clarification. I’ve checked the tutorial page for List/Details, but it doesn’t seem to be a short-term solution since it would change a lot of our site structure. 
So, I’d like to revisit our initial questions: 

Is there any way to programmatically trigger the creation of new Content Groups records?
Is there any documentation that can help us with this?

**Comment by iJungleboy** [comment]
Not really - and you would also need to find a way to assign it to the page it should be on. 

There is no API for this, because nobody ever need this before ;)

Technically you can do it - ContentGroups are also just entities, but you'll need to do some digging - eg. using App.Data.Create(...) and then of course after creating it, make sure there is a 2sxc-module on each page and in the DNN Module Settings assign the Content-Group to that module. 

This may help you get started https://docs.2sxc.org/basics/cms/content-blocks/content-blocks-in-dnn.html

Since this is certainly not a public issue but more of a support request, I'll close it now.

**Comment by ZacharyCPC** [comment]
> So to start - thanks for an AMAZINGLY CLEAR DESCRIPTION! 🥳💃🏻
> 
> So my guess is you're doing something unconventional (which is probably fine) but it causes us to interpret slightly different meanings to the words. I'm still missing a detail, but I'm sure we can figure this out.
> 
> 1. You mentioned an import, so I'm not sure what you mean by that, can you elaborate?
> 2. How were the original groups created? You describe something of "because xyz was empty" but that isn't clear to me.
> 3. I have a feeling that you have say 200+ pages or something and that each item is on an own DNN page or something. Is this correct? On the other hand, why not use list/details where the url-parameter determines what should be loaded?

@iJungleboy To respond to your suggestion in bullet #3, I agree that that would be a much better and simpler solution to how we're currently generating these pages. However, we are not only loading content from 2sxc on the pages, but a few DNN modules as well. Does 2sxc have a way of adding and displaying a DNN module within a 2sxc view?

**Comment by iJungleboy** [comment]
@ZacharyCPC 

You can load 2sxc inside 2sxc using built in APIs.
But there is no built-in API to load a DNN module inside a Razor page.

But AFAIK it can be done using DNN APIs, since it's all C#. It will take some API hunting though, but it should be fairly easy, because there are also modules such as tabbed-content modules that do exactly this (outside of 2sxc), and it should be easy to just duplicate that in a Razor file.

**Comment by ZacharyCPC** [comment]
@iJungleboy Good to know. I'll do some digging on that. Thank you for your help!
