### ISSUE TITLE
Unable to have blank image title in 2sxc v16 Basic Content Text/Image instances

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#3073]
### I'm submitting a

[x] bug report => search github for a similar issue before submitting

### ...about

[x] other / unknown

### Current Behavior / Expected Behavior

The problem is found in Basic Content instances of 50% Text / 50%, it is not possible to hide the title of the image (i.e. have no title on the image). Even when a title is not set in the Image Settings, the module uses the overall title of the module for the title (which is not wanted).

![2sxc-v16 - Basic Content](https://user-images.githubusercontent.com/3846223/236376605-9fa9c10f-3e58-40f2-b2e0-a9b14fb90b5e.jpg)

There seems to be no way of preventing the title "Welcome" from showing up on the image.

Here is what I have in 2sxc v15.3.0:

![2sxc-v15 - Basic Content](https://user-images.githubusercontent.com/3846223/236376967-269e9d4c-13f0-462e-b0f8-749bb238ec3a.jpg)

Note that there is no title on the image.

Sometimes I don't want a title on an image (which I could do with earlier versions of 2sxc).

Here are the settings for the module and for the image:

![2sxc-v16 - Basic Content Settings](https://user-images.githubusercontent.com/3846223/236377166-69beeb42-ec8e-481a-8899-da014e1ed6f1.jpg)

![2sxc-v16 - Image Settings](https://user-images.githubusercontent.com/3846223/236377192-40e10629-aa05-43e3-9de6-62bff1b85ed2.jpg)

Note that the image description is blank.

### Instructions to Reproduce the Problem

1) Install 2sxc v16 and all content and apps.
2) Add a 50% text / 50% image Basic Content object to the page.
3) Add text and image leaving the image description blank in the image settings.

There seems to be no way to tell 2sxc that there should not be a title on the image. Maybe I am missing something new in v16.

### Your environment

* **2sxc version(s):** 16.0.0  
* **Browser:** all 
* **DNN:** 9.11.2
* **Hosting platform:** IIS 
* **Language:** English (have not tested anything else)

**Comment by iJungleboy** [comment]
Hi @skarpik 

This is currently by design - it's in the Content templates. 

The image services `.Img(...)` has a new `imgAltFallback` which in the new content templates is set to be the initial title.

As of now we believe this is the desired behavior - as it matches the behavior before we had the new image configuration.

For now, you can simply change the razors to not do this in case you don't want that. 

If this is a regular concern, we'll see what we can do to make it more configurable (possibly a toggle or something).

**Comment by skarpik** [comment]
@iJungleboy thank you for the prompt and clear explanation. A toggle would be really helpful. Consider the following scenario:

- the user chooses to hide the title of the Text/Image instance (using the "hide" for the "heading type")
- they also use the Content Presentation Settings option to not show the title in the lightbox

Consequently the module title is a sort of orphan showing up nowhere but on the image.

Yes, the Razor code can be altered as you describe. However, a real strength of 2sxc is that it can be used by web developers (like me) who can dig into the code and create custom apps. But equally important, in my opinion, is that web developers who are more designers than coders, can use 2sxc to create really attractive websites without touching one line of code. My feeling is that there are a lot of people who love 2sxc to a large extent because it lets them focus on information architecture, content and design without ever thinking about code. Out-of-the-box, 2sxc offers some amazing power without requiring any coding at all.

**Comment by jeremy-farrance** [comment]
I just played with this and for the record, I agree with Steve that this is a problem. I understand how important having fallbacks is, but in this case there was expected functionality in previous versions; "no image title means no image title." The new logic is, "no image title? use the EntityTitle as fallback."

So I very much agree that they users and powerusers (content managers and editors that are not DEVs) need the ability to **not** have that unexpected title show up on the image.
 
I also think it is a bit odd and unexpected to show a title on the image when the field is blank. In my mind, it seems like a bug because it is unexpected. It seems like the simplest solution is to not fallback. I cannot see a situation where putting the module title (EntityTitle) text on top of the image makes sense. Just think for a moment about Steve's example above, how does the text "Welcome" on the image make any sense here? I just looked through one of our current projects and across 5+ pages did NOT find a single case where showing the title from the module/entity would have been useful or made sense. 
 
Anyhow, I hope this helps. I dislike the idea of having to modify the Content App templates every time we install them. @iJungleboy, I hope you reconsider your response above. Cheers!! - Jeremy
