### ISSUE TITLE
Error installing FAQ V4 - 2sxc v16.06.00

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#3181]
### I'm submitting a

[x] bug report => search github for a similar issue before submitting

### ...about

[x] admin experience UI

### Current Behavior / Expected Behavior
During auto-install of apps for v16.06.00, the FAQ v4 app failed to install.

![FAQ v4 install error](https://github.com/2sic/2sxc/assets/3846223/05edc49e-026b-4384-b75d-72f92c48a85c)

### Instructions to Reproduce the Problem

Created new DNN v9.12.00 website with 2Shine v5.0.5 theme. Installed 2sxc v16.06.00 then added app package to a new page. The error prevented loading the other apps.

### Your environment

* **2sxc version(s):** 16.06.00 
* **Browser:** Edge
* **DNN:** 9.12.00
* **Hosting platform:** IIS
* **Language:** English

**Comment by iJungleboy** [comment]
@ropalko

**Comment by ropalko** [comment]
Fixed release download path

**Comment by skarpik** [comment]
@iJungleboy and @ropalko - thanks for fixing the problem so quickly.

I have a couple of questions:

- For situations like this, is there a way to restart the auto-install? This is more a question of curiosity as I likely will start over. I created this website for the purpose of testing 2sxc v16.06.00 not for a project (for each release of 2sxc, I create a test website to test basic out of the box features)
- Based upon your development path, do you see an LTS for v16 in the not too distant future (I'm starting a new project and am wondering whether I should start with v16.06.00 or wait for an LTS)

Thanks again.

**Comment by iJungleboy** [comment]
Restarting Auto-Install is currently not possible.
There's a plan to provide it in later phases again, more like "install common Apps" but we're not there yet.

16.06 is IMHO very stable, we're using it in production.

Since I'll be on vacation for ca. 3 weeks we can't release it now, as we wouldn't be able to react quickly, but IMHO it's LTS quality. 

Note that all our standard apps have been upgraded to the new Typed model, but not released yet, as that will be in sync w/the LTS. ATM only the Blog, Mobius and FAQ are published with typed code.

**Comment by skarpik** [comment]
Thanks. Enjoy your vacation.

**Comment by iJungleboy** [comment]
though we're just reconsidering maybe LTSing today... ;)
