### ISSUE TITLE
Scheduled publishing for draft edits (feature request)

### ISSUE THREAD

**Issue by 6TELOIV** [2sic/2sxc#3435]
### I'm submitting a
[x] feature request

### ...about
[x] edit experience / UI
[x] admin experience UI

### Current Behavior / Expected Behavior
This is a feature request for the ability to schedule draft edits to a content item to be published at a certain time.

How I picture this could work:
- A new option is available under save modes called "Schedule".
- When selected, two additional fields are available, maybe below presentation options, called "Scheduling Options"
   1. Scheduled for - a date/time field, which lets the user pick when the scheduled change will happen
   2. Change to - a string dropdown specifying what should happen at that time. Options would be "Show" or "Hide"
- Users with draft-only permissions (no publishing perms) would continue to operate the same way; upon saving, it will always revert to "Draft" instead of any other save mode.
   - This ensures that they cannot make edits that are then published by the schedule. Someone with publishing perms would need to set the schedule
- Then, with a scheduled task, all content items with schedule dates in the past and publish status of "Scheduled" are set to their "Change to" field (show or hide)

### Instructions to Reproduce the Problem
Here are some examples of situations that arise with us:
- Event information needs to be changed from present to past tense after the event has passed
- A program is scheduled to end on a certain day, and a message needs to be added to the content saying such
- Inner content needs to be published/removed at a certain time (DNN/Evoq start/end date won't work for inner content)

### Your environment
* **2sxc version(s):** 17.09.00
* **Browser:** all
* **DNN:** 9.13.02
* **Hosting platform:** azure
* **Language:** any/all

**Comment by iJungleboy** [comment]
This would be an interesting enhancement, but it would take 2-5 days to implement, so it's not on our priorities.

It could take up to 5 days, because there are additional challenges when working with workflows - since Dnn may need to be informed about the state change if workflows are in use - so quite complex!

As a workable implementation now you need to do a bit more with code etc. and using a "Published" date-time field, filter for that etc. This is what the Blog app does for example. 

Since this is unlikely to happen any time soon, I'll mark it as needing sponsorship and close for now.
