### ISSUE TITLE
Public forms - 401 on /api/2sxc/admin/dialog/settings?appId=

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3477]
### I'm submitting a
[x] bug report
[x] not sure

### ...about
[x] Content Types or data management
[x] other / unknown

### Current Behavior / Expected Behavior
When I open the edit form to create or edit an entity using public forms, I now get error on the link
GET | https://x.pt/api/2sxc/admin/dialog/settings?appId=1029
Authorization has been denied for this request.

### Instructions to Reproduce the Problem
This is a recent issue. V18?

### Your environment
* **2sxc version(s):** 18.01
* **DNN:** 9.13.4

**Comment by iJungleboy** [comment]
thx.

Is the form still usable, or does it break?

**Comment by iJungleboy** [comment]
@enfJoao thanks.

In this case it's some code in the wrappers which too aggressively is looking for the settings, but it's actually not used, since the edit-ui gets the relevant settings on the `load` call.

So not urgent, but not nice.

**Comment by enfJoao** [comment]
Please give this issue some love :(

**Comment by iJungleboy** [comment]
Just reviewed this and noticed, that the user gets a nasty error message.

I was not aware of this, and assumed it's just a console-log (which would not be urgent).

Next time best include a screenshot or something, that we realize it's a critical issue.

Will be fixed in next release in a few days.
