### ISSUE TITLE
Oqtane - Kit.Page.Activate fails to activate jquery?

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3478]
### I'm submitting a
[x] bug report 
[x] not sure

### ...about
[x] Razor templating

### Current Behavior / Expected Behavior
Using strong typed templates with either
`Kit.Page.Activate("2sxc.JsCore")`
or
`Kit.Page.Activate("turnOn")`
but both result in 
`Uncaught ReferenceError: $ is not defined`

### Your environment
* **2sxc version(s):** 18.01.00
* **Oqtane:** 5.2.3
* **Hosting platform:** IIS

**Comment by iJungleboy** [comment]
This issues is a bit confusing.

2sxc does not use jquery at all. 
So activating turnOn or JsCore will also not activate jQuery, they are not seen as part of 2sxc.

I assume the message you are seeing is from your code (or the code of the app you're running), not from 2sxc JS code.

TBH we never tried using jQuery in Oqtane, since a) we don't use it and b) Oqtane is quite new and typically won't want to use these old libraries. 

So for now, if your app needs jQuery (and it could easily run into problems since Oqtane often reloads the DOM), then you should either include it in your app or use a script tag or something to get it from a CDN...

**Comment by enfJoao** [comment]
Oh... many guides still point to $2sxc so I assumed 2sxc loaded it if not present at the CMS.

I'll take a look at the documentation again to find up to date alternatives to my old apps.

**Comment by enfJoao** [comment]
For example, what would be a modern version of public forms example:

```
$2sxc.cms.run(tag, "new", { contentType: "Partners"})
            .then(function () {
                alert("Thanks - we'll review your entry and publish it.")
            });
```

**Comment by iJungleboy** [comment]
The sample above is fine, `$2sxc` exists and that's how it should work.

But it doesn't use jQuery. The original issue title and body suggests you're having problems with `$` (not `$2sxc`) and that is jQuery.

**Comment by enfJoao** [comment]
I spent the last 10 years thinking $2sxc was jquery :( 
Let me rebuild my app so I can remove all true jquery traces and see if the issue persists.
Sorry.

**Comment by iJungleboy** [comment]
:)

We really worked hard to get rid of jQuery 

The last step was to ensure that anything that used the $2sxc which had some jquery-style APIs would not break so that old code worked https://2sxc.org/en/blog/post/bye-jquery-go-fetch-2sxc-12-10
