### ISSUE TITLE
Oqtane - JsonIgnoreAttribute in System.Text.Json v8 and v9

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3510]
### I'm submitting a
[x] bug report

### ...about
[x] Razor templating
[x] other / unknown

### Current Behavior / Expected Behavior
One app is reporting this error (among others) in Oqtane.
I did a quick search on the file contents of the app and there is no use of System.Text.Json apparently.

`CS0433: The type 'JsonIgnoreAttribute' exists in both 'System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' `

### Your environment
* **2sxc version(s):** 18.04
* **Oqtane:** 6.0
* **Hosting platform:** IIS

**Comment by iJungleboy** [comment]
did you update an Oqtane from v5 or start new with v6?

**Comment by enfJoao** [comment]
Updated from v5.

**Comment by iJungleboy** [comment]
I suspected as much.

So my guess is that your refs folder - which contains a bunch of interfaces for the compiler - contains both v8 and v9 refs.

There were similar problems going from .net 7 to 8.

.net core tries to break apart it's system into smaller and smaller chunks, and because of that sometimes the file names change.

Pls try to flush your refs and replace it's contents with the refs of a new / clean oqtane install.

**Comment by enfJoao** [comment]
And my refs folder matches a clean install one.

**Comment by enfJoao** [comment]
But theres is a System.Text.Json.dll (v8) in the root folder.

**Comment by iJungleboy** [comment]
great. 
glad you fixed it and made an issue no Oqtane.
