### ISSUE TITLE
2sxc Oqtane stripping <script> attributes

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3532]
### I'm submitting a
[x] bug report 
[x] not sure

### ...about
[x] Razor templating
[x] JS development

### Current Behavior / Expected Behavior
All my <script> tags in Oqtane 2sxc apps are being sanitized / stripped of all attributes except for the src.

Example:
![image](https://github.com/user-attachments/assets/becf3143-3c1c-4288-8c94-076c1e3a9a9b)

renders

![image](https://github.com/user-attachments/assets/3e8553b2-f98f-4312-9dbf-d7fb240b9fbd)

This happens in all scripts in all 2sxc Oqtane apps.
It does not happen in Oqtane html modules.
It does not happen in DNN 2sxc apps.

### Your environment
* **2sxc version(s):** 19
* **Oqtane:** 6.01
* **Hosting platform:** IIS

**Comment by enfJoao** [comment]
Changing Oqtane render mode from static to interactive seems to solve this.

**Comment by iJungleboy** [comment]
@enfJoao 2sxc must do some processing and remove/re-add the scripts in some render modes. 

Just for our understanding to see if we should address this: Why would you add these additional attributes?

**Comment by enfJoao** [comment]
Two objectives:
1. Move all inline scripts to external files. SPA is a pain to manage with scripts on the template.
2. Reuse scripts with variables changing. Inagine a page with 20 charts using an external library (charts js for example). They all share the same base, but different title and data. These data attributes do the trick very well.

**Comment by enfJoao** [comment]
Here's a clear example on the use case.
This code would repeat over 20 times in a page with different title, data, colors, etc:

```
    <div class="chart-container-slick">
        <canvas id="uChart" class="canvasChart"></canvas>
    </div>

    <script>
        var ctx = document.getElementById('uChart').getContext('2d');
        var ageRangeChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(uLocationGrouped.Select(ar => ar.location))),
                datasets: [{
                    label: 'Chart title',
                    data: @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(uLocationGrouped.Select(ar => ar.locationCount))),
                    backgroundColor: 'blue',
                    barThickness: 20
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                    x: {
                        beginAtZero: true
                    },
                    y: {
                        beginAtZero: true,
                        ticks: {
                            stepSize: 1
                        }
                    }
                }
            }
        });
    </script>
```

Notice there is razor code in it and inline script.

I would like to do this:

barchart.js
```
let cid = document.currentScript.getAttribute('data-cid');
let clabels = document.currentScript.getAttribute('data-clabels'); 
let cdata = document.currentScript.getAttribute('data-cdata');
let ctitle = document.currentScript.getAttribute('data-ctitle');

var ctx = document.getElementById(cid).getContext('2d');
var ageRangeChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: JSON.parse(clabels),
        datasets: [{
            label: ctitle,
            data: JSON.parse(cdata),
            backgroundColor: 'blue',
            barThickness: 40
        }]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        scales: {
            x: {
                beginAtZero: true
            },
            y: {
                beginAtZero: true,
                ticks: {
                    stepSize: 1
                }
            }
        }
    }
});
```

template.cshtml
```
<div class="chart-container-slick">
    <canvas id="uChart" class="canvasChart"></canvas>
</div>
<script
    data-cid='uChart'
    data-ctitle='Chart title'
    data-clabels='@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(uLocationGrouped.Select(ar => ar.location)))'
    data-cdata='@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(uLocationGrouped.Select(ar => ar.locationCount)))'
    src='@App.Folder.Url/charts/barchart.js'>
</script>
```

**Comment by iJungleboy** [comment]
@enfJoao I guess your basic idea makes sense. 
To be honest, I really like the `currentScript` trick. 

Problem is that Blazor causes a lot of _very different_ problems with all kinds of variations of render modes and JavaScripts. We're talking about things such as

* Timing problems
* multiple executions
* unreliable first executions

In addition to this, whatever seems to work now could result in it not working in a future scenario, because of ongoing Blazor and Oqtane changes.

To compensate for all these variations, we are forced to rewrite how the JS is actually added to the browser, and the mechanisms vary for each render mode :(. And we're forced to update the mechanism for each release. 

For example, in some modes we're forced to use a JavaScript module loader to actually get the scripts to load, which could have a script tag, and some day may not have such a tag any more since it could use custom Elements and other tricks.

So we're kind of forced to restrict ourselves to what scenarios we support, and these must be scenarios we believe we can compensate for no matter how Blazor & Oqtane change. Our current strategy:

* prefer turnOn for everything
* `<script>` tags are supported in the basic implementation and _should_ always work.

Your cool implementation is beyond what we believe can be kept stable in the long term, so we cannot support it from inside 2sxc  - sorry :(.

Because of this, your only stable variation is to change what you're doing to use turnOn. That's safe - and will even survive future hardening such as proper CSP support. So I'll close this as won't-do.

**Comment by enfJoao** [comment]
I understant what you mean.

Here's 2 cents on what I could gather on 2sxc and Oqtane with a couple months testing.

For DNN, 2sxc adds a lot of desired functionality. Everything we need to do with content and apps, we can do it in 2sxc with advanced skills whatsoever. It's a know dead end road, however (even if it's more than 10 years from now).

For Oqtane, 2sxc restricts more than it adds. Even the community acts very aggressively towards 2sxc when asking question and saying there are obvious solutions for the problems within Blazor (server and browser), so why bother with this "addon"? Also, it seems that Oqtane is years away from a stable solution. Each step brings more problems than it solves. Blazing new techs in the corner and very few people to test it.

For now I will definitly stick with DNN. Things just work.

**Comment by iJungleboy** [comment]
@enfJoao I understand your pain.

For us we also believe that Blazor is the future, but it's not the present - at least not for web sites.

Too many strange things, and every new feature which should make things more normal (e.g. the rendering modes) introduces new problems - one step forward, one backwards.

So we are dedicated to invest into it, but cautious when using it in production.
So far 99% of our solutions are still DNN and until Oqtane has proper multi-language it will stay this way. 

But we believe in it in the long run. But if DNN picks up speed (there are some people in the community doing some really crazy 💩 in the background, making DNN closer and closer to .net core), it could actually achieve technical parity within 24 months or so, ...
