### ISSUE TITLE
drop-down menus are still gone in 8.00.02

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#409]
Problem in 8.00.02 is not fixed. Still the same issue
drop-down menus are still gone.
![puldows gone](https://cloud.githubusercontent.com/assets/13934402/10775255/211d6474-7d07-11e5-869e-d434b6fcdeb8.jpg)

![drop-down](https://cloud.githubusercontent.com/assets/13934402/10775332/b9caf538-7d07-11e5-865a-bf17af308065.jpg)

**Comment by iJungleboy** [comment]
This looks like a bug, sorry :(. Will look into it. Am currently in the way to Japan so it may take a few days.

**Comment by joshgk00** [comment]
I was trying to add a list of the Font Awesome classes as values to the dropdown, but in 8.00.02 the names show on a single line and don't show in the dropdown either. I'm guessing this issue is related

![image](https://cloud.githubusercontent.com/assets/13650025/10808440/c52a8866-7dc1-11e5-88a4-19a3f3fb3b12.png)

**Comment by ech01** [comment]
Same here, also possibly related is that after upgrading to 8.00.2 you cannot add values to the drop down. Text says to put values on separate lines, but the input is a single line text box
![no dropdown](https://cloud.githubusercontent.com/assets/3790873/10831065/4d13eb16-7e51-11e5-80a1-a95e54f8402a.jpg)

**Comment by raphael-m** [comment]
Fixed in 08.00.03
