### ISSUE TITLE
Click on "browse" in ADAM should only open browse 1x

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#438]
As of now, it seems that having multipe adam-items in a dialog will cause as many browse to open as there are adam-upload items. Should of course only open once.

**Comment by reaxx999** [comment]
For one of our customers this bug is really annoying, because in some cases there is more than 1 image field (+ hyperlink field, which also opens dialog field incause of https://github.com/2sic/2sxc/issues/455, so the customer gets about 4 dialog field on one specific content type). 

Plus: the dialog fields are opening in Firefox in reverse order, so this is really confusing.

If this could be prioritized higher (and fixed sooner) the customer and I would really appreciate it :)
