### ISSUE TITLE
Converted dropdown lists not visible in General Settings 

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#442]
An converted drop-down list is not visible in general settings, so you can't change the Dropdown Values .
A new dropdown list made in 8.0.4 is visible

All the dropdownlists can be used in the end-user edit pop-ups. On that place they are visible
![bug-drop-downs](https://cloud.githubusercontent.com/assets/13934402/11183050/c9a6878e-8c6f-11e5-95d4-f9d8e90b80f6.jpg)

**Comment by iJungleboy** [comment]
This is "by design" because the field configuration used to be very string specific and is now input-type specific. To work around the design change, everything uses the old settings till they are overridden with new settings which are made manually.

If you want to see the old settings just go into advanced/debug mode by ctrl-clicking in the edit dialog.
