### ISSUE TITLE
Plus icon to Add a View does not work with ie11 

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#447]
Administration -> Views -> Add works with Firefox and Chrome, not ie11
http://dnndev.me/Page2sic/Page1/mid/1408/ctl/edittemplate/appid/1002?popUp=true

![capture](https://cloud.githubusercontent.com/assets/5261858/11220774/c869b88a-8d61-11e5-8d23-0f617f77eea1.JPG)

**Comment by BravoSierra** [comment]
![capture](https://cloud.githubusercontent.com/assets/5261858/11221015/1edae0f8-8d63-11e5-8d82-ee6522b91acd.JPG)

**Comment by iJungleboy** [comment]
could you check again if it's a popup-blocker issue?

**Comment by iJungleboy** [comment]
So the problem could be the promiseWindow, but it could also be something else. We'll have to check.
IF it's the promise window, I see two solutions
1. Get rid of old dialogs so we don't need the promise window (lots of work)
2. Show an info that this fails in IE (not nice, but quick and effective)

Since 1. will take some more time (there are approx. 4 dialogs which still need the promise window) we have to do 2. first to ensure users can continue their work, then focus on replacing the remaining dialogs...

Todo
1. Check if it's the promise window, and/or if it's a security issue, or if an update of the promise window would fix everything...

**Comment by iJungleboy** [comment]
I was able to reproduce it. The PromiseWindow plugin tries to create a promise object and checks if the browser supports promises 
if(root.Promise)...
If not, it tries various other things like jQuery etc. probably chrome supports promises by default, the others don't - so it fails. I have to either
1. update promisewindow to try angular promises 
2. add an object to window to simulate browser-promise capabilities
3. get rid of the promisewindow plugin

I'll first try to persue 2 or 3...

**Comment by iJungleboy** [comment]
It looks like it would also support Q promises, I'll check if it's enough to include that library...
