### ISSUE TITLE
"App Razor Codes" does not appear

### ISSUE THREAD

**Issue by S-Staab** [2sic/2sxc#501]
I bulid a new app and want to use the "App Razor Codes", but they does not appear.

2sxc V. 8.0.7 / Dnn V. 07.04.02 

![toolbar](https://cloud.githubusercontent.com/assets/14276625/11533444/06fd0b70-990a-11e5-9132-b8b8e0e955ce.png)

**Comment by iJungleboy** [comment]
So you mean you are missing them in the examples? Or you are using them, and they don't work (like @App.Path) ?

**Comment by S-Staab** [comment]
I using them and they don't appear. (No error)

**Comment by iJungleboy** [comment]
Note that the two tags you are using could both be blank in many scenarios - not returning anything. For example, if there is no content, there is no toolbar for it. And if the Resources don't have a Title, this too would be blank. Could you check that this is not the cause? 

Please try the following tags to verify that they work (or don't)

1. @App.Path
2. @App.AppPath
3. @App.Name
4. @App.Folder

**Comment by S-Staab** [comment]
Of course the contents have to exist. I have check this yes :)

The tags exist :/ 
Ok i must check my content....
 
But why don't the toolbar work ?

**Comment by iJungleboy** [comment]
Content.Toolbar works when there is content - either when there is added content OR if the content it shows is demo-content (from the demo-item). If neither exists, then the Content-Variable is empty and also doesn't offer a toolbar. This is by design - if you want to show something before the user edits his content, you should really specify a demo-entity.
