### ISSUE TITLE
New templates do not show up if you want to change de layout template

### ISSUE THREAD

**Issue by KosVos37** [2sic/2sxc#505]
If I create a template in 2sxc7 in my developent environment and FTP it to the acceptance/production environment, the template appears in the admin/template(views) popup if you click on the change template button. In 2sxc8 it does not show up even not after refresh/clear Cache and restart appdomain. The way to go is to create a new template and paste the new template code. What I want is to switch and switch back with just by changing the underlinging template and not the template definition

**Comment by iJungleboy** [comment]
@KosVos37 could you do some more tests, because this is a very common dev scenario and you're the first to report it broken. Does it only happen on FTP? Are you sure you're replacing the correct file? What steps would you take, to then make it take the new template (do you have to restart something, clear cache...?)

**Comment by KosVos37** [comment]
Hi iJungleboy, I reinstalled 2sxc and now this works fine. After compare with my local version I had version 4.1 of the EAV.dll instead of 4.2 but the correct 8.0.4 of ToSic.SexyContent. I know I can update now to 8.0.8. Sorry for the inconvenience.
