### ISSUE TITLE
Request: Authorisation on Fields of Content-Types

### ISSUE THREAD

**Issue by KosVos37** [2sic/2sxc#551]
In 2sxc there is one role "2sxc designers" that allows designers to change all content and presentation of content-types. What we want is an authorisation layer that consist at least out of 2 roles. These roles are:
1.  "2sxc designers" -> designers that are allowed to modify a configurable subset of the fields
2. "Administrators" -> Allowed to set all fields
A better solution would be if two levels of designers roles do exists  ( or, more difficult, configurable ).
The reason that we want to protect some fields is that if a static number of fields are not set in template or have some wrong values the Template will not render correctly.

**Comment by iJungleboy** [comment]
The current situation has an important background: very often the site owners (the customers of the web designers) will have admin permissions as this is needed for certain actions like page management and user management. 

But these admin-users should NOT manage 2sxc, as there are too many options and it confuses them. because of this, normal admins are regarded as content-admins, not 2sxc-admins. So admins cannot have full edit-fields permissions, this is the function of the 2sxc designers. We could have also called it 2sxc-admins. 

Now from what I understand is you would like to have ANOTHER group. But based on your description I can't figure out what they should do. Could you explain with a real life example?

**Comment by Frankwalraven** [comment]
There are site designers (2sxc administrators) and normal content editors. We want to have templates with many fields for site designers, so they can easily format and make nice layouts by choosing options for content on the webpage (including options for responsive design and specific content items etc.) without HTML or CSS programming. 
Also some fields have content, but are more advanced. So many fields are not meant for normal content editors and these fields can confuse them, so we want to hide them for content editors. 

Therefore, we would like that fields can be authorized for content editors. So for example an administrator sees 20 fields when he wants to edit a content item and a normal content editor sees only 6 fields when he edit a content item.

**Comment by iJungleboy** [comment]
So what you would like is field-level permissions, where each field could have a edit/show permission based on roles, is that correct?

And if I understand you correctly, this isn't security relevant, it's more a UI thing to make the UI easier.

**Comment by Frankwalraven** [comment]
yep

**Comment by iJungleboy** [comment]
At the moment this is not on our pipeline. It's technically feasible, but fairly complex so both the initial implementation and follow up support would cost too many resources. 

The simplest implementation would be to create a custom input-type - let's call it "empty-yourcompany-conditionalfields" which would not really be visible but check the groups a user is in and then show/hide the appropriate fields. 

That is fairly straight forward and the basic functionality could be done in a few hours once you've worked yourself into creating custom input fields. I've posted blogs about that once

1. http://2sxc.org/en/blog/post/custom-input-type-advanced-dynamic-data
2. http://2sxc.org/en/blog/post/configurable-custom-input-type-dynamic-data-content

**Comment by iJungleboy** [comment]
I'll close this for now, re-open (or find a sponsor :)
