### ISSUE TITLE
Question: TinyMCE as default RTE?

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#592]
Any plans to make tinyMCE also a generic DNN RTE? Including Adam?

**Comment by iJungleboy** [comment]
That's very, very hard to do, because ADAM needs a context to manage the assets. In our case it's 

1. Portal
2. App
3. Content-Item GUID
4. Field
5. Field-Type (in this case wysiwyg)

As a generic wysiwyg-editor, this is not available. Many features wouldn't work reliably without this, and even it would work temporarily, it would fail at a more advanced use-case like export/import, where you would get ID clashes. 

But IMHO this is not very important. The old webforms-style applications will die quickly, and modern razor/js apps will either be done as an App (to benefit from all other data-handling aspecs) or as SQL+WebApi+Front-End applications, which have very custom needs for the editor - and these usually don't need adam - or they need it in a different way. 

In general we hope that most simple apps will be implemented as 2sxc apps in the future, and save the developer lots of time + give app-users more customization possibilities than with an Module-style concept. 

So for now it's not on our radar and we wouldn't invest resources into it. Other are free to duplicate / try, but a generic use case is impossible to do without also controlling the data-layer, export/import, metadata assignment (also data-layer) etc.
