### ISSUE TITLE
ADAM-ImagePicker does not work in IE11 (v8.1.0 BETA)

### ISSUE THREAD

**Issue by reaxx999** [2sic/2sxc#594]
ADAM-ImagePicker opens, but selection of file has no effect. 
Drag&Drop still works fine.

Tested on IE11 on different websites with 2sxc v 8.0.1 BETA. 
Works on 8.0.12, does not work anymore on 8.1.0 BETA.

**Comment by iJungleboy** [comment]
Thx, will check

**Comment by iJungleboy** [comment]
Most functionality works as expected. tried selecting the file - it became active. The only case where I found a bug was

1. When I upload using the button instead of drag/drop
2. then the upload works, but the preview doesn't update, so you may think that the upload didn't happen.

Was this your issue?

**Comment by iJungleboy** [comment]
Figured it out - was an angular-digest-cycle issue, which apparently was a bit different in IE than chrome. Fixed.
