### ISSUE TITLE
List Presentation Settings standard collapsed

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#621]
Is it possible that List Presentation Settings are standard collapsed like it was. makes things direct clearer

**Comment by iJungleboy** [comment]
I'll have to think about that. Originally these were always collapsed, but we discovered that people would completely ignore this very important feature. I'll try to think of something...

**Comment by Frankwalraven** [comment]
It would be nice when there is a possibility (setting) to get them Standard collapsed. We have many presentation settings and their are only occasionally used. Now a user get a very long list of fields and this can be confusing

**Comment by iJungleboy** [comment]
The architecture makes this fairly difficult to implement in a clean way. A hacky way is easy, but that would cause trouble in the future. From what I see I could imagine a few ways.

Method 1: new option in eav + config + route setting

1. Extend the EAV-system to allow the opening link to specify not only the title of the section (like presentation) but also it's visibility
2. Extend the fields which define a view/template to also have an option "Collapse Presentation by Default"
3. Pass on that value through the entire chain of command

Method 2: extend a content-type definition to auto-collapse

1. Extend the EAV-System so that each content-type can have an additional option to be collapsed by default. This is fairly complex, because the content-type itself doesn't have any dynamic fields as of now, so this change would be rather extensive

Method 3: create a hidden field-type which causes this functionality

1. Create a new, custom "input-type" - called something like "empty-collapse-view" which by default isn't visible, but would affect the form to auto-collapse the section by default

Method 4: Enhance the title field-type

1. Extend the current "empty-title" input field (which already allows collapsing of many fields) with a collapse-by-default. This would have the effect that the presentation wouldn't be 100% collapsed, but would be reduced to 1 single line with that title field / instructions.

Method 5: automatically hide most of a disabled group

1. Change behavior of disabled entities to not just be grayed out, but also to have a fade-out of about 50-100 pixels.

What do you think? I would believe method 4 or 5 would be the best, both wouldn't actually hide everything, but almost everything. I think this would actually be beneficial because it still allows discoverability...

**Comment by Frankwalraven** [comment]
I think Methode 4 the single line option is perfect when its collapsed and it can set on all the title fields (discovered this field type now :-) didn't know it exist. )

**Comment by iJungleboy** [comment]
Care to sponsor it? About 2-3 hours work - http://2sxc.org/en/Contact

**Comment by Frankwalraven** [comment]
Later it will not be a problem. We are a start-up and our resources are scarce at this moment

**Comment by iJungleboy** [comment]
@Frankwalraven no problem - we all started that way. I won't prioritize this for now though, but anybody else wanting this badly enough is welcome to contribute cash or code to make it happen :)
