### ISSUE TITLE
DNN 7 Search Integration is broken for Apps

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#644]
None of my apps are getting indexed. I have requirements similar to the "Search for DNN 7 Integration Demo" demo and can't get it to work.

As RenderPage seams to be broken too, I have attached a modified demo. I can't get any item to be found by dnn search.
[_Main.cshtml.txt](https://github.com/2sic/2sxc/files/129870/_Main.cshtml.txt)

**Comment by SCullman** [comment]
Only Apps are affected, Content Modules are getting indexed.

**Comment by iJungleboy** [comment]
Thanks, we'll check...

**Comment by iJungleboy** [comment]
Note: in the next release 8.2.4 I've changed something in the DNN manifest which might be the cause. 

The release might also be called 8.3.0 because I refactored a lot of internal API and there is a risk that external templates accessing undocumented APIs might break. 

I would appreciate your feedback on this...

**Comment by SCullman** [comment]
I still don't get any search results from apps in 8.3.1

**Comment by iJungleboy** [comment]
ok, thx

**Comment by raphael-m** [comment]
Closed with be56f8ca9c76d08372e9b70c7c51e26c29ec4eb4
