### ISSUE TITLE
Error edit template settings in view tab

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#691]
I tested this also on different DNN sites and the issue occurs here also with the latest 2sxc 8 version
Maby its is a DNN redirect issue, like you had befor, while the templates settings still using webforms

Explanation
We have a site where the domainname alias of the site is
`bprvisie.com/projecten`

There is also a alias `www.bprvisie.com/projecten`
I added also an alias `bprvisie.com/pietjepuk`
and
projecten.bprvisie.com

From `projecten.bprvisie.com` I can always edit the template settings in the view tab. and it shows always
`http://projecten.bprvisie.com/Home/mid/646/ctl/edittemplate/appid/4/templateid/618?popUp=true`

The problem occurs when you go to a subdomain name like `bprvisie.com/projecten`

when I delete www.bprvisie.com/projecten and set `bprvisie.com/projecten` as primary domain I can go to
the template settings

When I go from the `bprvisie.com/pietjepuk` to the templates it uses not `/pietjepuk`, but the URL looks like
`http://bprvisie.com/projecten/Home/mid/646/ctl/edittemplate/appid/4/templateid/618?popUp=true`
It should be
`http://bprvisie.com/pietjepuk/Home/mid/646/ctl/edittemplate/appid/4/templateid/618?popUp=true`
So with pietjepuk in the URL

When I add the `www.bprvisie.com/projecten` again an go from this URL to the templates I get the folowing URL
`http://www.bprvisie.com/Default.aspx?tabid=55&mid=646&ctl=edittemplate&appid=4&popUp=true&templateid=618`
you get the error ERR_TOO_MANY_REDIRECTS

Now from all the url's, exept from `projecten.bprvisie.com` url I get the same wrong URL
When I go from bprvisie.com/projecten to the template settings I get

`http://www.bprvisie.com/Default.aspx?tabid=55&mid=646&ctl=edittemplate&appid=4&popUp=true&templateid=618`

and it should

`http://bprvisie.com/projecten/Home/mid/646/ctl/edittemplate/appid/4/templateid/618?popUp=true`
So with projecten in the URL

From `bprvisie.com/pietjepuk` I get
`http://www.bprvisie.com/Default.aspx?tabid=55&mid=646&ctl=edittemplate&appid=4&popUp=true&templateid=618`

and it should 

`http://bprvisie.com/pietjepuk/Home/mid/646/ctl/edittemplate/appid/4/templateid/618?popUp=true`
SO with pietjepuk in the URL

this problem occurs also in other sites when you uses subdomains like `website.com/subdomain`

With subdomains like `subdomain.website.com` everithing works well. Also when there are no subdomains used like `website.com/subdomain`

**Comment by iJungleboy** [comment]
This sounds like a DNN bug - dnn is very buggy in terms of urls; we've had loads of these issues in the past and they were always DNN-url bugs. 

Likely problems are

1. Missing configuration for the home (start) page
2. Missing configuration for the search page (not kidding - this can really mess up sporadically)
3. Inproper configuration for language-to-portal-alias setup
4. Special use-case on home; often the dialogs work when you're on a sub-page, but not when you're on home

Please review these things first and get back to us if you still think it's a 2sxc issue. 

I'll close this for now, because to 99% it's a DNN issue - and the dialog still uses webforms.
