### ISSUE TITLE
Find a way to trigger scripts after ajax preview reload

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#721]
Possible solution: Create custom **ready** events on the module wrapper like `2sxc-ready` or `2sxc-unload` that will trigger when the AJAX preview changes the HTML. This may become complex, but we would be able to solve the issues we have now.

https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

> Discuss

**Comment by iJungleboy** [comment]
If we study this, we should do a bit more

1. Define a way to enable / disable ajax reload (so that apps could also do ajax)
2. Define triggers like before-refresh, etc. - or alternate refreshes in case the ajax shouldn't load the entire block, but only let an angular-app load new data

**Comment by iJungleboy** [comment]
As just discussed, the best way is to include a simple re-init script in each template which needs it, then2sxc doesn't need to do anything special. 

Let's just recap the situation
1. When the content loads the normal way, it can be one or more modules requiring the same init. This init can be in an external JS being loaded onLoad with `$(function() {...})` - this will be the most common scenario
2. It could also be internal after each module, again with an on-load, which only loads this specific instance. That on-load would then need to know the module-id or something to make sure it only initializes itself. 
3. when loading through ajax, external JS isn't going to run an onLoad automatically, unless it somehow has a DOM-monitoring (which is unlikely). So on AJAX (which only happens when the user is editing) the content has to include some kind of JS to re-init itself
4. any JS in the ajaxed-content will initialize, so it can be a simple "re-init-all-galleries" or "init-galeries-which-are-not-initialized" or it can be specific a init-module-473, depending on developer preferences.

The important this is that this re-init does
1. either it explicitly addresses the current module (to not re-init other stuff on the page)
2. or it call a general-re-init, but that checks which parts had already been initialized
3. alternately the external script could add a live-watch with $.live or something, but I'm not sure if this will work

**Comment by iJungleboy** [comment]
Note that apps now support ajax too - see #807 
So this is mainly to define best practices, not directly related to this release.

**Comment by iJungleboy** [comment]
As this itself is done and it's more a documentation thing, I'll close this issue to replace it with a documentation issue #808
