### ISSUE TITLE
"Copying" a 2sxc module

### ISSUE THREAD

**Issue by jncraig** [2sic/2sxc#757]
When we copy an HTML module, we have the option of making the copy as a reference to an existing module, or copy the module with its content, but that content isn't linked to the original module.

Is it possible to do this with 2sxc?  How?

If not, could this be added to the roadmap?

**Comment by iJungleboy** [comment]
It depends on what you want. if you only want to copy an element, you can use the replace/copy function - very easy. 

If you want to duplicate a list of items, but copy the items, that feature doesn't exist like that. it would also be unclear how to integrate that into the UI, because dnn doesn't allow for further steps / dialogs in the copy process. So for now I'll close this. if you need the second scenario and have a good idea how to implement it, we're open for suggestions / contributions.
