### ISSUE TITLE
Source editor - content fields do not appear in the defined order

### ISSUE THREAD

**Issue by mcshorty** [2sic/2sxc#783]
Module version: 8.3.7
DNN version: 7.4.2

In the source editor the defined content fields are sorted by name - expected is the defined order?

**Comment by iJungleboy** [comment]
This is by design - I don't think we would want to change this. 

If you would like to contribute a optional-sort function, you can do that, but we wouldn't invest any resources into this.

**Comment by mcshorty** [comment]
I thought this could be an unexpected behaviour - but sorry for my question - if you say "by design", what is the reason to show another sorting in the Source editor than in the Content type editor - and there is an explicit sort order? Normally the fields have a contextual dependency, and thats why the sort makes sense... 
Just a note from me, no answer necessary.

**Comment by iJungleboy** [comment]
@mcshorty no problem - always glad to help. 
As of now, it's by design as it's the simplest clear solution to catalog the fields in abc-order. But it's basically just some angular-js that does the sorting, so if there is a benefit in the other sorting (and you could invest the time to create it) we're open for contributions :)
