### ISSUE TITLE
Feature Request: Global configuration

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#847]
It would be great to be able to turn on/off 2sxc features that may not be wanted or needed.

- Adam (choose globally to use adam or core dnn file manager)
- The new quick insert feature (checkbox to enable)

While we appreciate the awesome innovations and agree on the direction, sometimes the changes can confuse content authors, necessitating retraining. Plus, it is inconsistent with other modules and DNN the core, which fractures the overall admin experience. Like I said, the above features are great, but might not be suitable for everyone. Leaving them on by default would be fine, but with the ability to override

Thank you for your consideration.

**Comment by iJungleboy** [comment]
This is a very complex topic - which is why we haven't touched it so far. Complexities include

* Scope of this "global" configuration - per host, per portal, per app, per content-type, per field, per instance (aka Module), per whatever-may-come
* Based on the scope, who is allowed to set it
* consistency across configuration types - some types are like yes-no switches for a field, others are like internal stuff (like TinyMCE settings, which are a mix between json-switches and code/events)
* what we really want to avoid is creating another settings-system, which is always behind implementation - so when tinymce would add a setting, we don't want to have to extend our "settings" system just for that
* more..

So we know of this need, but we don't want to touch it till we have a comprehensive, consistent solution that will stand the test of time, because everything else will place a huge burden in terms of compatibility down the road. 

So ATM it's low priority, not because it's not important, but because it's so difficult and mistakes are "expensive". What are your thoughts? Would you care to develop a rough concept highlighting all the possible things that must be considered and how this could be handled in a good way?

**Comment by ech01** [comment]
The point is you are adding features without letting the user decide whether they want them or not. You have essentially built a CMS within a CMS, which is not a great user experience IMO. Having two ways to manage images (core and adam) is unnecessary and confusing if you have an existing dnn site that was built utilizing the core file management system. And for the quick insert, that doubles up on functionality that is present in evoq.  

At least you have the option to use tinymce or dnn default editor(I choose tinymce 99% of the time) for fields. So precedent exists within 2sxc. For adam and quick insert, I think it would be an all or nothing approach: either you use them consistently or not.

**Comment by mryckman** [comment]
I would like to see something like this as well. I'd echo the above comment: 2sxc is very powerful and innovative and is developed very actively - all of which is awesome. But, my biggest holdup with it has been the disconnect between 2sxc and DNN. It feels like 2sxc avoids DNN when possible: security/permissions; file management; text editors; UI paterns; etc. In most of those cases, Daniel has made decent arguments for taking the path they did, but in the aggregate, it does feel like another CMS that sits atop DNN. 

With that said, I don't think central settings are the answer, actually... specifically because it ignores the DNN module pattern. The "quick add" feature should be a module setting (and I'd default to it being off). The "use adam" option should be an option on file fields (just like the text editor). In normal DNN, that's where you'd expect to find those options. For adam, I just think it needs more field-level settings for the file storage location.

I would also appreciate more use of module permissions. It would be great if 2sxc added module permissions for things like "Add Record", "Delete Record", "Update Record", "Update Own Record", "Delete Own Record". You could also do permissions at the entity level, but they should also be available at the module level. 

That's my two cents on this... And again, thank you to Daniel and the team for the ongoing development.

**Comment by iJungleboy** [comment]
In general I agree with much of what you say. The main issue is just limited resources. Adding such settings needs a lot of planning to do right - and if we skip that, we'll need a lot of resources in the future to work around things we didn't do right today. So the main reason we're delaying too many settings is because the entire concept of settings management has not been created - slowing down implementing any settings. 

BTW: add/delete etc. already exists - at content-type level :) but it only affects the REST API, which is the right place for it because if you have non-editors editing stuff, you'll usually want to create a custom form for that.

**Comment by mryckman** [comment]
I definitely understand about the resources. But, the add module popup thing is a great example, honestly, of something I wouldn't have spent the resources to create without having the settings to disable it. The trouble is that you're essentially replacing a core feature of DNN - I could just use "Add Module."  Your "Add Module" replacement might be convenient, but I it doesn't let me add any modules... just 2sxc modules. The overwhelming majority of users probably wouldn't want that as they're likely to only have one or two 2sxc modules on a page... and, hopefully, once those modules are added, the content itself is being managed by 2sxc.

As for the security stuff... I think it's good to have that at the content level, but it also really needs to be at the module level, in my opinion. Consider this case:

I create a content type "Resource" that is designed for our intranet to allow different departments to post files (accounting posting our tax form, or HR posting a benefits sheet, etc.). In each department, I want to allow members of that department to add/change records in their module, but not in the modules for other departments. All of the modules use the exact same design/template/content type. 

So, I create my content type, I create my template... but where do I set the permissions? Everything about 2sxc makes the first steps super easy - and, if I want, I can even export that content type to allow other DNN users the ability to completely replace the old "Repository" module with 2sxc. But, I can't make it easy to just have HR staff be able to edit the "HR Resources" module, without also making them editors of the module itself and thus adding a lot of confusion - or the ability for them to change stuff I don't want them to change.

I think having more settings and options at the module level would enable 2sxc to really jump to the next level in it's usability in the DNN community...

That's just my two cents on this - and again, thanks for your work and your responsiveness here.

**Comment by iJungleboy** [comment]
@mryckman about the security: I'm not sure what you are having trouble with, because you can use module level security for most things - so I'm not sure what you're stuck on. By default, users that have edit rights can edit the data - so a "HR can edit this list shown here" is trivial. And it's also easy to open the REST api to allow "users who have edit rights on the module may edit this content-type".

So your wish is probably about something else. Could you elaborate?

**Comment by mryckman** [comment]
Thanks Daniel... See, the problem I'm having is that there's a huge difference between "Edit" on a module and wanting people to be able to edit content in 2sxc. If a user has edit rights on a module, they can delete it, change settings, etc. Also, their interface looks different and a little more confusing. If I could just give them the ability to manage content in 2sxc, then I could make their experience much easier. Particularly for simply list content, that's often much nicer. 

It would just be nice to be able to give somebody the ability to add/change records in 2sxc without giving them full rights to edit the module. I believe Form and List does that, for example.

**Comment by iJungleboy** [comment]
@mryckman as of now you would do that with creating an own view / dialog to do that. It's a bit of work but can be done.

**Comment by mryckman** [comment]
@ech01 if it helps, we didn't have any use case for the "quick insert" thing and it kept causing problems because people were accidentally adding modules - I think I deleted like 12 this week. This css added to your portal file fixes it... though it's annoying knowing the js is still running:

.sc-content-block-menu {
display:none !important;
}
.sc-cb-highlight-for-insert {
background-color:inherit !important;
}

**Comment by iJungleboy** [comment]
This issue drifted off topic, so I created a new one describing the basic issues, problems and estimating time to implement - #919. 
I'll close this issue now.
