### ISSUE TITLE
Feature request: switch on/off auto module-title

### ISSUE THREAD

**Issue by trouble2** [2sic/2sxc#864]
When a user edit's an item in a module, the module title automatically is modified to the title of the item.
In some cases this is something you don't want.
So perhaps you can add some way of preventing this.

**Comment by iJungleboy** [comment]
I understand the need but I'm not sure how this could be provided in a way that the UX works. Could you give us 1-2 user stories where this would be helpful?

**Comment by trouble2** [comment]
Well, we have this site which is in development and it uses 2sxc for managing the locations:

http://Su.bondtest.nl

So when you go to a page for a location like this:
http://su.bondtest.nl/Spelenderwijs-locaties/Best-Practice/Welkom

There are several 2sxc modules which show parts of the content for 1 location record.
So the titles would be something like “Opening hourd” or “Information for parents”.
However when you edit the items in the modules they get changed to the title of the location.

Marnix Bouwman
[cid:image006.png@01D0344A.F84A7D80]bond for web solutions

Van: iJungleboy [mailto:notifications@github.com]
Verzonden: vrijdag 10 juni 2016 10:33
Aan: 2sic/2sxc <2sxc@noreply.github.com>
CC: Marnix Bouwman <marnixbouwman@bondforwebsolutions.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [2sic/2sxc] Feature request: switch on/off auto module-title (#864)


I understand the need but I'm not sure how this could be provided in a way that the UX works. Could you give us 1-2 user stories where this would be helpful?

**Comment by iJungleboy** [comment]
Ok, got it. So the core issue in this case is actually

1. You are sharing content-items
2. Sometimes you're only showing an extract (like opening hours)
3. In those cases, the title doesn't really make sense

Correct?

**Comment by iJungleboy** [comment]
In this case I would recommend the following:

Create a Content-type which is for showing the extracts, a bit like

1. Title
2. Location (the entity of the other information)
3. Show (a dropdown showing values like "opening-hours", ...)

Then create a view for this, which will of course show the title, and based on "show" choose which sub-template to use (if/then or with external templates Render(...)), and use the referred entity (Location) for that template.

Sounds about right...

**Comment by mryckman** [comment]
I have the same problem. When using a list template (which is most of what we use 2sxy for, changing the module title is counter-intuitive. I would almost always prefer the module keep the same title. As an example, I have a table where selected users can add/remove items from that table, I certainly would not want the title of the module changing. So, for now, I've just hard coded the title into the template. 

I would think that an easy solution is to add a module setting for that kind of thing that would be handled through DNN's traditional module settings. That would also be a good place to enable/disable the "add module" popup.

**Comment by iJungleboy** [comment]
I understand your issues so the next recommendation isn't meant to say the setting wouldn't make sense - it's more that I'm not quite sure how to make the setting "right". 

We never run into the issue, because we never show the module title and exclusively use it for identifying the module when copying or in the trash bin or something. We found that in designed web sites, the entire container-concept doesn't really work and is a kind of a leftover of the everything-is-boxed times which nowadays is never the case any more. 

So as a best practice we completely ignore the module title in our projects and never show it, as our default container never shows a title. I recommend you give this way of working a thought, because it solves many other problems at the same time.

**Comment by mryckman** [comment]
Thanks Daniel...

Respectfully, I think that's a great example of the connection between 2sxc and DNN. Even if you don't use module titles, most DNN sites do. I think it really ends up hurting 2sxc when the DNN content models get ignored that way. Personally, I would disable the module title changes... Here's why:

Consider the case where you want the title to change... Here, you have multiple answers, with the most intuitive being that you could hard code a "title" into the template/script and then just use "Hide Container" in the module settings.

But, consider the case where you don't want it to change... Now, you have to hide the container - you have no choice but to break a DNN default. Next, you have two choices: First, you could hard code the title into the template, but then you need to have different templates for every single module. Alternatively, you can just add the title to the "Module Header" block in the module settings. This works, but then you're just making a far more complicated way of achieving a core task in DNN because 2sxc breaks the standard. 

So, personally, I would just default to never changing the title and then think about adding a module setting that says "set title based on last record updated" or something.

**Comment by iJungleboy** [comment]
@mryckman the never-change-title can never be the default for various reasons. As it happens, the title-update functionality was broken for a few subversions (I think 8.2-8.3) and that cause many, many issues because all 2sxc modules then were just called "Content" or "App" - so whenever you wanted to copy/move/undelete a module it was really, really difficult. 

In reality if this is to be addressed, it needs the setting at various levels incl. site-level and portal level for various peoples preferences. Which of course adds new complexity and new surprises to people setting it one way today and discovering long term issues with the setting down the road (like the "can't find it in the undelete" issue). Just adding the setting will solve a quick issue, but create new ones requiring support and confusing users. 

This is why it should only be implemented after really thinking it through - so it's fairly resource intensive to do right. That's why it's not on our priorities right now.

**Comment by mryckman** [comment]
Thanks Daniel... I certainly see what you're saying... But I guess my thought is that that's always how it works with DNN for every other module. Site admins should be used to changing module titles... If they didn't, then every single HTML module would be called "Text/HTML." I'm not sure why people would expect 2sxc to behave differently - perhaps other than history. If that history is a concern - which is certainly fair, then I'd just default the module setting to be "true" that it should change the title with the stuff. 

I still wouldn't see why this would need to ever have a setting beyond the module level - it's a module level behavior.

But yeah, I think that's broadly the request with this stuff - to make 2sxc behave more like other DNN modules and the DNN standards... It's a hugely powerful module and you guys really do a great job with it - I just think those things would help it a lot.

**Comment by iJungleboy** [comment]
Moving this to the "closed but not implemented yet till sponsor appears" milestone.
