### ISSUE TITLE
Script (in the skin) does not load after saving content

### ISSUE THREAD

**Issue by thomassen88** [2sic/2sxc#866]
Hi, i have made an 2sxc-template with a "equal-height"-script from a script loaded in the skin. everytime i save a content in 2sxc the equal-height-script stops working.
i think it has something with the no-loading script in 2sxc. has anyone else experienced this?

**Take a look at this screenshots:**
Before editing/saving content: http://s31.postimg.org/6vwdbqj2z/before_2sxc_save.png
After: http://s31.postimg.org/67ofvji8r/after_2sxc_save.png

**Comment by iJungleboy** [comment]
This is an ajax issue. Your content is reloaded using ajax, and after that loading the equal-height isn't triggered automatically because you probably have it onload or something. 

So you can fix it yourself by ensuring your equal-height runs again. I wrote a very extensive paper on this topic here http://2sxc.org/en/blog/post/3-steps-to-ajax-enable-dnn-apps-modules-and-spa-200-400

**Comment by iJungleboy** [comment]
BTW: user questions are best posted on stackoverflow - http://2sxc.org/en/blog/post/moving-discussions-from-codeplex-to-stack-overflow because that way others can benefit as well. 

If it then turns out to be a 2sxc issue, then it should be opened here.

**Comment by thomassen88** [comment]
Thank you! sorry, i forgot to check out the website before i posted this. i didnt know you about the stack-overflow group. Thank you for fast reply ;)
