### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by kumardhiman** [2sic/2sxc#910]
Hi

I am trying to install the latest version of your package on to DNN 8 and Azure SQL but I get the following error message.

`

> SQL Execution resulted in following Exceptions: System.Data.SqlClient.SqlException (0x80131904): Your SQL installation is non-standard using a Custom Object Qualifier. 2sic uses the standard Microsoft Entity Framework which doesn't work well with this feature - installation aborted. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:506a41b2-cab8-424a-93b0-658e3a5a150b Error Number:50000,State:1,Class:16 ClientConnectionId before routing:d65af537-fed9-4258-8e79-14933a524406 Routing Destination:b5d5460976e7.tr6.westeurope1-a.worker.database.windows.net,11002 -- Check for custom Object Qualifier - break installation if it's configured (2sxc does not support object qualifier) IF 'dnn_' <> '' BEGIN RAISERROR(N'Your SQL installation is non-standard using a Custom Object Qualifier. 2sic uses the standard Microsoft Entity Framework which doesn''t work well with this feature - installation aborted.', 16, 1) RETURN END -- Script Block for 2SexyContent 05.05.00 Update -- --------------------------------------------- -- This SQL Script Block must be included in every .SqlDataProvider file -- for 2SexyContent <= 05.05.00 because of the rename of the internal -- module name. It does not have to be included for newer SQL scripts. -- This script changes the module name and the breaks the installation -- so the DNN cache is refreshed. After the upgrade is triggered again, -- the installation works. DECLARE @IsUpgradeFromPreviousVersion int SELECT @IsUpgradeFromPreviousVersion = CASE WHEN EXISTS(SELECT * FROM DesktopModules WHERE ModuleName = N'2SexyContent') THEN CAST (1 AS BIT) ELSE CAST (0 AS BIT) END If @IsUpgradeFromPreviousVersion = 1 BEGIN UPDATE DesktopModules SET ModuleName = N'2sxc' WHERE (ModuleName = N'2SexyContent') RAISERROR(N'Please run this upgrade again to finish the process. This is a necessary step because of the internal rename of the 2SexyContent module. ************************************************************************************************************************************************************************** PLEASE RUN THIS UPGRADE AGAIN TO FINISH THE PROCESS. This is a necessary step because of the internal rename of the 2SexyContent module. **************************************************************************************************************************************************************************', 16, 1) RETURN END -- End of the Script Block for 2SexyContent 05.05.00 Update

`

Please advice.

**Comment by iJungleboy** [comment]
Your DNN setup is non-standard, meaning you chose a customized object qualifier when you installed your DNN. See http://mitchelsellers.com/blogs/2010/03/23/the-dotnetnuke-object-qualifier-why-i-think-it-is-evil.aspx as a reference. 2sxc needs the standard setup for various reasons.

**Comment by GusBeare** [comment]
I'm having this same issue but I didn't use an object qualifier I never do??  Any ideas?
Is this a false error?  Seems to be a datetime conversion error but lower down it's reporting Object qualifier error?

SQL Execution resulted in following Exceptions: System.Data.SqlClient.SqlException (0x80131904): The conversion of a nvarchar data type to a datetime data type resulted in an out-of-range value. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:95f6c2dd-e653-43a2-9223-62994388a99d Error Number:242,State:3,Class:16 -- Check for custom Object Qualifier - break installation if it's configured (2sxc does not support object qualifier) IF '' <> '' BEGIN RAISERROR(N'Your SQL installation is non-standard using a Custom Object Qualifier. 2sic uses the standard Microsoft Entity Framework which doesn''t work well with this feature - installation aborted.', 16, 1) RETURN END -- Script Block for 2SexyContent 05.05.00 Update -- --------------------------------------------- -- This SQL Script Block must be included in every .SqlDataProvider file -- for 2SexyContent <= 05.05.00 because of the rename of the internal -- module name. It does not have to be included for newer SQL scripts. -- This script changes the module name and the breaks the installation -- so the DNN cache is refreshed. After the upgrade is triggered again,

**Comment by GusBeare** [comment]
I tried this on another 7.4.2 instance I have locally and got the same error.

**Comment by iJungleboy** [comment]
@GusBeare You are experiencing a different issue than the one described above. Are you doing an update or a new install?

**Comment by GusBeare** [comment]
New install. I've tried DNN 7, 8 and 9. Same error.   Could this be a date format/config issue in SQL Server?

**Comment by iJungleboy** [comment]
@GusBeare We've never encountered this, so I don't know. Do you use a special format/config in your system? Were you also installing the latest 2sxc (8.11) or an older version?

**Comment by GusBeare** [comment]
hmm.. don't think there is anything special about my setup. SQl Server 2012 developer edition with mostly default config I think.  Yes, I tried to install the latest version of 2sxc: 8.11.  I think the error is happening during an insert when this script is executed:  00.99.00.SqlDataProvider.

Sometimes collation can cause these issues. I have it set to:  Latin1_General_CI_AS and I have the language set to "British English".

Could the British English be causing a date error?

**Comment by GusBeare** [comment]
It could be this:

http://stackoverflow.com/questions/10818796/error-converting-string-to-datetime-due-to-locale

But my DNN user has default lang set to British English which is same as the server default.

**Comment by GusBeare** [comment]
Your scripts are doing stuff like this:

 CAST(N''2017-02-20 15:28:27.697''

Perhaps should explicitly define the date format on your convert?  e.g.

SELECT CONVERT(DATETIME,'2012-12-31',120)

**Comment by iJungleboy** [comment]
@GusBeare thanks for the research. 
@raphael-m will look into it.

**Comment by GusBeare** [comment]
thanks. I tried setting my DNN database to English language but the install still failed with the same error.

SQL Execution resulted in following Exceptions: System.Data.SqlClient.SqlException (0x80131904): The conversion of a nvarchar data type to a datetime data type resulted in an out-of-range value. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:faac44c3-fcc5-48a9-9c20-830c015325fc Error Number:242,State:3,Class:16 -- Check for custom O

**Comment by raphael-m** [comment]
@GusBeare please run the following SQL queries separately and let me know which of them worked and which did not:

```
SELECT CAST(N'2012-05-02 08:31:35.297' AS DateTime)
```
```
SET LANGUAGE English
SELECT CAST(N'2012-05-02 08:31:35.297' AS DateTime)
```
```
SELECT CONVERT(DATETIME, N'2012-05-02 08:31:35.297', 121)
```

**Comment by GusBeare** [comment]
thanks @raphael-m 

they all worked!

**Comment by raphael-m** [comment]
Well that's strange, I expected the first one to fail (that's where the installation seemed to fail in your case). Is the language still set to English? Please try changing the language to what was set before, then preventively restart SQL server and try to run the queries again.

**Comment by GusBeare** [comment]
Hi I set it back but it still works.

However, this will work in all cases because it doesn't matter which way round you have the month and day it will always be a valid date:

SELECT CAST(N'2012-05-02 08:31:35.297' AS DateTime)

This this also works:

SELECT CAST(N'2012-20-02 08:31:35.297' AS DateTime)

But this fails:

SELECT CAST(N'2012-02-20 08:31:35.297' AS DateTime)
Msg 242, Level 16, State 3, Line 2
The conversion of a nvarchar data type to a datetime data type resulted in an out-of-range value.

language is set to "British English" for that database and user.

**Comment by GusBeare** [comment]
So for a British user the day should come before the month:  20-02-2017 ideally.

**Comment by raphael-m** [comment]
Sorry, my mistake - of course, my tests were not useful. I was able to reproduce the issue by setting the users default language to British English.

We will add `SET LANGUAGE English` on top of the `00.99.00.SqlDataProvider` file which sets the session language to English ([more](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-language-transact-sql)). This changes the datetime format that CAST expects to what we actually use in the insert statements.

**Comment by contact2adil** [comment]
Hi Danial,

My Installation also failed due to Object Qualifier issue.
Problem is now my system is behaving wierd, specially the UI part.
Looks like with failed installation also, the setup created 2 folders in DM folder.

I really need to clean whatever has been installed in my setup to get my site working properly.

Do you have any script or step to clean the items installed during failed installation f 2sxc module.

Kind Regards,

**Comment by iJungleboy** [comment]
@contact2adil There is no helper script for this, sorry. Basically all the sql stuff starts with dbo.Tosic_... (tables and stored procedures) so it's easy to clean, but I assume that it probably didn't create any tables. 

Then there's the folder in DB (easy to clean).

The hardest part would be removing the DLLs, if any were added. Here you'll have to do some guessing - or just compare the file list with the backup.

**Comment by contact2adil** [comment]
Thanks for your quick response Danial, I think I have messed up my site badly.
I have not yet been able to fix the issue. Looks like the installation has also changed web.config setting and some file permission.
does sxc module installtion make any change to file permission or web.cofig?

**Comment by iJungleboy** [comment]
@contact2adil no, 2sxc doesn't change file permissions. 

The installation does add the image-resizer to the web.config, but it adds a comment into the file.

**Comment by contact2adil** [comment]
Thx for your response.

**Comment by iJungleboy** [comment]
@weeksandy our entity-framework implementation has moved to EF Core (we want to be future-ready) so that example won't help in any way. 

Support for this: Basically it's a question of resources - to support this will take someone 3-5 days of work, to implement, test, and test for consequences in various upgrade situations. We (2sic) won't invest into this as we this issue, but anybody else is welcome to do it, or to request this as paid support.

**Comment by weeksandy** [comment]
@iJungleboy Appreciate the quick response and we certainly appreciate the resource issue.  We want to discuss internally if it makes sense for us to tackle it.  We would want to do it so it was part of the 2sxc source going forward.

We don't do any current work at the Entity Framework or EF Core level.  Is there any guidance you can provide as to how an implementation to handle the object qualifiers might differ for EF Core versus Entity Framework, that was discussed in the previous thread (https://dnnentityframework.codeplex.com/).

Thanks,

Andy

**Comment by iJungleboy** [comment]
@weeksandy I cannot really give any guidance ATM. I believe the implementation itself isn't such a big deal, but the big work will be testing various scenarios from new-install on dnn 7/8/9 to various upgrade cases.
