### ISSUE TITLE
Not able to add an item after upgrade

### ISSUE THREAD

**Issue by andyduo** [2sic/2sxc#951]
I just upgraded to version 8.5.3 and this seems to have broken the ability to add an item to a list in my app. There is no blue + button showing in the content toolbar and if I try to add an item from the Action menu it throws an error. See attached file for error details:
![capture](https://cloud.githubusercontent.com/assets/358112/18737964/4bdf0bca-80eb-11e6-8efa-403d7a5beb86.PNG)

DNN version is 08.00.03

**Comment by iJungleboy** [comment]
@andy what version were you using previously? What code are you using to generate the standalone "+" button?

**Comment by andyduo** [comment]
I have had to roll back so I am on version 7.2.3. I'm using the [Content:Toolbar] token to generate the toolbar. On version 7.2.3 this works OK as the Add/New Item button shows in the toolbar but after the upgrade it shows the toolbar without an Add/New Item button.

**Comment by iJungleboy** [comment]
Ok, sorry for the rollback. i'll try to explain what happened and how to go about it.

You are using a template in the data-mode - check http://2sxc.org/en/blog/post/12-differences-when-templating-data-instead-of-content.

In older versions, 2sxc had a [+] button in the toolbar, which caused usability problems. Why? because the + usually should add an item "right after" the toolbar you clicked it on. This doesn't behave that way in data-mode, where usually some kind of sorting is applied. So people would click + and then the item would be somewhere unexpected, making them think it wasn't created at all. 

So the correct solution is to create a separate + button, and everything is fine and behaves as expected.  There are quite a few ways to do this, the easiest is when using Razor with the @Edit.Toolbar(...) command. With tokens you will need to do it using JavaScript, because there is no server-code that generates this. Which would you like? I'll point you in the right directions. 

Note that I'll close the issue, but still answer your questions.

**Comment by andyduo** [comment]
OK thanks for the clarification. It is a token template in this case, although I do use Razor now this was done a while ago so a token template option would be fantastic. Also a remove item button would be a big help too.

Also for razor where can i see/learn to use the @Edit.Toolbar(...) command you mention?

Thanks!

**Comment by iJungleboy** [comment]
I'm just writing the docs :) 

https://github.com/2sic/2sxc/wiki/Razor-Edit

**Comment by andyduo** [comment]
Hi there, so I converted one of my App templates to Razor and added the @Edit.Toolbar(cont) tag to the template but I still don't see a remove icon in the rendered toolbar like you do in a normal content template. How can I add a remove item button in my app so the user can delete an item?

Thanks.

**Comment by andyduo** [comment]
As an update I used this code:
<a onclick='$2sxc(this).manage.run({"action": "remove", "entityId": @cont.EntityId})'>remove #@cont.EntityId</a>

This brings up a popup saying the item will be removed, when I click OK I get another popup saying 404 Bad Request

**Comment by iJungleboy** [comment]
Remove is a list-functionality, which requires the items to be added/removed to the list as you want to - check out http://2sxc.org/en/blog/post/12-differences-when-templating-data-instead-of-content
