### ISSUE TITLE
Feature Request: Event Notifications

### ISSUE THREAD

**Issue by mryckman** [2sic/2sxc#965]
I'm sure this has come up before, but it would be very cool if there was a way to attach actions to events within a data type. This would enable sending an email when a new item is added, for example.  I would imagine it would be sensible to add this to the data type, then let the admin build an action and specify the event that calls that action... something like that.

If the emails were pretty customizable, they could facilitate workflow, let a user know we've received their comments, or whatever.

**Comment by iJungleboy** [comment]
Just to brainstorm this a bit, these are probably common actions:

1. Before Save - allowing you to do something, change the data, or cancel the save
2. After Save - allowing you to do something
3. Before Delete
4. After Delete

What would have to be figured out

1. A core issue would be the data-type transferred to these API; the common DynamicEntity wouldn't quite do, because you have other issues with data-before/after
2. Another problem is multiple items - should a query call each before/after once? this could cause quite a bit of problems with performance, as each save would probably invalidate the cache, requiring a cache-reload which may be a bit expensive
3. Where to put the code, especially because it would cause some issues in debugging the code if it only runs in hidden mode and be hard to develop
4. Where to register that you have a custom event...

**Comment by mangiove** [comment]
Maybe instead of emails it would be less impact to initially just do an event registry? Where admin can see whats happened...
And select whats events would be registered...

**Comment by iJungleboy** [comment]
An event-system would be a completely different feature and would again actually be fairly complex, especially if certain people would want notifications only in specific cases and not in others. So I believe the "simplest, most versatile" solution is a simple API, which allows people to code whatever they want to happen. Then people could create events, logs, send mails, update something else, etc.

**Comment by mryckman** [comment]
Thanks Daniel - I suspect you're right... both about the approach and the complexity. I'd wondered about something visually managed - a bit like the query designer. Maybe the root object could represent an event in a data source where the result (presumably the updated/inserted/deleted record) could flow to different tasks assignable by the user. Perhaps those "tasks" could include things like "Log Event", "Send Email", "Execute Code", etc., but also include things like the "Value Filter" and other procedural things.

I don't know - in any case, it does seem difficult.

**Comment by iJungleboy** [comment]
@mryckman such a generic workflow system can be created - but it would take a total of about 4 weeks work to do right. So without a sponsor it would be simply impossible, while providing a simpler "these are the events, you can write c# code for them" would be more likely because it's just much less work.

**Comment by iJungleboy** [comment]
will close for now...
